// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: gateway.proto

package rpcPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GmKickPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`     // 玩家id
	ServerId      int32                  `protobuf:"varint,2,opt,name=serverId,proto3" json:"serverId,omitempty"` // 服务器id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GmKickPlayerReq) Reset() {
	*x = GmKickPlayerReq{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GmKickPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GmKickPlayerReq) ProtoMessage() {}

func (x *GmKickPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GmKickPlayerReq.ProtoReflect.Descriptor instead.
func (*GmKickPlayerReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GmKickPlayerReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GmKickPlayerReq) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type NotifyAllianceChangeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`         // 玩家id
	ChangeOper    int32                  `protobuf:"varint,2,opt,name=changeOper,proto3" json:"changeOper,omitempty"` // 联盟操作
	AllianceId    int64                  `protobuf:"varint,3,opt,name=allianceId,proto3" json:"allianceId,omitempty"` // 联盟id
	Items         []*ItemInfo            `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyAllianceChangeReq) Reset() {
	*x = NotifyAllianceChangeReq{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyAllianceChangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyAllianceChangeReq) ProtoMessage() {}

func (x *NotifyAllianceChangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAllianceChangeReq.ProtoReflect.Descriptor instead.
func (*NotifyAllianceChangeReq) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyAllianceChangeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotifyAllianceChangeReq) GetChangeOper() int32 {
	if x != nil {
		return x.ChangeOper
	}
	return 0
}

func (x *NotifyAllianceChangeReq) GetAllianceId() int64 {
	if x != nil {
		return x.AllianceId
	}
	return 0
}

func (x *NotifyAllianceChangeReq) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x05rpcPb\x1a\fcommon.proto\"E\n" +
	"\x0fGmKickPlayerReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bserverId\x18\x02 \x01(\x05R\bserverId\"\x98\x01\n" +
	"\x17NotifyAllianceChangeReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"changeOper\x18\x02 \x01(\x05R\n" +
	"changeOper\x12\x1e\n" +
	"\n" +
	"allianceId\x18\x03 \x01(\x03R\n" +
	"allianceId\x12%\n" +
	"\x05items\x18\x04 \x03(\v2\x0f.rpcPb.ItemInfoR\x05items2\xd9\x02\n" +
	"\vGateService\x12-\n" +
	"\bSayHello\x12\x0f.rpcPb.HelloReq\x1a\x10.rpcPb.HelloResp\x12F\n" +
	"\x13DeliverRechargeItem\x12\x1d.rpcPb.DeliverRechargeItemReq\x1a\x10.rpcPb.EmptyResp\x12O\n" +
	"\x1cNotifyServerOperationHandler\x12\x1d.rpcPb.NotifyOperationMessage\x1a\x10.rpcPb.EmptyResp\x12H\n" +
	"\x14NotifyAllianceChange\x12\x1e.rpcPb.NotifyAllianceChangeReq\x1a\x10.rpcPb.EmptyResp\x128\n" +
	"\fGmKickPlayer\x12\x16.rpcPb.GmKickPlayerReq\x1a\x10.rpcPb.EmptyRespB3Z1github.com/drop/GoServer/server/logic/rpcPb;rpcPbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_proto_goTypes = []any{
	(*GmKickPlayerReq)(nil),         // 0: rpcPb.GmKickPlayerReq
	(*NotifyAllianceChangeReq)(nil), // 1: rpcPb.NotifyAllianceChangeReq
	(*ItemInfo)(nil),                // 2: rpcPb.ItemInfo
	(*HelloReq)(nil),                // 3: rpcPb.HelloReq
	(*DeliverRechargeItemReq)(nil),  // 4: rpcPb.DeliverRechargeItemReq
	(*NotifyOperationMessage)(nil),  // 5: rpcPb.NotifyOperationMessage
	(*HelloResp)(nil),               // 6: rpcPb.HelloResp
	(*EmptyResp)(nil),               // 7: rpcPb.EmptyResp
}
var file_gateway_proto_depIdxs = []int32{
	2, // 0: rpcPb.NotifyAllianceChangeReq.items:type_name -> rpcPb.ItemInfo
	3, // 1: rpcPb.GateService.SayHello:input_type -> rpcPb.HelloReq
	4, // 2: rpcPb.GateService.DeliverRechargeItem:input_type -> rpcPb.DeliverRechargeItemReq
	5, // 3: rpcPb.GateService.NotifyServerOperationHandler:input_type -> rpcPb.NotifyOperationMessage
	1, // 4: rpcPb.GateService.NotifyAllianceChange:input_type -> rpcPb.NotifyAllianceChangeReq
	0, // 5: rpcPb.GateService.GmKickPlayer:input_type -> rpcPb.GmKickPlayerReq
	6, // 6: rpcPb.GateService.SayHello:output_type -> rpcPb.HelloResp
	7, // 7: rpcPb.GateService.DeliverRechargeItem:output_type -> rpcPb.EmptyResp
	7, // 8: rpcPb.GateService.NotifyServerOperationHandler:output_type -> rpcPb.EmptyResp
	7, // 9: rpcPb.GateService.NotifyAllianceChange:output_type -> rpcPb.EmptyResp
	7, // 10: rpcPb.GateService.GmKickPlayer:output_type -> rpcPb.EmptyResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
