configs:
  0: # SERVER_TYPE_GAME
    0: # ENV_DEVELOP
      loggerConfig:
        infoFilename: "logs/info.log"
        errorFilename: "logs/error.log"
        maxsize: 100    # MB
        maxbackups: 7
        maxage: 7       # days
        compress: true
      netConfig:
        host: "localhost"
        port: 8080
      mysqlConfig:
        dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
        maxIdleConnections: 10
        maxOpenConnections: 100
        maxLifetime: 10
      redisConfig:
        addr: "127.0.0.1:6379"
        db: 0
        poolSize: 10
      runConfig:
        dbPoolInfo:
          - poolType: 0 # DB_POOL_TYPE_LOGIN
            workerNum: 10
            workerTaskSize: 100
          - poolType: 1 # DB_POOL_TYPE_SCENE
            workerNum: 20
            workerTaskSize: 200
  1: # SERVER_TYPE_LOGIC
    0: # ENV_DEVELOP
      loggerConfig:
        infoFilename: "logs/info.log"
        errorFilename: "logs/error.log"
        maxsize: 100    # MB
        maxbackups: 7
        maxage: 7       # days
        compress: true
      netConfig:
        host: "localhost"
        port: 8080
      mysqlConfig:
        dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
        maxIdleConnections: 10
        maxOpenConnections: 100
        maxLifetime: 10
      redisConfig:
        addr: "127.0.0.1:6379"
        db: 0
        poolSize: 10
      runConfig:
        dbPoolInfo:
          - poolType: 0 # DB_POOL_TYPE_LOGIN
            workerNum: 10
            workerTaskSize: 100
          - poolType: 1 # DB_POOL_TYPE_SCENE
            workerNum: 20
            workerTaskSize: 200

