// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: chatMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfo     *PlayerBasicInfo       `protobuf:"bytes,1,opt,name=playerInfo,proto3" json:"playerInfo,omitempty"`         // 发送者玩家信息
	SendType       int32                  `protobuf:"varint,2,opt,name=sendType,proto3" json:"sendType,omitempty"`            // 聊天类型  0 私聊 1 全服通知 2 世界 3 工会
	ToObjectId     int64                  `protobuf:"varint,3,opt,name=toObjectId,proto3" json:"toObjectId,omitempty"`        // 世界/工会/私聊对象ID
	MessageContent string                 `protobuf:"bytes,4,opt,name=messageContent,proto3" json:"messageContent,omitempty"` // 消息内容
	SendTime       int64                  `protobuf:"varint,5,opt,name=sendTime,proto3" json:"sendTime,omitempty"`            // 发送时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chatMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chatMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetPlayerInfo() *PlayerBasicInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

func (x *ChatMessage) GetSendType() int32 {
	if x != nil {
		return x.SendType
	}
	return 0
}

func (x *ChatMessage) GetToObjectId() int64 {
	if x != nil {
		return x.ToObjectId
	}
	return 0
}

func (x *ChatMessage) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *ChatMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type SendChatMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatMessage   *ChatMessage           `protobuf:"bytes,1,opt,name=chatMessage,proto3" json:"chatMessage,omitempty"` // 聊天消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageReq) Reset() {
	*x = SendChatMessageReq{}
	mi := &file_chatMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageReq) ProtoMessage() {}

func (x *SendChatMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_chatMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageReq.ProtoReflect.Descriptor instead.
func (*SendChatMessageReq) Descriptor() ([]byte, []int) {
	return file_chatMessage_proto_rawDescGZIP(), []int{1}
}

func (x *SendChatMessageReq) GetChatMessage() *ChatMessage {
	if x != nil {
		return x.ChatMessage
	}
	return nil
}

type SendChatMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageResp) Reset() {
	*x = SendChatMessageResp{}
	mi := &file_chatMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResp) ProtoMessage() {}

func (x *SendChatMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_chatMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResp.ProtoReflect.Descriptor instead.
func (*SendChatMessageResp) Descriptor() ([]byte, []int) {
	return file_chatMessage_proto_rawDescGZIP(), []int{2}
}

type PushReceivedChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatMessage   *ChatMessage           `protobuf:"bytes,1,opt,name=chatMessage,proto3" json:"chatMessage,omitempty"` // 聊天消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReceivedChatMessage) Reset() {
	*x = PushReceivedChatMessage{}
	mi := &file_chatMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReceivedChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReceivedChatMessage) ProtoMessage() {}

func (x *PushReceivedChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReceivedChatMessage.ProtoReflect.Descriptor instead.
func (*PushReceivedChatMessage) Descriptor() ([]byte, []int) {
	return file_chatMessage_proto_rawDescGZIP(), []int{3}
}

func (x *PushReceivedChatMessage) GetChatMessage() *ChatMessage {
	if x != nil {
		return x.ChatMessage
	}
	return nil
}

var File_chatMessage_proto protoreflect.FileDescriptor

const file_chatMessage_proto_rawDesc = "" +
	"\n" +
	"\x11chatMessage.proto\x12\x02pb\x1a\x13commonMessage.proto\"\xc2\x01\n" +
	"\vChatMessage\x123\n" +
	"\n" +
	"playerInfo\x18\x01 \x01(\v2\x13.pb.PlayerBasicInfoR\n" +
	"playerInfo\x12\x1a\n" +
	"\bsendType\x18\x02 \x01(\x05R\bsendType\x12\x1e\n" +
	"\n" +
	"toObjectId\x18\x03 \x01(\x03R\n" +
	"toObjectId\x12&\n" +
	"\x0emessageContent\x18\x04 \x01(\tR\x0emessageContent\x12\x1a\n" +
	"\bsendTime\x18\x05 \x01(\x03R\bsendTime\"G\n" +
	"\x12SendChatMessageReq\x121\n" +
	"\vchatMessage\x18\x01 \x01(\v2\x0f.pb.ChatMessageR\vchatMessage\"\x15\n" +
	"\x13SendChatMessageResp\"L\n" +
	"\x17PushReceivedChatMessage\x121\n" +
	"\vchatMessage\x18\x01 \x01(\v2\x0f.pb.ChatMessageR\vchatMessageB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_chatMessage_proto_rawDescOnce sync.Once
	file_chatMessage_proto_rawDescData []byte
)

func file_chatMessage_proto_rawDescGZIP() []byte {
	file_chatMessage_proto_rawDescOnce.Do(func() {
		file_chatMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatMessage_proto_rawDesc), len(file_chatMessage_proto_rawDesc)))
	})
	return file_chatMessage_proto_rawDescData
}

var file_chatMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatMessage_proto_goTypes = []any{
	(*ChatMessage)(nil),             // 0: pb.ChatMessage
	(*SendChatMessageReq)(nil),      // 1: pb.SendChatMessageReq
	(*SendChatMessageResp)(nil),     // 2: pb.SendChatMessageResp
	(*PushReceivedChatMessage)(nil), // 3: pb.PushReceivedChatMessage
	(*PlayerBasicInfo)(nil),         // 4: pb.PlayerBasicInfo
}
var file_chatMessage_proto_depIdxs = []int32{
	4, // 0: pb.ChatMessage.playerInfo:type_name -> pb.PlayerBasicInfo
	0, // 1: pb.SendChatMessageReq.chatMessage:type_name -> pb.ChatMessage
	0, // 2: pb.PushReceivedChatMessage.chatMessage:type_name -> pb.ChatMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatMessage_proto_init() }
func file_chatMessage_proto_init() {
	if File_chatMessage_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatMessage_proto_rawDesc), len(file_chatMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatMessage_proto_goTypes,
		DependencyIndexes: file_chatMessage_proto_depIdxs,
		MessageInfos:      file_chatMessage_proto_msgTypes,
	}.Build()
	File_chatMessage_proto = out.File
	file_chatMessage_proto_goTypes = nil
	file_chatMessage_proto_depIdxs = nil
}
