// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: commonMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家错误推送
type MessageError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         MESSAGE_ID             `protobuf:"varint,1,opt,name=msgId,proto3,enum=pb.MESSAGE_ID" json:"msgId,omitempty"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,2,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageError) Reset() {
	*x = MessageError{}
	mi := &file_commonMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageError) ProtoMessage() {}

func (x *MessageError) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageError.ProtoReflect.Descriptor instead.
func (*MessageError) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{0}
}

func (x *MessageError) GetMsgId() MESSAGE_ID {
	if x != nil {
		return x.MsgId
	}
	return MESSAGE_ID_BEGIN
}

func (x *MessageError) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

type ExchangeItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExchangeId    int32                  `protobuf:"varint,1,opt,name=exchangeId,proto3" json:"exchangeId,omitempty"`
	ExchangeNum   int32                  `protobuf:"varint,2,opt,name=exchangeNum,proto3" json:"exchangeNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeItemReq) Reset() {
	*x = ExchangeItemReq{}
	mi := &file_commonMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeItemReq) ProtoMessage() {}

func (x *ExchangeItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeItemReq.ProtoReflect.Descriptor instead.
func (*ExchangeItemReq) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeItemReq) GetExchangeId() int32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *ExchangeItemReq) GetExchangeNum() int32 {
	if x != nil {
		return x.ExchangeNum
	}
	return 0
}

type ExchangeItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeItemResp) Reset() {
	*x = ExchangeItemResp{}
	mi := &file_commonMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeItemResp) ProtoMessage() {}

func (x *ExchangeItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeItemResp.ProtoReflect.Descriptor instead.
func (*ExchangeItemResp) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{2}
}

type PushFunctionChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*FunctionOpenInfo    `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFunctionChange) Reset() {
	*x = PushFunctionChange{}
	mi := &file_commonMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFunctionChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFunctionChange) ProtoMessage() {}

func (x *PushFunctionChange) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFunctionChange.ProtoReflect.Descriptor instead.
func (*PushFunctionChange) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{3}
}

func (x *PushFunctionChange) GetInfos() []*FunctionOpenInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

// 推送物品变更
type PushItemChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           ITEM_CHANGE_TYPE       `protobuf:"varint,1,opt,name=type,proto3,enum=pb.ITEM_CHANGE_TYPE" json:"type,omitempty"`
	AddItemList    []*ItemBasicInfo       `protobuf:"bytes,2,rep,name=addItemList,proto3" json:"addItemList,omitempty"`
	RemoveItemList []*ItemBasicInfo       `protobuf:"bytes,3,rep,name=removeItemList,proto3" json:"removeItemList,omitempty"`
	Source         int32                  `protobuf:"varint,4,opt,name=source,proto3" json:"source,omitempty"` //来源
	IsPay          int32                  `protobuf:"varint,5,opt,name=isPay,proto3" json:"isPay,omitempty"`   //是否是支付获得，0不是 1是
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushItemChange) Reset() {
	*x = PushItemChange{}
	mi := &file_commonMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushItemChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushItemChange) ProtoMessage() {}

func (x *PushItemChange) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushItemChange.ProtoReflect.Descriptor instead.
func (*PushItemChange) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{4}
}

func (x *PushItemChange) GetType() ITEM_CHANGE_TYPE {
	if x != nil {
		return x.Type
	}
	return ITEM_CHANGE_TYPE_ITEM_CHANGE_TYPE_COMMON
}

func (x *PushItemChange) GetAddItemList() []*ItemBasicInfo {
	if x != nil {
		return x.AddItemList
	}
	return nil
}

func (x *PushItemChange) GetRemoveItemList() []*ItemBasicInfo {
	if x != nil {
		return x.RemoveItemList
	}
	return nil
}

func (x *PushItemChange) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *PushItemChange) GetIsPay() int32 {
	if x != nil {
		return x.IsPay
	}
	return 0
}

type PlayerGMMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuncId        int32                  `protobuf:"varint,1,opt,name=funcId,proto3" json:"funcId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGMMessage) Reset() {
	*x = PlayerGMMessage{}
	mi := &file_commonMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGMMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGMMessage) ProtoMessage() {}

func (x *PlayerGMMessage) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGMMessage.ProtoReflect.Descriptor instead.
func (*PlayerGMMessage) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerGMMessage) GetFuncId() int32 {
	if x != nil {
		return x.FuncId
	}
	return 0
}

func (x *PlayerGMMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 功能开启数据
type FunctionOpenInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FuncId         int32                  `protobuf:"varint,1,opt,name=funcId,proto3" json:"funcId,omitempty"`                 // 功能id
	Status         int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                 // 功能状态。0关闭，1可见，2可用
	RewardCommited int32                  `protobuf:"varint,3,opt,name=rewardCommited,proto3" json:"rewardCommited,omitempty"` // 领取的奖励是否已经提交
	UnlockTime     int64                  `protobuf:"varint,4,opt,name=unlockTime,proto3" json:"unlockTime,omitempty"`         //系统解锁时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionOpenInfo) Reset() {
	*x = FunctionOpenInfo{}
	mi := &file_commonMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOpenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOpenInfo) ProtoMessage() {}

func (x *FunctionOpenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOpenInfo.ProtoReflect.Descriptor instead.
func (*FunctionOpenInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionOpenInfo) GetFuncId() int32 {
	if x != nil {
		return x.FuncId
	}
	return 0
}

func (x *FunctionOpenInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FunctionOpenInfo) GetRewardCommited() int32 {
	if x != nil {
		return x.RewardCommited
	}
	return 0
}

func (x *FunctionOpenInfo) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

type ItemBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemBasicInfo) Reset() {
	*x = ItemBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBasicInfo) ProtoMessage() {}

func (x *ItemBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBasicInfo.ProtoReflect.Descriptor instead.
func (*ItemBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{7}
}

func (x *ItemBasicInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemBasicInfo) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 物品信息
type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`    // 配置ID
	ItemNum       int64                  `protobuf:"varint,2,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"` // 数据
	ItemUid       int32                  `protobuf:"varint,3,opt,name=item_uid,json=itemUid,proto3" json:"item_uid,omitempty"` // 唯一
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_commonMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInfo) GetItemNum() int64 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

func (x *ItemInfo) GetItemUid() int32 {
	if x != nil {
		return x.ItemUid
	}
	return 0
}

type InventoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfo            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryData) Reset() {
	*x = InventoryData{}
	mi := &file_commonMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryData) ProtoMessage() {}

func (x *InventoryData) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryData.ProtoReflect.Descriptor instead.
func (*InventoryData) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryData) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type PlayerBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	ServerId      int32                  `protobuf:"varint,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	HeadId        int32                  `protobuf:"varint,6,opt,name=headId,proto3" json:"headId,omitempty"`
	HeadFrameId   int32                  `protobuf:"varint,7,opt,name=headFrameId,proto3" json:"headFrameId,omitempty"`
	TitleId       int32                  `protobuf:"varint,8,opt,name=titleId,proto3" json:"titleId,omitempty"`
	Level         int32                  `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	BubbleId      int32                  `protobuf:"varint,10,opt,name=bubbleId,proto3" json:"bubbleId,omitempty"`       // 对话框id
	ImageId       int32                  `protobuf:"varint,11,opt,name=imageId,proto3" json:"imageId,omitempty"`         // 小人id
	ChargeCount   int32                  `protobuf:"varint,12,opt,name=chargeCount,proto3" json:"chargeCount,omitempty"` // 充值数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBasicInfo) Reset() {
	*x = PlayerBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBasicInfo) ProtoMessage() {}

func (x *PlayerBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBasicInfo.ProtoReflect.Descriptor instead.
func (*PlayerBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerBasicInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlayerBasicInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PlayerBasicInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *PlayerBasicInfo) GetHeadId() int32 {
	if x != nil {
		return x.HeadId
	}
	return 0
}

func (x *PlayerBasicInfo) GetHeadFrameId() int32 {
	if x != nil {
		return x.HeadFrameId
	}
	return 0
}

func (x *PlayerBasicInfo) GetTitleId() int32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *PlayerBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerBasicInfo) GetBubbleId() int32 {
	if x != nil {
		return x.BubbleId
	}
	return 0
}

func (x *PlayerBasicInfo) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *PlayerBasicInfo) GetChargeCount() int32 {
	if x != nil {
		return x.ChargeCount
	}
	return 0
}

type PlayerAllianceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllianceId    int64                  `protobuf:"varint,1,opt,name=allianceId,proto3" json:"allianceId,omitempty"`
	AllianceName  string                 `protobuf:"bytes,2,opt,name=allianceName,proto3" json:"allianceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAllianceInfo) Reset() {
	*x = PlayerAllianceInfo{}
	mi := &file_commonMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAllianceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAllianceInfo) ProtoMessage() {}

func (x *PlayerAllianceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAllianceInfo.ProtoReflect.Descriptor instead.
func (*PlayerAllianceInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerAllianceInfo) GetAllianceId() int64 {
	if x != nil {
		return x.AllianceId
	}
	return 0
}

func (x *PlayerAllianceInfo) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

type PlayerFormationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormationId   int32                  `protobuf:"varint,1,opt,name=formationId,proto3" json:"formationId,omitempty"`
	FormationType int32                  `protobuf:"varint,2,opt,name=formationType,proto3" json:"formationType,omitempty"`
	Infos         []*HeroBagInfo         `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerFormationDetail) Reset() {
	*x = PlayerFormationDetail{}
	mi := &file_commonMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerFormationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFormationDetail) ProtoMessage() {}

func (x *PlayerFormationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFormationDetail.ProtoReflect.Descriptor instead.
func (*PlayerFormationDetail) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerFormationDetail) GetFormationId() int32 {
	if x != nil {
		return x.FormationId
	}
	return 0
}

func (x *PlayerFormationDetail) GetFormationType() int32 {
	if x != nil {
		return x.FormationType
	}
	return 0
}

func (x *PlayerFormationDetail) GetInfos() []*HeroBagInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type SceneBasicInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceId         int32                  `protobuf:"varint,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	StageId            int32                  `protobuf:"varint,2,opt,name=stageId,proto3" json:"stageId,omitempty"`
	CurrentSubStageId  int32                  `protobuf:"varint,3,opt,name=currentSubStageId,proto3" json:"currentSubStageId,omitempty"`
	SubStageInfos      []*SubStageInfo        `protobuf:"bytes,4,rep,name=subStageInfos,proto3" json:"subStageInfos,omitempty"`
	AllMonsterTemplate []*MonsterTemplateInfo `protobuf:"bytes,5,rep,name=allMonsterTemplate,proto3" json:"allMonsterTemplate,omitempty"`
	RandomSeed         int64                  `protobuf:"varint,6,opt,name=randomSeed,proto3" json:"randomSeed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SceneBasicInfo) Reset() {
	*x = SceneBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneBasicInfo) ProtoMessage() {}

func (x *SceneBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneBasicInfo.ProtoReflect.Descriptor instead.
func (*SceneBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{13}
}

func (x *SceneBasicInfo) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *SceneBasicInfo) GetStageId() int32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *SceneBasicInfo) GetCurrentSubStageId() int32 {
	if x != nil {
		return x.CurrentSubStageId
	}
	return 0
}

func (x *SceneBasicInfo) GetSubStageInfos() []*SubStageInfo {
	if x != nil {
		return x.SubStageInfos
	}
	return nil
}

func (x *SceneBasicInfo) GetAllMonsterTemplate() []*MonsterTemplateInfo {
	if x != nil {
		return x.AllMonsterTemplate
	}
	return nil
}

func (x *SceneBasicInfo) GetRandomSeed() int64 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

type SubStageInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubStageId         int32                  `protobuf:"varint,1,opt,name=subStageId,proto3" json:"subStageId,omitempty"`
	RoomId             int32                  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MonsterInfos       []*MonsterInfo         `protobuf:"bytes,3,rep,name=monsterInfos,proto3" json:"monsterInfos,omitempty"`
	IsCyCle            int32                  `protobuf:"varint,4,opt,name=isCyCle,proto3" json:"isCyCle,omitempty"`
	HeroInfos          []*HeroBasicInfo       `protobuf:"bytes,5,rep,name=heroInfos,proto3" json:"heroInfos,omitempty"`
	PlayerLevel        int32                  `protobuf:"varint,6,opt,name=playerLevel,proto3" json:"playerLevel,omitempty"`
	SelfComboSkillIds  []int32                `protobuf:"varint,7,rep,packed,name=selfComboSkillIds,proto3" json:"selfComboSkillIds,omitempty"`
	EnemyComboSkillIds []int32                `protobuf:"varint,8,rep,packed,name=enemyComboSkillIds,proto3" json:"enemyComboSkillIds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubStageInfo) Reset() {
	*x = SubStageInfo{}
	mi := &file_commonMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubStageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubStageInfo) ProtoMessage() {}

func (x *SubStageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubStageInfo.ProtoReflect.Descriptor instead.
func (*SubStageInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{14}
}

func (x *SubStageInfo) GetSubStageId() int32 {
	if x != nil {
		return x.SubStageId
	}
	return 0
}

func (x *SubStageInfo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SubStageInfo) GetMonsterInfos() []*MonsterInfo {
	if x != nil {
		return x.MonsterInfos
	}
	return nil
}

func (x *SubStageInfo) GetIsCyCle() int32 {
	if x != nil {
		return x.IsCyCle
	}
	return 0
}

func (x *SubStageInfo) GetHeroInfos() []*HeroBasicInfo {
	if x != nil {
		return x.HeroInfos
	}
	return nil
}

func (x *SubStageInfo) GetPlayerLevel() int32 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

func (x *SubStageInfo) GetSelfComboSkillIds() []int32 {
	if x != nil {
		return x.SelfComboSkillIds
	}
	return nil
}

func (x *SubStageInfo) GetEnemyComboSkillIds() []int32 {
	if x != nil {
		return x.EnemyComboSkillIds
	}
	return nil
}

type MonsterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	SpawnId       string                 `protobuf:"bytes,2,opt,name=spawnId,proto3" json:"spawnId,omitempty"`
	WaveSequence  int32                  `protobuf:"varint,3,opt,name=waveSequence,proto3" json:"waveSequence,omitempty"`
	MonsterId     int32                  `protobuf:"varint,4,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Drops         []*ItemBasicInfo       `protobuf:"bytes,7,rep,name=drops,proto3" json:"drops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterInfo) Reset() {
	*x = MonsterInfo{}
	mi := &file_commonMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterInfo) ProtoMessage() {}

func (x *MonsterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterInfo.ProtoReflect.Descriptor instead.
func (*MonsterInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{15}
}

func (x *MonsterInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MonsterInfo) GetSpawnId() string {
	if x != nil {
		return x.SpawnId
	}
	return ""
}

func (x *MonsterInfo) GetWaveSequence() int32 {
	if x != nil {
		return x.WaveSequence
	}
	return 0
}

func (x *MonsterInfo) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterInfo) GetDrops() []*ItemBasicInfo {
	if x != nil {
		return x.Drops
	}
	return nil
}

type HeroBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroId        int32                  `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	BasicInfo     *CharactorBasicInfo    `protobuf:"bytes,2,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroBasicInfo) Reset() {
	*x = HeroBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroBasicInfo) ProtoMessage() {}

func (x *HeroBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroBasicInfo.ProtoReflect.Descriptor instead.
func (*HeroBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{16}
}

func (x *HeroBasicInfo) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroBasicInfo) GetBasicInfo() *CharactorBasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

type MonsterTemplateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterId     int32                  `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	UnitId        int32                  `protobuf:"varint,2,opt,name=unitId,proto3" json:"unitId,omitempty"`
	AtkSpeed      int32                  `protobuf:"varint,3,opt,name=atkSpeed,proto3" json:"atkSpeed,omitempty"`
	MoveSpeed     int32                  `protobuf:"varint,4,opt,name=moveSpeed,proto3" json:"moveSpeed,omitempty"`
	PatrolRange   int32                  `protobuf:"varint,5,opt,name=patrolRange,proto3" json:"patrolRange,omitempty"`
	AggroRange    int32                  `protobuf:"varint,6,opt,name=aggroRange,proto3" json:"aggroRange,omitempty"`
	AttackRange   int32                  `protobuf:"varint,7,opt,name=attackRange,proto3" json:"attackRange,omitempty"`
	Attrs         map[int32]int64        `protobuf:"bytes,8,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	BasicSkill    int32                  `protobuf:"varint,9,opt,name=basicSkill,proto3" json:"basicSkill,omitempty"`
	SkillIds      []int32                `protobuf:"varint,10,rep,packed,name=skillIds,proto3" json:"skillIds,omitempty"`
	PetBattleInfo *PetBattleInfo         `protobuf:"bytes,11,opt,name=petBattleInfo,proto3" json:"petBattleInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterTemplateInfo) Reset() {
	*x = MonsterTemplateInfo{}
	mi := &file_commonMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterTemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterTemplateInfo) ProtoMessage() {}

func (x *MonsterTemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterTemplateInfo.ProtoReflect.Descriptor instead.
func (*MonsterTemplateInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{17}
}

func (x *MonsterTemplateInfo) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterTemplateInfo) GetUnitId() int32 {
	if x != nil {
		return x.UnitId
	}
	return 0
}

func (x *MonsterTemplateInfo) GetAtkSpeed() int32 {
	if x != nil {
		return x.AtkSpeed
	}
	return 0
}

func (x *MonsterTemplateInfo) GetMoveSpeed() int32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *MonsterTemplateInfo) GetPatrolRange() int32 {
	if x != nil {
		return x.PatrolRange
	}
	return 0
}

func (x *MonsterTemplateInfo) GetAggroRange() int32 {
	if x != nil {
		return x.AggroRange
	}
	return 0
}

func (x *MonsterTemplateInfo) GetAttackRange() int32 {
	if x != nil {
		return x.AttackRange
	}
	return 0
}

func (x *MonsterTemplateInfo) GetAttrs() map[int32]int64 {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *MonsterTemplateInfo) GetBasicSkill() int32 {
	if x != nil {
		return x.BasicSkill
	}
	return 0
}

func (x *MonsterTemplateInfo) GetSkillIds() []int32 {
	if x != nil {
		return x.SkillIds
	}
	return nil
}

func (x *MonsterTemplateInfo) GetPetBattleInfo() *PetBattleInfo {
	if x != nil {
		return x.PetBattleInfo
	}
	return nil
}

type CharactorBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attrs         map[int32]int64        `protobuf:"bytes,1,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkillIds      *SkillsInfo            `protobuf:"bytes,2,opt,name=skillIds,proto3" json:"skillIds,omitempty"`
	UnitsId       int32                  `protobuf:"varint,3,opt,name=unitsId,proto3" json:"unitsId,omitempty"`
	AttackRange   int32                  `protobuf:"varint,4,opt,name=attackRange,proto3" json:"attackRange,omitempty"`
	PetBattleInfo *PetBattleInfo         `protobuf:"bytes,5,opt,name=petBattleInfo,proto3" json:"petBattleInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharactorBasicInfo) Reset() {
	*x = CharactorBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharactorBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharactorBasicInfo) ProtoMessage() {}

func (x *CharactorBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharactorBasicInfo.ProtoReflect.Descriptor instead.
func (*CharactorBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{18}
}

func (x *CharactorBasicInfo) GetAttrs() map[int32]int64 {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CharactorBasicInfo) GetSkillIds() *SkillsInfo {
	if x != nil {
		return x.SkillIds
	}
	return nil
}

func (x *CharactorBasicInfo) GetUnitsId() int32 {
	if x != nil {
		return x.UnitsId
	}
	return 0
}

func (x *CharactorBasicInfo) GetAttackRange() int32 {
	if x != nil {
		return x.AttackRange
	}
	return 0
}

func (x *CharactorBasicInfo) GetPetBattleInfo() *PetBattleInfo {
	if x != nil {
		return x.PetBattleInfo
	}
	return nil
}

// 宠物战斗信息
type PetBattleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	PetId         int32                  `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Star          int32                  `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`
	SkillList     []int32                `protobuf:"varint,5,rep,packed,name=skillList,proto3" json:"skillList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetBattleInfo) Reset() {
	*x = PetBattleInfo{}
	mi := &file_commonMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetBattleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetBattleInfo) ProtoMessage() {}

func (x *PetBattleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetBattleInfo.ProtoReflect.Descriptor instead.
func (*PetBattleInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{19}
}

func (x *PetBattleInfo) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetBattleInfo) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetBattleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetBattleInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *PetBattleInfo) GetSkillList() []int32 {
	if x != nil {
		return x.SkillList
	}
	return nil
}

type SkillsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicSkill    int32                  `protobuf:"varint,1,opt,name=basicSkill,proto3" json:"basicSkill,omitempty"`      // 基础技能
	SkillList     []int32                `protobuf:"varint,2,rep,packed,name=skillList,proto3" json:"skillList,omitempty"` // 其余技能List
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillsInfo) Reset() {
	*x = SkillsInfo{}
	mi := &file_commonMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillsInfo) ProtoMessage() {}

func (x *SkillsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillsInfo.ProtoReflect.Descriptor instead.
func (*SkillsInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{20}
}

func (x *SkillsInfo) GetBasicSkill() int32 {
	if x != nil {
		return x.BasicSkill
	}
	return 0
}

func (x *SkillsInfo) GetSkillList() []int32 {
	if x != nil {
		return x.SkillList
	}
	return nil
}

// 活动信息
type ActivityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"` // 活动ID
	SettleTime    int64                  `protobuf:"varint,2,opt,name=settleTime,proto3" json:"settleTime,omitempty"` // 结算时间
	EndTime       int64                  `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`       // 结束时间
	Locked        bool                   `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`         // 是否锁定
	StartTime     int64                  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 开启时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	mi := &file_commonMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{21}
}

func (x *ActivityInfo) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityInfo) GetSettleTime() int64 {
	if x != nil {
		return x.SettleTime
	}
	return 0
}

func (x *ActivityInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ActivityInfo) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *ActivityInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// 剧情完成请求
type StoryFinishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       int32                  `protobuf:"varint,1,opt,name=storyId,proto3" json:"storyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryFinishReq) Reset() {
	*x = StoryFinishReq{}
	mi := &file_commonMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryFinishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryFinishReq) ProtoMessage() {}

func (x *StoryFinishReq) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryFinishReq.ProtoReflect.Descriptor instead.
func (*StoryFinishReq) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{22}
}

func (x *StoryFinishReq) GetStoryId() int32 {
	if x != nil {
		return x.StoryId
	}
	return 0
}

type StoryFinishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryFinishResp) Reset() {
	*x = StoryFinishResp{}
	mi := &file_commonMessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryFinishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryFinishResp) ProtoMessage() {}

func (x *StoryFinishResp) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryFinishResp.ProtoReflect.Descriptor instead.
func (*StoryFinishResp) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{23}
}

type HeroShowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          int32                  `protobuf:"varint,1,opt,name=unit,proto3" json:"unit,omitempty"`
	PetId         int32                  `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroShowInfo) Reset() {
	*x = HeroShowInfo{}
	mi := &file_commonMessage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroShowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroShowInfo) ProtoMessage() {}

func (x *HeroShowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroShowInfo.ProtoReflect.Descriptor instead.
func (*HeroShowInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{24}
}

func (x *HeroShowInfo) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *HeroShowInfo) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type AccessoryDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessoryId    int32                  `protobuf:"varint,1,opt,name=accessoryId,proto3" json:"accessoryId,omitempty"`       // 饰品id
	AccessoryLevel int32                  `protobuf:"varint,2,opt,name=accessoryLevel,proto3" json:"accessoryLevel,omitempty"` // 饰品等级
	AccessoryNum   int32                  `protobuf:"varint,3,opt,name=accessoryNum,proto3" json:"accessoryNum,omitempty"`     // 饰品数量
	HeroOwnId      int64                  `protobuf:"varint,4,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`           // 英雄唯一id
	Power          int64                  `protobuf:"varint,5,opt,name=power,proto3" json:"power,omitempty"`                   // 战力
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccessoryDetail) Reset() {
	*x = AccessoryDetail{}
	mi := &file_commonMessage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessoryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessoryDetail) ProtoMessage() {}

func (x *AccessoryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessoryDetail.ProtoReflect.Descriptor instead.
func (*AccessoryDetail) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{25}
}

func (x *AccessoryDetail) GetAccessoryId() int32 {
	if x != nil {
		return x.AccessoryId
	}
	return 0
}

func (x *AccessoryDetail) GetAccessoryLevel() int32 {
	if x != nil {
		return x.AccessoryLevel
	}
	return 0
}

func (x *AccessoryDetail) GetAccessoryNum() int32 {
	if x != nil {
		return x.AccessoryNum
	}
	return 0
}

func (x *AccessoryDetail) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *AccessoryDetail) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

// 装备详情信息
type EquipmentDetailInfo struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	EquipmentOwnId int64                      `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`                                                                   // 装备唯一ID
	EquipmentId    int32                      `protobuf:"varint,2,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`                                                                         // 装备模板ID
	HeroOwnId      int64                      `protobuf:"varint,3,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`                                                                             // 穿戴的英雄唯一ID
	Level          int32                      `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                                                     // 装备等级
	SlotType       int32                      `protobuf:"varint,5,opt,name=slotType,proto3" json:"slotType,omitempty"`                                                                               // 装备部位类型
	SlotIndex      int32                      `protobuf:"varint,6,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`                                                                             // 装备槽位索引
	StarLevel      int32                      `protobuf:"varint,7,opt,name=starLevel,proto3" json:"starLevel,omitempty"`                                                                             // 装备星级
	SetId          int32                      `protobuf:"varint,8,opt,name=setId,proto3" json:"setId,omitempty"`                                                                                     // 套装ID
	IsLocked       bool                       `protobuf:"varint,9,opt,name=isLocked,proto3" json:"isLocked,omitempty"`                                                                               // 是否锁定
	ForgeLevel     int32                      `protobuf:"varint,10,opt,name=forgeLevel,proto3" json:"forgeLevel,omitempty"`                                                                          // 锻造等级，预留字段
	BaseStats      map[int32]int32            `protobuf:"bytes,11,rep,name=baseStats,proto3" json:"baseStats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 基础属性
	AttributeAffix []*EquipmentAffixInfo      `protobuf:"bytes,12,rep,name=attributeAffix,proto3" json:"attributeAffix,omitempty"`                                                                   // 属性词条
	SkillAffix     []*EquipmentSkillAffixInfo `protobuf:"bytes,13,rep,name=skillAffix,proto3" json:"skillAffix,omitempty"`                                                                           // 技能词条
	SetInfo        *EquipmentSetInfo          `protobuf:"bytes,14,opt,name=setInfo,proto3" json:"setInfo,omitempty"`                                                                                 // 套装信息
	Power          int64                      `protobuf:"varint,15,opt,name=power,proto3" json:"power,omitempty"`                                                                                    // 战力
	StrongLevel    int32                      `protobuf:"varint,16,opt,name=strongLevel,proto3" json:"strongLevel,omitempty"`                                                                        // 强化等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentDetailInfo) Reset() {
	*x = EquipmentDetailInfo{}
	mi := &file_commonMessage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDetailInfo) ProtoMessage() {}

func (x *EquipmentDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDetailInfo.ProtoReflect.Descriptor instead.
func (*EquipmentDetailInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{26}
}

func (x *EquipmentDetailInfo) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetEquipmentId() int32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *EquipmentDetailInfo) GetStarLevel() int32 {
	if x != nil {
		return x.StarLevel
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSetId() int32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *EquipmentDetailInfo) GetForgeLevel() int32 {
	if x != nil {
		return x.ForgeLevel
	}
	return 0
}

func (x *EquipmentDetailInfo) GetBaseStats() map[int32]int32 {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *EquipmentDetailInfo) GetAttributeAffix() []*EquipmentAffixInfo {
	if x != nil {
		return x.AttributeAffix
	}
	return nil
}

func (x *EquipmentDetailInfo) GetSkillAffix() []*EquipmentSkillAffixInfo {
	if x != nil {
		return x.SkillAffix
	}
	return nil
}

func (x *EquipmentDetailInfo) GetSetInfo() *EquipmentSetInfo {
	if x != nil {
		return x.SetInfo
	}
	return nil
}

func (x *EquipmentDetailInfo) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *EquipmentDetailInfo) GetStrongLevel() int32 {
	if x != nil {
		return x.StrongLevel
	}
	return 0
}

// 装备词条信息
type EquipmentAffixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffixId       int32                  `protobuf:"varint,1,opt,name=affixId,proto3" json:"affixId,omitempty"`     // 词条ID
	StatType      int32                  `protobuf:"varint,2,opt,name=statType,proto3" json:"statType,omitempty"`   // 属性类型
	StatValue     int32                  `protobuf:"varint,3,opt,name=statValue,proto3" json:"statValue,omitempty"` // 属性数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentAffixInfo) Reset() {
	*x = EquipmentAffixInfo{}
	mi := &file_commonMessage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentAffixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentAffixInfo) ProtoMessage() {}

func (x *EquipmentAffixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentAffixInfo.ProtoReflect.Descriptor instead.
func (*EquipmentAffixInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{27}
}

func (x *EquipmentAffixInfo) GetAffixId() int32 {
	if x != nil {
		return x.AffixId
	}
	return 0
}

func (x *EquipmentAffixInfo) GetStatType() int32 {
	if x != nil {
		return x.StatType
	}
	return 0
}

func (x *EquipmentAffixInfo) GetStatValue() int32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

// 装备技能词条信息
type EquipmentSkillAffixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillAffixId  int32                  `protobuf:"varint,1,opt,name=skillAffixId,proto3" json:"skillAffixId,omitempty"` // 技能词条ID
	SkillId       int32                  `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`           // 技能ID
	SkillLevel    int32                  `protobuf:"varint,3,opt,name=skillLevel,proto3" json:"skillLevel,omitempty"`     // 技能等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentSkillAffixInfo) Reset() {
	*x = EquipmentSkillAffixInfo{}
	mi := &file_commonMessage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSkillAffixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSkillAffixInfo) ProtoMessage() {}

func (x *EquipmentSkillAffixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSkillAffixInfo.ProtoReflect.Descriptor instead.
func (*EquipmentSkillAffixInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{28}
}

func (x *EquipmentSkillAffixInfo) GetSkillAffixId() int32 {
	if x != nil {
		return x.SkillAffixId
	}
	return 0
}

func (x *EquipmentSkillAffixInfo) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *EquipmentSkillAffixInfo) GetSkillLevel() int32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

// 套装信息
type EquipmentSetInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SetId            int32                  `protobuf:"varint,1,opt,name=setId,proto3" json:"setId,omitempty"`                                                                                        // 套装ID
	ActivePieceCount int32                  `protobuf:"varint,2,opt,name=activePieceCount,proto3" json:"activePieceCount,omitempty"`                                                                  // 当前激活件数
	PieceCount       int32                  `protobuf:"varint,3,opt,name=pieceCount,proto3" json:"pieceCount,omitempty"`                                                                              // 总件数
	ActiveStats      map[int32]int32        `protobuf:"bytes,4,rep,name=activeStats,proto3" json:"activeStats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 激活属性
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EquipmentSetInfo) Reset() {
	*x = EquipmentSetInfo{}
	mi := &file_commonMessage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSetInfo) ProtoMessage() {}

func (x *EquipmentSetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSetInfo.ProtoReflect.Descriptor instead.
func (*EquipmentSetInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{29}
}

func (x *EquipmentSetInfo) GetSetId() int32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *EquipmentSetInfo) GetActivePieceCount() int32 {
	if x != nil {
		return x.ActivePieceCount
	}
	return 0
}

func (x *EquipmentSetInfo) GetPieceCount() int32 {
	if x != nil {
		return x.PieceCount
	}
	return 0
}

func (x *EquipmentSetInfo) GetActiveStats() map[int32]int32 {
	if x != nil {
		return x.ActiveStats
	}
	return nil
}

// 宠物详情信息
type PetDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`                                                                                // 宠物唯一ID
	PetId         int32                  `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`                                                                                      // 配表ID
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                                      // 等级
	Star          int32                  `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`                                                                                        // 星级（从0开始）
	HeroOwnId     int64                  `protobuf:"varint,5,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`                                                                              // 绑定英雄，0=在背包
	Attributes    map[int32]int64        `protobuf:"bytes,6,rep,name=Attributes,proto3" json:"Attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 宠物属性列表
	PassiveSkills []int32                `protobuf:"varint,7,rep,packed,name=passiveSkills,proto3" json:"passiveSkills,omitempty"`                                                               // 被动技能列表（没有则空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailInfo) Reset() {
	*x = PetDetailInfo{}
	mi := &file_commonMessage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailInfo) ProtoMessage() {}

func (x *PetDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailInfo.ProtoReflect.Descriptor instead.
func (*PetDetailInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{30}
}

func (x *PetDetailInfo) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetDetailInfo) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetDetailInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetDetailInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *PetDetailInfo) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *PetDetailInfo) GetAttributes() map[int32]int64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PetDetailInfo) GetPassiveSkills() []int32 {
	if x != nil {
		return x.PassiveSkills
	}
	return nil
}

type EquipmentBasicInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"` // 装备唯一ID
	EquipmentId    int32                  `protobuf:"varint,2,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`       // 装备模板ID
	Level          int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                   // 装备等级
	SlotType       int32                  `protobuf:"varint,4,opt,name=slotType,proto3" json:"slotType,omitempty"`             // 装备部位类型
	SlotIndex      int32                  `protobuf:"varint,5,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`           // 装备槽位索引
	StarLevel      int32                  `protobuf:"varint,6,opt,name=starLevel,proto3" json:"starLevel,omitempty"`           // 装备星级
	StrongLevel    int32                  `protobuf:"varint,7,opt,name=strongLevel,proto3" json:"strongLevel,omitempty"`       // 强化等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentBasicInfo) Reset() {
	*x = EquipmentBasicInfo{}
	mi := &file_commonMessage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentBasicInfo) ProtoMessage() {}

func (x *EquipmentBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_commonMessage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentBasicInfo.ProtoReflect.Descriptor instead.
func (*EquipmentBasicInfo) Descriptor() ([]byte, []int) {
	return file_commonMessage_proto_rawDescGZIP(), []int{31}
}

func (x *EquipmentBasicInfo) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentBasicInfo) GetEquipmentId() int32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *EquipmentBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentBasicInfo) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

func (x *EquipmentBasicInfo) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *EquipmentBasicInfo) GetStarLevel() int32 {
	if x != nil {
		return x.StarLevel
	}
	return 0
}

func (x *EquipmentBasicInfo) GetStrongLevel() int32 {
	if x != nil {
		return x.StrongLevel
	}
	return 0
}

var File_commonMessage_proto protoreflect.FileDescriptor

const file_commonMessage_proto_rawDesc = "" +
	"\n" +
	"\x13commonMessage.proto\x12\x02pb\x1a\x11messageEnum.proto\x1a\x11heroMessage.proto\"b\n" +
	"\fMessageError\x12$\n" +
	"\x05msgId\x18\x01 \x01(\x0e2\x0e.pb.MESSAGE_IDR\x05msgId\x12,\n" +
	"\terrorCode\x18\x02 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\"S\n" +
	"\x0fExchangeItemReq\x12\x1e\n" +
	"\n" +
	"exchangeId\x18\x01 \x01(\x05R\n" +
	"exchangeId\x12 \n" +
	"\vexchangeNum\x18\x02 \x01(\x05R\vexchangeNum\"\x12\n" +
	"\x10ExchangeItemResp\"@\n" +
	"\x12PushFunctionChange\x12*\n" +
	"\x05infos\x18\x01 \x03(\v2\x14.pb.FunctionOpenInfoR\x05infos\"\xd8\x01\n" +
	"\x0ePushItemChange\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.pb.ITEM_CHANGE_TYPER\x04type\x123\n" +
	"\vaddItemList\x18\x02 \x03(\v2\x11.pb.ItemBasicInfoR\vaddItemList\x129\n" +
	"\x0eremoveItemList\x18\x03 \x03(\v2\x11.pb.ItemBasicInfoR\x0eremoveItemList\x12\x16\n" +
	"\x06source\x18\x04 \x01(\x05R\x06source\x12\x14\n" +
	"\x05isPay\x18\x05 \x01(\x05R\x05isPay\"C\n" +
	"\x0fPlayerGMMessage\x12\x16\n" +
	"\x06funcId\x18\x01 \x01(\x05R\x06funcId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8a\x01\n" +
	"\x10FunctionOpenInfo\x12\x16\n" +
	"\x06funcId\x18\x01 \x01(\x05R\x06funcId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12&\n" +
	"\x0erewardCommited\x18\x03 \x01(\x05R\x0erewardCommited\x12\x1e\n" +
	"\n" +
	"unlockTime\x18\x04 \x01(\x03R\n" +
	"unlockTime\"=\n" +
	"\rItemBasicInfo\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"Y\n" +
	"\bItemInfo\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x02 \x01(\x03R\aitemNum\x12\x19\n" +
	"\bitem_uid\x18\x03 \x01(\x05R\aitemUid\"3\n" +
	"\rInventoryData\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.pb.ItemInfoR\x05items\"\xa3\x02\n" +
	"\x0fPlayerBasicInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\x12\x1a\n" +
	"\bserverId\x18\x03 \x01(\x05R\bserverId\x12\x16\n" +
	"\x06headId\x18\x06 \x01(\x05R\x06headId\x12 \n" +
	"\vheadFrameId\x18\a \x01(\x05R\vheadFrameId\x12\x18\n" +
	"\atitleId\x18\b \x01(\x05R\atitleId\x12\x14\n" +
	"\x05level\x18\t \x01(\x05R\x05level\x12\x1a\n" +
	"\bbubbleId\x18\n" +
	" \x01(\x05R\bbubbleId\x12\x18\n" +
	"\aimageId\x18\v \x01(\x05R\aimageId\x12 \n" +
	"\vchargeCount\x18\f \x01(\x05R\vchargeCount\"X\n" +
	"\x12PlayerAllianceInfo\x12\x1e\n" +
	"\n" +
	"allianceId\x18\x01 \x01(\x03R\n" +
	"allianceId\x12\"\n" +
	"\fallianceName\x18\x02 \x01(\tR\fallianceName\"\x86\x01\n" +
	"\x15PlayerFormationDetail\x12 \n" +
	"\vformationId\x18\x01 \x01(\x05R\vformationId\x12$\n" +
	"\rformationType\x18\x02 \x01(\x05R\rformationType\x12%\n" +
	"\x05infos\x18\x03 \x03(\v2\x0f.pb.HeroBagInfoR\x05infos\"\x99\x02\n" +
	"\x0eSceneBasicInfo\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\x05R\n" +
	"instanceId\x12\x18\n" +
	"\astageId\x18\x02 \x01(\x05R\astageId\x12,\n" +
	"\x11currentSubStageId\x18\x03 \x01(\x05R\x11currentSubStageId\x126\n" +
	"\rsubStageInfos\x18\x04 \x03(\v2\x10.pb.SubStageInfoR\rsubStageInfos\x12G\n" +
	"\x12allMonsterTemplate\x18\x05 \x03(\v2\x17.pb.MonsterTemplateInfoR\x12allMonsterTemplate\x12\x1e\n" +
	"\n" +
	"randomSeed\x18\x06 \x01(\x03R\n" +
	"randomSeed\"\xc6\x02\n" +
	"\fSubStageInfo\x12\x1e\n" +
	"\n" +
	"subStageId\x18\x01 \x01(\x05R\n" +
	"subStageId\x12\x16\n" +
	"\x06roomId\x18\x02 \x01(\x05R\x06roomId\x123\n" +
	"\fmonsterInfos\x18\x03 \x03(\v2\x0f.pb.monsterInfoR\fmonsterInfos\x12\x18\n" +
	"\aisCyCle\x18\x04 \x01(\x05R\aisCyCle\x12/\n" +
	"\theroInfos\x18\x05 \x03(\v2\x11.pb.HeroBasicInfoR\theroInfos\x12 \n" +
	"\vplayerLevel\x18\x06 \x01(\x05R\vplayerLevel\x12,\n" +
	"\x11selfComboSkillIds\x18\a \x03(\x05R\x11selfComboSkillIds\x12.\n" +
	"\x12enemyComboSkillIds\x18\b \x03(\x05R\x12enemyComboSkillIds\"\xa8\x01\n" +
	"\vmonsterInfo\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x18\n" +
	"\aspawnId\x18\x02 \x01(\tR\aspawnId\x12\"\n" +
	"\fwaveSequence\x18\x03 \x01(\x05R\fwaveSequence\x12\x1c\n" +
	"\tmonsterId\x18\x04 \x01(\x05R\tmonsterId\x12'\n" +
	"\x05drops\x18\a \x03(\v2\x11.pb.ItemBasicInfoR\x05drops\"]\n" +
	"\rHeroBasicInfo\x12\x16\n" +
	"\x06heroId\x18\x01 \x01(\x05R\x06heroId\x124\n" +
	"\tbasicInfo\x18\x02 \x01(\v2\x16.pb.CharactorBasicInfoR\tbasicInfo\"\xd2\x03\n" +
	"\x13MonsterTemplateInfo\x12\x1c\n" +
	"\tmonsterId\x18\x01 \x01(\x05R\tmonsterId\x12\x16\n" +
	"\x06unitId\x18\x02 \x01(\x05R\x06unitId\x12\x1a\n" +
	"\batkSpeed\x18\x03 \x01(\x05R\batkSpeed\x12\x1c\n" +
	"\tmoveSpeed\x18\x04 \x01(\x05R\tmoveSpeed\x12 \n" +
	"\vpatrolRange\x18\x05 \x01(\x05R\vpatrolRange\x12\x1e\n" +
	"\n" +
	"aggroRange\x18\x06 \x01(\x05R\n" +
	"aggroRange\x12 \n" +
	"\vattackRange\x18\a \x01(\x05R\vattackRange\x128\n" +
	"\x05attrs\x18\b \x03(\v2\".pb.MonsterTemplateInfo.AttrsEntryR\x05attrs\x12\x1e\n" +
	"\n" +
	"basicSkill\x18\t \x01(\x05R\n" +
	"basicSkill\x12\x1a\n" +
	"\bskillIds\x18\n" +
	" \x03(\x05R\bskillIds\x127\n" +
	"\rpetBattleInfo\x18\v \x01(\v2\x11.pb.PetBattleInfoR\rpetBattleInfo\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa8\x02\n" +
	"\x12CharactorBasicInfo\x127\n" +
	"\x05attrs\x18\x01 \x03(\v2!.pb.CharactorBasicInfo.AttrsEntryR\x05attrs\x12*\n" +
	"\bskillIds\x18\x02 \x01(\v2\x0e.pb.SkillsInfoR\bskillIds\x12\x18\n" +
	"\aunitsId\x18\x03 \x01(\x05R\aunitsId\x12 \n" +
	"\vattackRange\x18\x04 \x01(\x05R\vattackRange\x127\n" +
	"\rpetBattleInfo\x18\x05 \x01(\v2\x11.pb.PetBattleInfoR\rpetBattleInfo\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x89\x01\n" +
	"\rPetBattleInfo\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x05R\x05petId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04star\x18\x04 \x01(\x05R\x04star\x12\x1c\n" +
	"\tskillList\x18\x05 \x03(\x05R\tskillList\"J\n" +
	"\n" +
	"SkillsInfo\x12\x1e\n" +
	"\n" +
	"basicSkill\x18\x01 \x01(\x05R\n" +
	"basicSkill\x12\x1c\n" +
	"\tskillList\x18\x02 \x03(\x05R\tskillList\"\x9e\x01\n" +
	"\fActivityInfo\x12\x1e\n" +
	"\n" +
	"activityId\x18\x01 \x01(\x05R\n" +
	"activityId\x12\x1e\n" +
	"\n" +
	"settleTime\x18\x02 \x01(\x03R\n" +
	"settleTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\x03R\aendTime\x12\x16\n" +
	"\x06locked\x18\x04 \x01(\bR\x06locked\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x03R\tstartTime\"*\n" +
	"\x0eStoryFinishReq\x12\x18\n" +
	"\astoryId\x18\x01 \x01(\x05R\astoryId\"\x11\n" +
	"\x0fStoryFinishResp\"8\n" +
	"\fHeroShowInfo\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\x05R\x04unit\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x05R\x05petId\"\xb3\x01\n" +
	"\x0fAccessoryDetail\x12 \n" +
	"\vaccessoryId\x18\x01 \x01(\x05R\vaccessoryId\x12&\n" +
	"\x0eaccessoryLevel\x18\x02 \x01(\x05R\x0eaccessoryLevel\x12\"\n" +
	"\faccessoryNum\x18\x03 \x01(\x05R\faccessoryNum\x12\x1c\n" +
	"\theroOwnId\x18\x04 \x01(\x03R\theroOwnId\x12\x14\n" +
	"\x05power\x18\x05 \x01(\x03R\x05power\"\xa6\x05\n" +
	"\x13EquipmentDetailInfo\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12 \n" +
	"\vequipmentId\x18\x02 \x01(\x05R\vequipmentId\x12\x1c\n" +
	"\theroOwnId\x18\x03 \x01(\x03R\theroOwnId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1a\n" +
	"\bslotType\x18\x05 \x01(\x05R\bslotType\x12\x1c\n" +
	"\tslotIndex\x18\x06 \x01(\x05R\tslotIndex\x12\x1c\n" +
	"\tstarLevel\x18\a \x01(\x05R\tstarLevel\x12\x14\n" +
	"\x05setId\x18\b \x01(\x05R\x05setId\x12\x1a\n" +
	"\bisLocked\x18\t \x01(\bR\bisLocked\x12\x1e\n" +
	"\n" +
	"forgeLevel\x18\n" +
	" \x01(\x05R\n" +
	"forgeLevel\x12D\n" +
	"\tbaseStats\x18\v \x03(\v2&.pb.EquipmentDetailInfo.BaseStatsEntryR\tbaseStats\x12>\n" +
	"\x0eattributeAffix\x18\f \x03(\v2\x16.pb.EquipmentAffixInfoR\x0eattributeAffix\x12;\n" +
	"\n" +
	"skillAffix\x18\r \x03(\v2\x1b.pb.EquipmentSkillAffixInfoR\n" +
	"skillAffix\x12.\n" +
	"\asetInfo\x18\x0e \x01(\v2\x14.pb.EquipmentSetInfoR\asetInfo\x12\x14\n" +
	"\x05power\x18\x0f \x01(\x03R\x05power\x12 \n" +
	"\vstrongLevel\x18\x10 \x01(\x05R\vstrongLevel\x1a<\n" +
	"\x0eBaseStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"h\n" +
	"\x12EquipmentAffixInfo\x12\x18\n" +
	"\aaffixId\x18\x01 \x01(\x05R\aaffixId\x12\x1a\n" +
	"\bstatType\x18\x02 \x01(\x05R\bstatType\x12\x1c\n" +
	"\tstatValue\x18\x03 \x01(\x05R\tstatValue\"w\n" +
	"\x17EquipmentSkillAffixInfo\x12\"\n" +
	"\fskillAffixId\x18\x01 \x01(\x05R\fskillAffixId\x12\x18\n" +
	"\askillId\x18\x02 \x01(\x05R\askillId\x12\x1e\n" +
	"\n" +
	"skillLevel\x18\x03 \x01(\x05R\n" +
	"skillLevel\"\xfd\x01\n" +
	"\x10EquipmentSetInfo\x12\x14\n" +
	"\x05setId\x18\x01 \x01(\x05R\x05setId\x12*\n" +
	"\x10activePieceCount\x18\x02 \x01(\x05R\x10activePieceCount\x12\x1e\n" +
	"\n" +
	"pieceCount\x18\x03 \x01(\x05R\n" +
	"pieceCount\x12G\n" +
	"\vactiveStats\x18\x04 \x03(\v2%.pb.EquipmentSetInfo.ActiveStatsEntryR\vactiveStats\x1a>\n" +
	"\x10ActiveStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb1\x02\n" +
	"\rPetDetailInfo\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x05R\x05petId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04star\x18\x04 \x01(\x05R\x04star\x12\x1c\n" +
	"\theroOwnId\x18\x05 \x01(\x03R\theroOwnId\x12A\n" +
	"\n" +
	"Attributes\x18\x06 \x03(\v2!.pb.PetDetailInfo.AttributesEntryR\n" +
	"Attributes\x12$\n" +
	"\rpassiveSkills\x18\a \x03(\x05R\rpassiveSkills\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xee\x01\n" +
	"\x12EquipmentBasicInfo\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12 \n" +
	"\vequipmentId\x18\x02 \x01(\x05R\vequipmentId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1a\n" +
	"\bslotType\x18\x04 \x01(\x05R\bslotType\x12\x1c\n" +
	"\tslotIndex\x18\x05 \x01(\x05R\tslotIndex\x12\x1c\n" +
	"\tstarLevel\x18\x06 \x01(\x05R\tstarLevel\x12 \n" +
	"\vstrongLevel\x18\a \x01(\x05R\vstrongLevelB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_commonMessage_proto_rawDescOnce sync.Once
	file_commonMessage_proto_rawDescData []byte
)

func file_commonMessage_proto_rawDescGZIP() []byte {
	file_commonMessage_proto_rawDescOnce.Do(func() {
		file_commonMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commonMessage_proto_rawDesc), len(file_commonMessage_proto_rawDesc)))
	})
	return file_commonMessage_proto_rawDescData
}

var file_commonMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_commonMessage_proto_goTypes = []any{
	(*MessageError)(nil),            // 0: pb.MessageError
	(*ExchangeItemReq)(nil),         // 1: pb.ExchangeItemReq
	(*ExchangeItemResp)(nil),        // 2: pb.ExchangeItemResp
	(*PushFunctionChange)(nil),      // 3: pb.PushFunctionChange
	(*PushItemChange)(nil),          // 4: pb.PushItemChange
	(*PlayerGMMessage)(nil),         // 5: pb.PlayerGMMessage
	(*FunctionOpenInfo)(nil),        // 6: pb.FunctionOpenInfo
	(*ItemBasicInfo)(nil),           // 7: pb.ItemBasicInfo
	(*ItemInfo)(nil),                // 8: pb.ItemInfo
	(*InventoryData)(nil),           // 9: pb.InventoryData
	(*PlayerBasicInfo)(nil),         // 10: pb.PlayerBasicInfo
	(*PlayerAllianceInfo)(nil),      // 11: pb.PlayerAllianceInfo
	(*PlayerFormationDetail)(nil),   // 12: pb.PlayerFormationDetail
	(*SceneBasicInfo)(nil),          // 13: pb.SceneBasicInfo
	(*SubStageInfo)(nil),            // 14: pb.SubStageInfo
	(*MonsterInfo)(nil),             // 15: pb.monsterInfo
	(*HeroBasicInfo)(nil),           // 16: pb.HeroBasicInfo
	(*MonsterTemplateInfo)(nil),     // 17: pb.MonsterTemplateInfo
	(*CharactorBasicInfo)(nil),      // 18: pb.CharactorBasicInfo
	(*PetBattleInfo)(nil),           // 19: pb.PetBattleInfo
	(*SkillsInfo)(nil),              // 20: pb.SkillsInfo
	(*ActivityInfo)(nil),            // 21: pb.ActivityInfo
	(*StoryFinishReq)(nil),          // 22: pb.StoryFinishReq
	(*StoryFinishResp)(nil),         // 23: pb.StoryFinishResp
	(*HeroShowInfo)(nil),            // 24: pb.HeroShowInfo
	(*AccessoryDetail)(nil),         // 25: pb.AccessoryDetail
	(*EquipmentDetailInfo)(nil),     // 26: pb.EquipmentDetailInfo
	(*EquipmentAffixInfo)(nil),      // 27: pb.EquipmentAffixInfo
	(*EquipmentSkillAffixInfo)(nil), // 28: pb.EquipmentSkillAffixInfo
	(*EquipmentSetInfo)(nil),        // 29: pb.EquipmentSetInfo
	(*PetDetailInfo)(nil),           // 30: pb.PetDetailInfo
	(*EquipmentBasicInfo)(nil),      // 31: pb.EquipmentBasicInfo
	nil,                             // 32: pb.MonsterTemplateInfo.AttrsEntry
	nil,                             // 33: pb.CharactorBasicInfo.AttrsEntry
	nil,                             // 34: pb.EquipmentDetailInfo.BaseStatsEntry
	nil,                             // 35: pb.EquipmentSetInfo.ActiveStatsEntry
	nil,                             // 36: pb.PetDetailInfo.AttributesEntry
	(MESSAGE_ID)(0),                 // 37: pb.MESSAGE_ID
	(ERROR_CODE)(0),                 // 38: pb.ERROR_CODE
	(ITEM_CHANGE_TYPE)(0),           // 39: pb.ITEM_CHANGE_TYPE
	(*HeroBagInfo)(nil),             // 40: pb.HeroBagInfo
}
var file_commonMessage_proto_depIdxs = []int32{
	37, // 0: pb.MessageError.msgId:type_name -> pb.MESSAGE_ID
	38, // 1: pb.MessageError.errorCode:type_name -> pb.ERROR_CODE
	6,  // 2: pb.PushFunctionChange.infos:type_name -> pb.FunctionOpenInfo
	39, // 3: pb.PushItemChange.type:type_name -> pb.ITEM_CHANGE_TYPE
	7,  // 4: pb.PushItemChange.addItemList:type_name -> pb.ItemBasicInfo
	7,  // 5: pb.PushItemChange.removeItemList:type_name -> pb.ItemBasicInfo
	8,  // 6: pb.InventoryData.items:type_name -> pb.ItemInfo
	40, // 7: pb.PlayerFormationDetail.infos:type_name -> pb.HeroBagInfo
	14, // 8: pb.SceneBasicInfo.subStageInfos:type_name -> pb.SubStageInfo
	17, // 9: pb.SceneBasicInfo.allMonsterTemplate:type_name -> pb.MonsterTemplateInfo
	15, // 10: pb.SubStageInfo.monsterInfos:type_name -> pb.monsterInfo
	16, // 11: pb.SubStageInfo.heroInfos:type_name -> pb.HeroBasicInfo
	7,  // 12: pb.monsterInfo.drops:type_name -> pb.ItemBasicInfo
	18, // 13: pb.HeroBasicInfo.basicInfo:type_name -> pb.CharactorBasicInfo
	32, // 14: pb.MonsterTemplateInfo.attrs:type_name -> pb.MonsterTemplateInfo.AttrsEntry
	19, // 15: pb.MonsterTemplateInfo.petBattleInfo:type_name -> pb.PetBattleInfo
	33, // 16: pb.CharactorBasicInfo.attrs:type_name -> pb.CharactorBasicInfo.AttrsEntry
	20, // 17: pb.CharactorBasicInfo.skillIds:type_name -> pb.SkillsInfo
	19, // 18: pb.CharactorBasicInfo.petBattleInfo:type_name -> pb.PetBattleInfo
	34, // 19: pb.EquipmentDetailInfo.baseStats:type_name -> pb.EquipmentDetailInfo.BaseStatsEntry
	27, // 20: pb.EquipmentDetailInfo.attributeAffix:type_name -> pb.EquipmentAffixInfo
	28, // 21: pb.EquipmentDetailInfo.skillAffix:type_name -> pb.EquipmentSkillAffixInfo
	29, // 22: pb.EquipmentDetailInfo.setInfo:type_name -> pb.EquipmentSetInfo
	35, // 23: pb.EquipmentSetInfo.activeStats:type_name -> pb.EquipmentSetInfo.ActiveStatsEntry
	36, // 24: pb.PetDetailInfo.Attributes:type_name -> pb.PetDetailInfo.AttributesEntry
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_commonMessage_proto_init() }
func file_commonMessage_proto_init() {
	if File_commonMessage_proto != nil {
		return
	}
	file_messageEnum_proto_init()
	file_heroMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonMessage_proto_rawDesc), len(file_commonMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonMessage_proto_goTypes,
		DependencyIndexes: file_commonMessage_proto_depIdxs,
		MessageInfos:      file_commonMessage_proto_msgTypes,
	}.Build()
	File_commonMessage_proto = out.File
	file_commonMessage_proto_goTypes = nil
	file_commonMessage_proto_depIdxs = nil
}
