// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: equipmentMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装备基础信息
type EquipmentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"` // 装备唯一ID，全局唯一标识
	EquipmentId    int32                  `protobuf:"varint,2,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`       // 装备模板ID，对应配置表中的ID
	HeroOwnId      int64                  `protobuf:"varint,3,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`           // 穿戴的英雄唯一ID，0表示在仓库中
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                   // 装备等级，固定不可升级
	SlotType       int32                  `protobuf:"varint,5,opt,name=slotType,proto3" json:"slotType,omitempty"`             // 装备部位类型：1-武器，2-防具
	SlotIndex      int32                  `protobuf:"varint,6,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`           // 装备槽位索引：武器(0)，防具(1-5)
	StarLevel      int32                  `protobuf:"varint,7,opt,name=starLevel,proto3" json:"starLevel,omitempty"`           // 装备星级，预留字段
	SetId          int32                  `protobuf:"varint,8,opt,name=setId,proto3" json:"setId,omitempty"`                   // 套装ID，0表示不属于任何套装
	IsLocked       bool                   `protobuf:"varint,9,opt,name=isLocked,proto3" json:"isLocked,omitempty"`             // 是否锁定，锁定后无法分解
	Power          int64                  `protobuf:"varint,10,opt,name=power,proto3" json:"power,omitempty"`                  // 战力
	StrongLevel    int32                  `protobuf:"varint,11,opt,name=strongLevel,proto3" json:"strongLevel,omitempty"`      // 强化等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentInfo) Reset() {
	*x = EquipmentInfo{}
	mi := &file_equipmentMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentInfo) ProtoMessage() {}

func (x *EquipmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentInfo.ProtoReflect.Descriptor instead.
func (*EquipmentInfo) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{0}
}

func (x *EquipmentInfo) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentInfo) GetEquipmentId() int32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *EquipmentInfo) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *EquipmentInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentInfo) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

func (x *EquipmentInfo) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *EquipmentInfo) GetStarLevel() int32 {
	if x != nil {
		return x.StarLevel
	}
	return 0
}

func (x *EquipmentInfo) GetSetId() int32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *EquipmentInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *EquipmentInfo) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *EquipmentInfo) GetStrongLevel() int32 {
	if x != nil {
		return x.StrongLevel
	}
	return 0
}

// 装备词条信息
type EquipmentAffixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffixId       int32                  `protobuf:"varint,1,opt,name=affixId,proto3" json:"affixId,omitempty"`     // 词条ID
	StatType      int32                  `protobuf:"varint,2,opt,name=statType,proto3" json:"statType,omitempty"`   // 属性类型
	StatValue     int32                  `protobuf:"varint,3,opt,name=statValue,proto3" json:"statValue,omitempty"` // 属性数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentAffixInfo) Reset() {
	*x = EquipmentAffixInfo{}
	mi := &file_equipmentMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentAffixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentAffixInfo) ProtoMessage() {}

func (x *EquipmentAffixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentAffixInfo.ProtoReflect.Descriptor instead.
func (*EquipmentAffixInfo) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{1}
}

func (x *EquipmentAffixInfo) GetAffixId() int32 {
	if x != nil {
		return x.AffixId
	}
	return 0
}

func (x *EquipmentAffixInfo) GetStatType() int32 {
	if x != nil {
		return x.StatType
	}
	return 0
}

func (x *EquipmentAffixInfo) GetStatValue() int32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

// 装备技能词条信息
type EquipmentSkillAffixInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillAffixId  int32                  `protobuf:"varint,1,opt,name=skillAffixId,proto3" json:"skillAffixId,omitempty"` // 技能词条ID
	SkillId       int32                  `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`           // 技能ID
	SkillLevel    int32                  `protobuf:"varint,3,opt,name=skillLevel,proto3" json:"skillLevel,omitempty"`     // 技能等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentSkillAffixInfo) Reset() {
	*x = EquipmentSkillAffixInfo{}
	mi := &file_equipmentMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSkillAffixInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSkillAffixInfo) ProtoMessage() {}

func (x *EquipmentSkillAffixInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSkillAffixInfo.ProtoReflect.Descriptor instead.
func (*EquipmentSkillAffixInfo) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{2}
}

func (x *EquipmentSkillAffixInfo) GetSkillAffixId() int32 {
	if x != nil {
		return x.SkillAffixId
	}
	return 0
}

func (x *EquipmentSkillAffixInfo) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *EquipmentSkillAffixInfo) GetSkillLevel() int32 {
	if x != nil {
		return x.SkillLevel
	}
	return 0
}

// 套装信息
type EquipmentSetInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SetId            int32                  `protobuf:"varint,1,opt,name=setId,proto3" json:"setId,omitempty"`                                                                                        // 套装ID
	ActivePieceCount int32                  `protobuf:"varint,2,opt,name=activePieceCount,proto3" json:"activePieceCount,omitempty"`                                                                  // 当前激活件数
	PieceCount       int32                  `protobuf:"varint,3,opt,name=pieceCount,proto3" json:"pieceCount,omitempty"`                                                                              // 总件数
	ActiveStats      map[int32]int32        `protobuf:"bytes,4,rep,name=activeStats,proto3" json:"activeStats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 激活属性
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EquipmentSetInfo) Reset() {
	*x = EquipmentSetInfo{}
	mi := &file_equipmentMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSetInfo) ProtoMessage() {}

func (x *EquipmentSetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSetInfo.ProtoReflect.Descriptor instead.
func (*EquipmentSetInfo) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{3}
}

func (x *EquipmentSetInfo) GetSetId() int32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *EquipmentSetInfo) GetActivePieceCount() int32 {
	if x != nil {
		return x.ActivePieceCount
	}
	return 0
}

func (x *EquipmentSetInfo) GetPieceCount() int32 {
	if x != nil {
		return x.PieceCount
	}
	return 0
}

func (x *EquipmentSetInfo) GetActiveStats() map[int32]int32 {
	if x != nil {
		return x.ActiveStats
	}
	return nil
}

// 装备详情信息
type EquipmentDetailInfo struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	EquipmentOwnId int64                      `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`                                                                   // 装备唯一ID
	EquipmentId    int32                      `protobuf:"varint,2,opt,name=equipmentId,proto3" json:"equipmentId,omitempty"`                                                                         // 装备模板ID
	HeroOwnId      int64                      `protobuf:"varint,3,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`                                                                             // 穿戴的英雄唯一ID
	Level          int32                      `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                                                     // 装备等级
	SlotType       int32                      `protobuf:"varint,5,opt,name=slotType,proto3" json:"slotType,omitempty"`                                                                               // 装备部位类型
	SlotIndex      int32                      `protobuf:"varint,6,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`                                                                             // 装备槽位索引
	StarLevel      int32                      `protobuf:"varint,7,opt,name=starLevel,proto3" json:"starLevel,omitempty"`                                                                             // 装备星级
	SetId          int32                      `protobuf:"varint,8,opt,name=setId,proto3" json:"setId,omitempty"`                                                                                     // 套装ID
	IsLocked       bool                       `protobuf:"varint,9,opt,name=isLocked,proto3" json:"isLocked,omitempty"`                                                                               // 是否锁定
	ForgeLevel     int32                      `protobuf:"varint,10,opt,name=forgeLevel,proto3" json:"forgeLevel,omitempty"`                                                                          // 锻造等级，预留字段
	BaseStats      map[int32]int32            `protobuf:"bytes,11,rep,name=baseStats,proto3" json:"baseStats,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 基础属性
	AttributeAffix []*EquipmentAffixInfo      `protobuf:"bytes,12,rep,name=attributeAffix,proto3" json:"attributeAffix,omitempty"`                                                                   // 属性词条
	SkillAffix     []*EquipmentSkillAffixInfo `protobuf:"bytes,13,rep,name=skillAffix,proto3" json:"skillAffix,omitempty"`                                                                           // 技能词条
	SetInfo        *EquipmentSetInfo          `protobuf:"bytes,14,opt,name=setInfo,proto3" json:"setInfo,omitempty"`                                                                                 // 套装信息
	Power          int64                      `protobuf:"varint,15,opt,name=power,proto3" json:"power,omitempty"`                                                                                    // 战力
	StrongLevel    int32                      `protobuf:"varint,16,opt,name=strongLevel,proto3" json:"strongLevel,omitempty"`                                                                        // 强化等级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentDetailInfo) Reset() {
	*x = EquipmentDetailInfo{}
	mi := &file_equipmentMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDetailInfo) ProtoMessage() {}

func (x *EquipmentDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDetailInfo.ProtoReflect.Descriptor instead.
func (*EquipmentDetailInfo) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{4}
}

func (x *EquipmentDetailInfo) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetEquipmentId() int32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSlotType() int32 {
	if x != nil {
		return x.SlotType
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *EquipmentDetailInfo) GetStarLevel() int32 {
	if x != nil {
		return x.StarLevel
	}
	return 0
}

func (x *EquipmentDetailInfo) GetSetId() int32 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *EquipmentDetailInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *EquipmentDetailInfo) GetForgeLevel() int32 {
	if x != nil {
		return x.ForgeLevel
	}
	return 0
}

func (x *EquipmentDetailInfo) GetBaseStats() map[int32]int32 {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *EquipmentDetailInfo) GetAttributeAffix() []*EquipmentAffixInfo {
	if x != nil {
		return x.AttributeAffix
	}
	return nil
}

func (x *EquipmentDetailInfo) GetSkillAffix() []*EquipmentSkillAffixInfo {
	if x != nil {
		return x.SkillAffix
	}
	return nil
}

func (x *EquipmentDetailInfo) GetSetInfo() *EquipmentSetInfo {
	if x != nil {
		return x.SetInfo
	}
	return nil
}

func (x *EquipmentDetailInfo) GetPower() int64 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *EquipmentDetailInfo) GetStrongLevel() int32 {
	if x != nil {
		return x.StrongLevel
	}
	return 0
}

// 获取装备列表请求
type EquipmentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentListReq) Reset() {
	*x = EquipmentListReq{}
	mi := &file_equipmentMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentListReq) ProtoMessage() {}

func (x *EquipmentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentListReq.ProtoReflect.Descriptor instead.
func (*EquipmentListReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{5}
}

// 获取装备列表响应
type EquipmentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	Equipments    []*EquipmentInfo       `protobuf:"bytes,2,rep,name=equipments,proto3" json:"equipments,omitempty"`                   // 装备列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentListResp) Reset() {
	*x = EquipmentListResp{}
	mi := &file_equipmentMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentListResp) ProtoMessage() {}

func (x *EquipmentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentListResp.ProtoReflect.Descriptor instead.
func (*EquipmentListResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{6}
}

func (x *EquipmentListResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentListResp) GetEquipments() []*EquipmentInfo {
	if x != nil {
		return x.Equipments
	}
	return nil
}

// 获取装备详情请求
type EquipmentDetailReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"` // 要查询的装备唯一ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentDetailReq) Reset() {
	*x = EquipmentDetailReq{}
	mi := &file_equipmentMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDetailReq) ProtoMessage() {}

func (x *EquipmentDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDetailReq.ProtoReflect.Descriptor instead.
func (*EquipmentDetailReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{7}
}

func (x *EquipmentDetailReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

// 获取装备详情响应
type EquipmentDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	Detail        *EquipmentDetailInfo   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`                           // 装备详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentDetailResp) Reset() {
	*x = EquipmentDetailResp{}
	mi := &file_equipmentMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDetailResp) ProtoMessage() {}

func (x *EquipmentDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDetailResp.ProtoReflect.Descriptor instead.
func (*EquipmentDetailResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{8}
}

func (x *EquipmentDetailResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentDetailResp) GetDetail() *EquipmentDetailInfo {
	if x != nil {
		return x.Detail
	}
	return nil
}

// 穿戴装备请求
type EquipmentEquipReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"` // 要穿戴的装备ID
	HeroOwnId      int64                  `protobuf:"varint,2,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`           // 英雄ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentEquipReq) Reset() {
	*x = EquipmentEquipReq{}
	mi := &file_equipmentMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentEquipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentEquipReq) ProtoMessage() {}

func (x *EquipmentEquipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentEquipReq.ProtoReflect.Descriptor instead.
func (*EquipmentEquipReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{9}
}

func (x *EquipmentEquipReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentEquipReq) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

// 穿戴装备响应
type EquipmentEquipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                    // 是否成功（保留字段，兼容旧客户端）
	HeroInfo      *HeroBagInfo           `protobuf:"bytes,3,opt,name=heroInfo,proto3" json:"heroInfo,omitempty"`                       // 英雄信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentEquipResp) Reset() {
	*x = EquipmentEquipResp{}
	mi := &file_equipmentMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentEquipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentEquipResp) ProtoMessage() {}

func (x *EquipmentEquipResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentEquipResp.ProtoReflect.Descriptor instead.
func (*EquipmentEquipResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{10}
}

func (x *EquipmentEquipResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentEquipResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *EquipmentEquipResp) GetHeroInfo() *HeroBagInfo {
	if x != nil {
		return x.HeroInfo
	}
	return nil
}

// 卸下装备请求
type EquipmentUnequipReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentUnequipReq) Reset() {
	*x = EquipmentUnequipReq{}
	mi := &file_equipmentMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentUnequipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentUnequipReq) ProtoMessage() {}

func (x *EquipmentUnequipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentUnequipReq.ProtoReflect.Descriptor instead.
func (*EquipmentUnequipReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{11}
}

func (x *EquipmentUnequipReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

// 卸下装备响应
type EquipmentUnequipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                    // 是否成功（保留字段，兼容旧客户端）
	HeroInfo      *HeroBagInfo           `protobuf:"bytes,3,opt,name=heroInfo,proto3" json:"heroInfo,omitempty"`                       // 英雄信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentUnequipResp) Reset() {
	*x = EquipmentUnequipResp{}
	mi := &file_equipmentMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentUnequipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentUnequipResp) ProtoMessage() {}

func (x *EquipmentUnequipResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentUnequipResp.ProtoReflect.Descriptor instead.
func (*EquipmentUnequipResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{12}
}

func (x *EquipmentUnequipResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentUnequipResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *EquipmentUnequipResp) GetHeroInfo() *HeroBagInfo {
	if x != nil {
		return x.HeroInfo
	}
	return nil
}

// 替换装备请求
type EquipmentSwapReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`
	HeroOwnId      int64                  `protobuf:"varint,2,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentSwapReq) Reset() {
	*x = EquipmentSwapReq{}
	mi := &file_equipmentMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSwapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSwapReq) ProtoMessage() {}

func (x *EquipmentSwapReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSwapReq.ProtoReflect.Descriptor instead.
func (*EquipmentSwapReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{13}
}

func (x *EquipmentSwapReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentSwapReq) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

// 替换装备响应
type EquipmentSwapResp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode              ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"`        // 错误码
	IsSuccess              bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                           // 是否成功（保留字段，兼容旧客户端）
	ReplacedEquipmentOwnId int64                  `protobuf:"varint,3,opt,name=replacedEquipmentOwnId,proto3" json:"replacedEquipmentOwnId,omitempty"` // 被替换的装备唯一ID
	HeroInfo               *HeroBagInfo           `protobuf:"bytes,4,opt,name=heroInfo,proto3" json:"heroInfo,omitempty"`                              // 英雄信息
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EquipmentSwapResp) Reset() {
	*x = EquipmentSwapResp{}
	mi := &file_equipmentMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentSwapResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentSwapResp) ProtoMessage() {}

func (x *EquipmentSwapResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentSwapResp.ProtoReflect.Descriptor instead.
func (*EquipmentSwapResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{14}
}

func (x *EquipmentSwapResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentSwapResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *EquipmentSwapResp) GetReplacedEquipmentOwnId() int64 {
	if x != nil {
		return x.ReplacedEquipmentOwnId
	}
	return 0
}

func (x *EquipmentSwapResp) GetHeroInfo() *HeroBagInfo {
	if x != nil {
		return x.HeroInfo
	}
	return nil
}

// 一键穿戴请求
type EquipmentQuickEquipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroOwnIds    []int64                `protobuf:"varint,1,rep,packed,name=heroOwnIds,proto3" json:"heroOwnIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentQuickEquipReq) Reset() {
	*x = EquipmentQuickEquipReq{}
	mi := &file_equipmentMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentQuickEquipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentQuickEquipReq) ProtoMessage() {}

func (x *EquipmentQuickEquipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentQuickEquipReq.ProtoReflect.Descriptor instead.
func (*EquipmentQuickEquipReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{15}
}

func (x *EquipmentQuickEquipReq) GetHeroOwnIds() []int64 {
	if x != nil {
		return x.HeroOwnIds
	}
	return nil
}

// 一键穿戴响应
type EquipmentQuickEquipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                    // 是否成功（保留字段，兼容旧客户端）
	Equipments    []*EquipmentInfo       `protobuf:"bytes,3,rep,name=equipments,proto3" json:"equipments,omitempty"`                   // 穿戴的装备列表
	HeroInfos     []*HeroBagInfo         `protobuf:"bytes,4,rep,name=heroInfos,proto3" json:"heroInfos,omitempty"`                     // 受影响的英雄信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentQuickEquipResp) Reset() {
	*x = EquipmentQuickEquipResp{}
	mi := &file_equipmentMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentQuickEquipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentQuickEquipResp) ProtoMessage() {}

func (x *EquipmentQuickEquipResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentQuickEquipResp.ProtoReflect.Descriptor instead.
func (*EquipmentQuickEquipResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{16}
}

func (x *EquipmentQuickEquipResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentQuickEquipResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *EquipmentQuickEquipResp) GetEquipments() []*EquipmentInfo {
	if x != nil {
		return x.Equipments
	}
	return nil
}

func (x *EquipmentQuickEquipResp) GetHeroInfos() []*HeroBagInfo {
	if x != nil {
		return x.HeroInfos
	}
	return nil
}

// 一键卸下请求
type EquipmentQuickUnequipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroOwnIds    []int64                `protobuf:"varint,1,rep,packed,name=heroOwnIds,proto3" json:"heroOwnIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentQuickUnequipReq) Reset() {
	*x = EquipmentQuickUnequipReq{}
	mi := &file_equipmentMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentQuickUnequipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentQuickUnequipReq) ProtoMessage() {}

func (x *EquipmentQuickUnequipReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentQuickUnequipReq.ProtoReflect.Descriptor instead.
func (*EquipmentQuickUnequipReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{17}
}

func (x *EquipmentQuickUnequipReq) GetHeroOwnIds() []int64 {
	if x != nil {
		return x.HeroOwnIds
	}
	return nil
}

// 一键卸下响应
type EquipmentQuickUnequipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                    // 是否成功（保留字段，兼容旧客户端）
	HeroInfos     []*HeroBagInfo         `protobuf:"bytes,3,rep,name=heroInfos,proto3" json:"heroInfos,omitempty"`                     // 受影响的英雄信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentQuickUnequipResp) Reset() {
	*x = EquipmentQuickUnequipResp{}
	mi := &file_equipmentMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentQuickUnequipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentQuickUnequipResp) ProtoMessage() {}

func (x *EquipmentQuickUnequipResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentQuickUnequipResp.ProtoReflect.Descriptor instead.
func (*EquipmentQuickUnequipResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{18}
}

func (x *EquipmentQuickUnequipResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentQuickUnequipResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *EquipmentQuickUnequipResp) GetHeroInfos() []*HeroBagInfo {
	if x != nil {
		return x.HeroInfos
	}
	return nil
}

// 锁定/解锁装备请求
type EquipmentLockReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`
	Lock           bool                   `protobuf:"varint,2,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentLockReq) Reset() {
	*x = EquipmentLockReq{}
	mi := &file_equipmentMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentLockReq) ProtoMessage() {}

func (x *EquipmentLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentLockReq.ProtoReflect.Descriptor instead.
func (*EquipmentLockReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{19}
}

func (x *EquipmentLockReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentLockReq) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

// 锁定/解锁装备响应
type EquipmentLockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	IsSuccess     bool                   `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`                    // 是否成功（保留字段，兼容旧客户端）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentLockResp) Reset() {
	*x = EquipmentLockResp{}
	mi := &file_equipmentMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentLockResp) ProtoMessage() {}

func (x *EquipmentLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentLockResp.ProtoReflect.Descriptor instead.
func (*EquipmentLockResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{20}
}

func (x *EquipmentLockResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentLockResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

// 分解装备请求
type EquipmentDecomposeReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnIds []int64                `protobuf:"varint,1,rep,packed,name=equipmentOwnIds,proto3" json:"equipmentOwnIds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquipmentDecomposeReq) Reset() {
	*x = EquipmentDecomposeReq{}
	mi := &file_equipmentMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDecomposeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDecomposeReq) ProtoMessage() {}

func (x *EquipmentDecomposeReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDecomposeReq.ProtoReflect.Descriptor instead.
func (*EquipmentDecomposeReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{21}
}

func (x *EquipmentDecomposeReq) GetEquipmentOwnIds() []int64 {
	if x != nil {
		return x.EquipmentOwnIds
	}
	return nil
}

// 分解装备响应
type EquipmentDecomposeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ERROR_CODE             `protobuf:"varint,1,opt,name=errorCode,proto3,enum=pb.ERROR_CODE" json:"errorCode,omitempty"` // 错误码
	DropId        []int32                `protobuf:"varint,2,rep,packed,name=dropId,proto3" json:"dropId,omitempty"`                   // 掉落物品ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentDecomposeResp) Reset() {
	*x = EquipmentDecomposeResp{}
	mi := &file_equipmentMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentDecomposeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDecomposeResp) ProtoMessage() {}

func (x *EquipmentDecomposeResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDecomposeResp.ProtoReflect.Descriptor instead.
func (*EquipmentDecomposeResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{22}
}

func (x *EquipmentDecomposeResp) GetErrorCode() ERROR_CODE {
	if x != nil {
		return x.ErrorCode
	}
	return ERROR_CODE_SUCCESS
}

func (x *EquipmentDecomposeResp) GetDropId() []int32 {
	if x != nil {
		return x.DropId
	}
	return nil
}

type PushEquipmentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*EquipmentDetailInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushEquipmentDetail) Reset() {
	*x = PushEquipmentDetail{}
	mi := &file_equipmentMessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushEquipmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEquipmentDetail) ProtoMessage() {}

func (x *PushEquipmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEquipmentDetail.ProtoReflect.Descriptor instead.
func (*PushEquipmentDetail) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{23}
}

func (x *PushEquipmentDetail) GetInfo() []*EquipmentDetailInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type EquipmentForgeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperId       int32                  `protobuf:"varint,1,opt,name=paperId,proto3" json:"paperId,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentForgeReq) Reset() {
	*x = EquipmentForgeReq{}
	mi := &file_equipmentMessage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentForgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentForgeReq) ProtoMessage() {}

func (x *EquipmentForgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentForgeReq.ProtoReflect.Descriptor instead.
func (*EquipmentForgeReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{24}
}

func (x *EquipmentForgeReq) GetPaperId() int32 {
	if x != nil {
		return x.PaperId
	}
	return 0
}

func (x *EquipmentForgeReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EquipmentForgeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentForgeResp) Reset() {
	*x = EquipmentForgeResp{}
	mi := &file_equipmentMessage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentForgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentForgeResp) ProtoMessage() {}

func (x *EquipmentForgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentForgeResp.ProtoReflect.Descriptor instead.
func (*EquipmentForgeResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{25}
}

type EquipmentStrongReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`
	IsUseStone     bool                   `protobuf:"varint,2,opt,name=isUseStone,proto3" json:"isUseStone,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentStrongReq) Reset() {
	*x = EquipmentStrongReq{}
	mi := &file_equipmentMessage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentStrongReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentStrongReq) ProtoMessage() {}

func (x *EquipmentStrongReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentStrongReq.ProtoReflect.Descriptor instead.
func (*EquipmentStrongReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{26}
}

func (x *EquipmentStrongReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

func (x *EquipmentStrongReq) GetIsUseStone() bool {
	if x != nil {
		return x.IsUseStone
	}
	return false
}

type EquipmentStrongResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EquipmentDetail *EquipmentDetailInfo   `protobuf:"bytes,1,opt,name=equipmentDetail,proto3" json:"equipmentDetail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquipmentStrongResp) Reset() {
	*x = EquipmentStrongResp{}
	mi := &file_equipmentMessage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentStrongResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentStrongResp) ProtoMessage() {}

func (x *EquipmentStrongResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentStrongResp.ProtoReflect.Descriptor instead.
func (*EquipmentStrongResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{27}
}

func (x *EquipmentStrongResp) GetEquipmentDetail() *EquipmentDetailInfo {
	if x != nil {
		return x.EquipmentDetail
	}
	return nil
}

type EquipmentRebirthReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EquipmentOwnId int64                  `protobuf:"varint,1,opt,name=equipmentOwnId,proto3" json:"equipmentOwnId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EquipmentRebirthReq) Reset() {
	*x = EquipmentRebirthReq{}
	mi := &file_equipmentMessage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRebirthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRebirthReq) ProtoMessage() {}

func (x *EquipmentRebirthReq) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRebirthReq.ProtoReflect.Descriptor instead.
func (*EquipmentRebirthReq) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{28}
}

func (x *EquipmentRebirthReq) GetEquipmentOwnId() int64 {
	if x != nil {
		return x.EquipmentOwnId
	}
	return 0
}

type EquipmentRebirthResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EquipmentDetail *EquipmentDetailInfo   `protobuf:"bytes,1,opt,name=equipmentDetail,proto3" json:"equipmentDetail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EquipmentRebirthResp) Reset() {
	*x = EquipmentRebirthResp{}
	mi := &file_equipmentMessage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentRebirthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentRebirthResp) ProtoMessage() {}

func (x *EquipmentRebirthResp) ProtoReflect() protoreflect.Message {
	mi := &file_equipmentMessage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentRebirthResp.ProtoReflect.Descriptor instead.
func (*EquipmentRebirthResp) Descriptor() ([]byte, []int) {
	return file_equipmentMessage_proto_rawDescGZIP(), []int{29}
}

func (x *EquipmentRebirthResp) GetEquipmentDetail() *EquipmentDetailInfo {
	if x != nil {
		return x.EquipmentDetail
	}
	return nil
}

var File_equipmentMessage_proto protoreflect.FileDescriptor

const file_equipmentMessage_proto_rawDesc = "" +
	"\n" +
	"\x16equipmentMessage.proto\x12\x02pb\x1a\x11messageEnum.proto\x1a\x11heroMessage.proto\"\xcf\x02\n" +
	"\rEquipmentInfo\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12 \n" +
	"\vequipmentId\x18\x02 \x01(\x05R\vequipmentId\x12\x1c\n" +
	"\theroOwnId\x18\x03 \x01(\x03R\theroOwnId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1a\n" +
	"\bslotType\x18\x05 \x01(\x05R\bslotType\x12\x1c\n" +
	"\tslotIndex\x18\x06 \x01(\x05R\tslotIndex\x12\x1c\n" +
	"\tstarLevel\x18\a \x01(\x05R\tstarLevel\x12\x14\n" +
	"\x05setId\x18\b \x01(\x05R\x05setId\x12\x1a\n" +
	"\bisLocked\x18\t \x01(\bR\bisLocked\x12\x14\n" +
	"\x05power\x18\n" +
	" \x01(\x03R\x05power\x12 \n" +
	"\vstrongLevel\x18\v \x01(\x05R\vstrongLevel\"h\n" +
	"\x12EquipmentAffixInfo\x12\x18\n" +
	"\aaffixId\x18\x01 \x01(\x05R\aaffixId\x12\x1a\n" +
	"\bstatType\x18\x02 \x01(\x05R\bstatType\x12\x1c\n" +
	"\tstatValue\x18\x03 \x01(\x05R\tstatValue\"w\n" +
	"\x17EquipmentSkillAffixInfo\x12\"\n" +
	"\fskillAffixId\x18\x01 \x01(\x05R\fskillAffixId\x12\x18\n" +
	"\askillId\x18\x02 \x01(\x05R\askillId\x12\x1e\n" +
	"\n" +
	"skillLevel\x18\x03 \x01(\x05R\n" +
	"skillLevel\"\xfd\x01\n" +
	"\x10EquipmentSetInfo\x12\x14\n" +
	"\x05setId\x18\x01 \x01(\x05R\x05setId\x12*\n" +
	"\x10activePieceCount\x18\x02 \x01(\x05R\x10activePieceCount\x12\x1e\n" +
	"\n" +
	"pieceCount\x18\x03 \x01(\x05R\n" +
	"pieceCount\x12G\n" +
	"\vactiveStats\x18\x04 \x03(\v2%.pb.EquipmentSetInfo.ActiveStatsEntryR\vactiveStats\x1a>\n" +
	"\x10ActiveStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa6\x05\n" +
	"\x13EquipmentDetailInfo\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12 \n" +
	"\vequipmentId\x18\x02 \x01(\x05R\vequipmentId\x12\x1c\n" +
	"\theroOwnId\x18\x03 \x01(\x03R\theroOwnId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1a\n" +
	"\bslotType\x18\x05 \x01(\x05R\bslotType\x12\x1c\n" +
	"\tslotIndex\x18\x06 \x01(\x05R\tslotIndex\x12\x1c\n" +
	"\tstarLevel\x18\a \x01(\x05R\tstarLevel\x12\x14\n" +
	"\x05setId\x18\b \x01(\x05R\x05setId\x12\x1a\n" +
	"\bisLocked\x18\t \x01(\bR\bisLocked\x12\x1e\n" +
	"\n" +
	"forgeLevel\x18\n" +
	" \x01(\x05R\n" +
	"forgeLevel\x12D\n" +
	"\tbaseStats\x18\v \x03(\v2&.pb.EquipmentDetailInfo.BaseStatsEntryR\tbaseStats\x12>\n" +
	"\x0eattributeAffix\x18\f \x03(\v2\x16.pb.EquipmentAffixInfoR\x0eattributeAffix\x12;\n" +
	"\n" +
	"skillAffix\x18\r \x03(\v2\x1b.pb.EquipmentSkillAffixInfoR\n" +
	"skillAffix\x12.\n" +
	"\asetInfo\x18\x0e \x01(\v2\x14.pb.EquipmentSetInfoR\asetInfo\x12\x14\n" +
	"\x05power\x18\x0f \x01(\x03R\x05power\x12 \n" +
	"\vstrongLevel\x18\x10 \x01(\x05R\vstrongLevel\x1a<\n" +
	"\x0eBaseStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x12\n" +
	"\x10EquipmentListReq\"t\n" +
	"\x11EquipmentListResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x121\n" +
	"\n" +
	"equipments\x18\x02 \x03(\v2\x11.pb.EquipmentInfoR\n" +
	"equipments\"<\n" +
	"\x12EquipmentDetailReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\"t\n" +
	"\x13EquipmentDetailResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12/\n" +
	"\x06detail\x18\x02 \x01(\v2\x17.pb.EquipmentDetailInfoR\x06detail\"Y\n" +
	"\x11EquipmentEquipReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12\x1c\n" +
	"\theroOwnId\x18\x02 \x01(\x03R\theroOwnId\"\x8d\x01\n" +
	"\x12EquipmentEquipResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\x12+\n" +
	"\bheroInfo\x18\x03 \x01(\v2\x0f.pb.HeroBagInfoR\bheroInfo\"=\n" +
	"\x13EquipmentUnequipReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\"\x8f\x01\n" +
	"\x14EquipmentUnequipResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\x12+\n" +
	"\bheroInfo\x18\x03 \x01(\v2\x0f.pb.HeroBagInfoR\bheroInfo\"X\n" +
	"\x10EquipmentSwapReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12\x1c\n" +
	"\theroOwnId\x18\x02 \x01(\x03R\theroOwnId\"\xc4\x01\n" +
	"\x11EquipmentSwapResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\x126\n" +
	"\x16replacedEquipmentOwnId\x18\x03 \x01(\x03R\x16replacedEquipmentOwnId\x12+\n" +
	"\bheroInfo\x18\x04 \x01(\v2\x0f.pb.HeroBagInfoR\bheroInfo\"8\n" +
	"\x16EquipmentQuickEquipReq\x12\x1e\n" +
	"\n" +
	"heroOwnIds\x18\x01 \x03(\x03R\n" +
	"heroOwnIds\"\xc7\x01\n" +
	"\x17EquipmentQuickEquipResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\x121\n" +
	"\n" +
	"equipments\x18\x03 \x03(\v2\x11.pb.EquipmentInfoR\n" +
	"equipments\x12-\n" +
	"\theroInfos\x18\x04 \x03(\v2\x0f.pb.HeroBagInfoR\theroInfos\":\n" +
	"\x18EquipmentQuickUnequipReq\x12\x1e\n" +
	"\n" +
	"heroOwnIds\x18\x01 \x03(\x03R\n" +
	"heroOwnIds\"\x96\x01\n" +
	"\x19EquipmentQuickUnequipResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\x12-\n" +
	"\theroInfos\x18\x03 \x03(\v2\x0f.pb.HeroBagInfoR\theroInfos\"N\n" +
	"\x10EquipmentLockReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12\x12\n" +
	"\x04lock\x18\x02 \x01(\bR\x04lock\"_\n" +
	"\x11EquipmentLockResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x1c\n" +
	"\tisSuccess\x18\x02 \x01(\bR\tisSuccess\"A\n" +
	"\x15EquipmentDecomposeReq\x12(\n" +
	"\x0fequipmentOwnIds\x18\x01 \x03(\x03R\x0fequipmentOwnIds\"^\n" +
	"\x16EquipmentDecomposeResp\x12,\n" +
	"\terrorCode\x18\x01 \x01(\x0e2\x0e.pb.ERROR_CODER\terrorCode\x12\x16\n" +
	"\x06dropId\x18\x02 \x03(\x05R\x06dropId\"B\n" +
	"\x13PushEquipmentDetail\x12+\n" +
	"\x04info\x18\x01 \x03(\v2\x17.pb.EquipmentDetailInfoR\x04info\"C\n" +
	"\x11EquipmentForgeReq\x12\x18\n" +
	"\apaperId\x18\x01 \x01(\x05R\apaperId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x14\n" +
	"\x12EquipmentForgeResp\"\\\n" +
	"\x12EquipmentStrongReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\x12\x1e\n" +
	"\n" +
	"isUseStone\x18\x02 \x01(\bR\n" +
	"isUseStone\"X\n" +
	"\x13EquipmentStrongResp\x12A\n" +
	"\x0fequipmentDetail\x18\x01 \x01(\v2\x17.pb.EquipmentDetailInfoR\x0fequipmentDetail\"=\n" +
	"\x13EquipmentRebirthReq\x12&\n" +
	"\x0eequipmentOwnId\x18\x01 \x01(\x03R\x0eequipmentOwnId\"Y\n" +
	"\x14EquipmentRebirthResp\x12A\n" +
	"\x0fequipmentDetail\x18\x01 \x01(\v2\x17.pb.EquipmentDetailInfoR\x0fequipmentDetailB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_equipmentMessage_proto_rawDescOnce sync.Once
	file_equipmentMessage_proto_rawDescData []byte
)

func file_equipmentMessage_proto_rawDescGZIP() []byte {
	file_equipmentMessage_proto_rawDescOnce.Do(func() {
		file_equipmentMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_equipmentMessage_proto_rawDesc), len(file_equipmentMessage_proto_rawDesc)))
	})
	return file_equipmentMessage_proto_rawDescData
}

var file_equipmentMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_equipmentMessage_proto_goTypes = []any{
	(*EquipmentInfo)(nil),             // 0: pb.EquipmentInfo
	(*EquipmentAffixInfo)(nil),        // 1: pb.EquipmentAffixInfo
	(*EquipmentSkillAffixInfo)(nil),   // 2: pb.EquipmentSkillAffixInfo
	(*EquipmentSetInfo)(nil),          // 3: pb.EquipmentSetInfo
	(*EquipmentDetailInfo)(nil),       // 4: pb.EquipmentDetailInfo
	(*EquipmentListReq)(nil),          // 5: pb.EquipmentListReq
	(*EquipmentListResp)(nil),         // 6: pb.EquipmentListResp
	(*EquipmentDetailReq)(nil),        // 7: pb.EquipmentDetailReq
	(*EquipmentDetailResp)(nil),       // 8: pb.EquipmentDetailResp
	(*EquipmentEquipReq)(nil),         // 9: pb.EquipmentEquipReq
	(*EquipmentEquipResp)(nil),        // 10: pb.EquipmentEquipResp
	(*EquipmentUnequipReq)(nil),       // 11: pb.EquipmentUnequipReq
	(*EquipmentUnequipResp)(nil),      // 12: pb.EquipmentUnequipResp
	(*EquipmentSwapReq)(nil),          // 13: pb.EquipmentSwapReq
	(*EquipmentSwapResp)(nil),         // 14: pb.EquipmentSwapResp
	(*EquipmentQuickEquipReq)(nil),    // 15: pb.EquipmentQuickEquipReq
	(*EquipmentQuickEquipResp)(nil),   // 16: pb.EquipmentQuickEquipResp
	(*EquipmentQuickUnequipReq)(nil),  // 17: pb.EquipmentQuickUnequipReq
	(*EquipmentQuickUnequipResp)(nil), // 18: pb.EquipmentQuickUnequipResp
	(*EquipmentLockReq)(nil),          // 19: pb.EquipmentLockReq
	(*EquipmentLockResp)(nil),         // 20: pb.EquipmentLockResp
	(*EquipmentDecomposeReq)(nil),     // 21: pb.EquipmentDecomposeReq
	(*EquipmentDecomposeResp)(nil),    // 22: pb.EquipmentDecomposeResp
	(*PushEquipmentDetail)(nil),       // 23: pb.PushEquipmentDetail
	(*EquipmentForgeReq)(nil),         // 24: pb.EquipmentForgeReq
	(*EquipmentForgeResp)(nil),        // 25: pb.EquipmentForgeResp
	(*EquipmentStrongReq)(nil),        // 26: pb.EquipmentStrongReq
	(*EquipmentStrongResp)(nil),       // 27: pb.EquipmentStrongResp
	(*EquipmentRebirthReq)(nil),       // 28: pb.EquipmentRebirthReq
	(*EquipmentRebirthResp)(nil),      // 29: pb.EquipmentRebirthResp
	nil,                               // 30: pb.EquipmentSetInfo.ActiveStatsEntry
	nil,                               // 31: pb.EquipmentDetailInfo.BaseStatsEntry
	(ERROR_CODE)(0),                   // 32: pb.ERROR_CODE
	(*HeroBagInfo)(nil),               // 33: pb.HeroBagInfo
}
var file_equipmentMessage_proto_depIdxs = []int32{
	30, // 0: pb.EquipmentSetInfo.activeStats:type_name -> pb.EquipmentSetInfo.ActiveStatsEntry
	31, // 1: pb.EquipmentDetailInfo.baseStats:type_name -> pb.EquipmentDetailInfo.BaseStatsEntry
	1,  // 2: pb.EquipmentDetailInfo.attributeAffix:type_name -> pb.EquipmentAffixInfo
	2,  // 3: pb.EquipmentDetailInfo.skillAffix:type_name -> pb.EquipmentSkillAffixInfo
	3,  // 4: pb.EquipmentDetailInfo.setInfo:type_name -> pb.EquipmentSetInfo
	32, // 5: pb.EquipmentListResp.errorCode:type_name -> pb.ERROR_CODE
	0,  // 6: pb.EquipmentListResp.equipments:type_name -> pb.EquipmentInfo
	32, // 7: pb.EquipmentDetailResp.errorCode:type_name -> pb.ERROR_CODE
	4,  // 8: pb.EquipmentDetailResp.detail:type_name -> pb.EquipmentDetailInfo
	32, // 9: pb.EquipmentEquipResp.errorCode:type_name -> pb.ERROR_CODE
	33, // 10: pb.EquipmentEquipResp.heroInfo:type_name -> pb.HeroBagInfo
	32, // 11: pb.EquipmentUnequipResp.errorCode:type_name -> pb.ERROR_CODE
	33, // 12: pb.EquipmentUnequipResp.heroInfo:type_name -> pb.HeroBagInfo
	32, // 13: pb.EquipmentSwapResp.errorCode:type_name -> pb.ERROR_CODE
	33, // 14: pb.EquipmentSwapResp.heroInfo:type_name -> pb.HeroBagInfo
	32, // 15: pb.EquipmentQuickEquipResp.errorCode:type_name -> pb.ERROR_CODE
	0,  // 16: pb.EquipmentQuickEquipResp.equipments:type_name -> pb.EquipmentInfo
	33, // 17: pb.EquipmentQuickEquipResp.heroInfos:type_name -> pb.HeroBagInfo
	32, // 18: pb.EquipmentQuickUnequipResp.errorCode:type_name -> pb.ERROR_CODE
	33, // 19: pb.EquipmentQuickUnequipResp.heroInfos:type_name -> pb.HeroBagInfo
	32, // 20: pb.EquipmentLockResp.errorCode:type_name -> pb.ERROR_CODE
	32, // 21: pb.EquipmentDecomposeResp.errorCode:type_name -> pb.ERROR_CODE
	4,  // 22: pb.PushEquipmentDetail.info:type_name -> pb.EquipmentDetailInfo
	4,  // 23: pb.EquipmentStrongResp.equipmentDetail:type_name -> pb.EquipmentDetailInfo
	4,  // 24: pb.EquipmentRebirthResp.equipmentDetail:type_name -> pb.EquipmentDetailInfo
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_equipmentMessage_proto_init() }
func file_equipmentMessage_proto_init() {
	if File_equipmentMessage_proto != nil {
		return
	}
	file_messageEnum_proto_init()
	file_heroMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_equipmentMessage_proto_rawDesc), len(file_equipmentMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_equipmentMessage_proto_goTypes,
		DependencyIndexes: file_equipmentMessage_proto_depIdxs,
		MessageInfos:      file_equipmentMessage_proto_msgTypes,
	}.Build()
	File_equipmentMessage_proto = out.File
	file_equipmentMessage_proto_goTypes = nil
	file_equipmentMessage_proto_depIdxs = nil
}
