// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: expeditionMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpeditionBattlefieldInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BattlefieldId    int32                  `protobuf:"varint,1,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"`       // 战场id
	BattlefieldLevel int32                  `protobuf:"varint,2,opt,name=battlefieldLevel,proto3" json:"battlefieldLevel,omitempty"` // 战场等级
	MonsterInfos     []*ExpeditionPointInfo `protobuf:"bytes,3,rep,name=monsterInfos,proto3" json:"monsterInfos,omitempty"`          // 怪物信息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpeditionBattlefieldInfo) Reset() {
	*x = ExpeditionBattlefieldInfo{}
	mi := &file_expeditionMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionBattlefieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionBattlefieldInfo) ProtoMessage() {}

func (x *ExpeditionBattlefieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionBattlefieldInfo.ProtoReflect.Descriptor instead.
func (*ExpeditionBattlefieldInfo) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ExpeditionBattlefieldInfo) GetBattlefieldId() int32 {
	if x != nil {
		return x.BattlefieldId
	}
	return 0
}

func (x *ExpeditionBattlefieldInfo) GetBattlefieldLevel() int32 {
	if x != nil {
		return x.BattlefieldLevel
	}
	return 0
}

func (x *ExpeditionBattlefieldInfo) GetMonsterInfos() []*ExpeditionPointInfo {
	if x != nil {
		return x.MonsterInfos
	}
	return nil
}

type ExpeditionPointInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PointId         int32                  `protobuf:"varint,1,opt,name=pointId,proto3" json:"pointId,omitempty"`                 // 点位id
	MonsterId       int32                  `protobuf:"varint,2,opt,name=monsterId,proto3" json:"monsterId,omitempty"`             // 怪物id
	NextRefreshTime int64                  `protobuf:"varint,3,opt,name=nextRefreshTime,proto3" json:"nextRefreshTime,omitempty"` // 下次刷新时间
	IsReward        int32                  `protobuf:"varint,4,opt,name=isReward,proto3" json:"isReward,omitempty"`               // 是否能领奖
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpeditionPointInfo) Reset() {
	*x = ExpeditionPointInfo{}
	mi := &file_expeditionMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionPointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionPointInfo) ProtoMessage() {}

func (x *ExpeditionPointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionPointInfo.ProtoReflect.Descriptor instead.
func (*ExpeditionPointInfo) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ExpeditionPointInfo) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *ExpeditionPointInfo) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *ExpeditionPointInfo) GetNextRefreshTime() int64 {
	if x != nil {
		return x.NextRefreshTime
	}
	return 0
}

func (x *ExpeditionPointInfo) GetIsReward() int32 {
	if x != nil {
		return x.IsReward
	}
	return 0
}

type ExpeditionSlotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slotId,proto3" json:"slotId,omitempty"`               // 槽位id
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`               // 状态（0:未开始 1:进行中）
	BattlefieldId int32                  `protobuf:"varint,3,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"` // 战场id
	PointId       int32                  `protobuf:"varint,4,opt,name=pointId,proto3" json:"pointId,omitempty"`             // 点位id
	OverTime      int64                  `protobuf:"varint,5,opt,name=overTime,proto3" json:"overTime,omitempty"`           // 结束时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionSlotInfo) Reset() {
	*x = ExpeditionSlotInfo{}
	mi := &file_expeditionMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionSlotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionSlotInfo) ProtoMessage() {}

func (x *ExpeditionSlotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionSlotInfo.ProtoReflect.Descriptor instead.
func (*ExpeditionSlotInfo) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ExpeditionSlotInfo) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ExpeditionSlotInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ExpeditionSlotInfo) GetBattlefieldId() int32 {
	if x != nil {
		return x.BattlefieldId
	}
	return 0
}

func (x *ExpeditionSlotInfo) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *ExpeditionSlotInfo) GetOverTime() int64 {
	if x != nil {
		return x.OverTime
	}
	return 0
}

// 地图信息请求
type ExpeditionInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionInfoReq) Reset() {
	*x = ExpeditionInfoReq{}
	mi := &file_expeditionMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionInfoReq) ProtoMessage() {}

func (x *ExpeditionInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionInfoReq.ProtoReflect.Descriptor instead.
func (*ExpeditionInfoReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{3}
}

type ExpeditionInfoResp struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	Battlefields               []*ExpeditionBattlefieldInfo `protobuf:"bytes,1,rep,name=battlefields,proto3" json:"battlefields,omitempty"`                              // 战场信息
	Slots                      []*ExpeditionSlotInfo        `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`                                            // 派遣槽位信息
	FreeClaimCount             int32                        `protobuf:"varint,3,opt,name=freeClaimCount,proto3" json:"freeClaimCount,omitempty"`                         // 免费已领取次数
	FreeCDTimeStamp            int64                        `protobuf:"varint,4,opt,name=freeCDTimeStamp,proto3" json:"freeCDTimeStamp,omitempty"`                       // 免费领取cd结束时间戳
	LastPowerRecoveryTimeStamp int64                        `protobuf:"varint,5,opt,name=LastPowerRecoveryTimeStamp,proto3" json:"LastPowerRecoveryTimeStamp,omitempty"` // 上一次体力恢复时间戳
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ExpeditionInfoResp) Reset() {
	*x = ExpeditionInfoResp{}
	mi := &file_expeditionMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionInfoResp) ProtoMessage() {}

func (x *ExpeditionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionInfoResp.ProtoReflect.Descriptor instead.
func (*ExpeditionInfoResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{4}
}

func (x *ExpeditionInfoResp) GetBattlefields() []*ExpeditionBattlefieldInfo {
	if x != nil {
		return x.Battlefields
	}
	return nil
}

func (x *ExpeditionInfoResp) GetSlots() []*ExpeditionSlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ExpeditionInfoResp) GetFreeClaimCount() int32 {
	if x != nil {
		return x.FreeClaimCount
	}
	return 0
}

func (x *ExpeditionInfoResp) GetFreeCDTimeStamp() int64 {
	if x != nil {
		return x.FreeCDTimeStamp
	}
	return 0
}

func (x *ExpeditionInfoResp) GetLastPowerRecoveryTimeStamp() int64 {
	if x != nil {
		return x.LastPowerRecoveryTimeStamp
	}
	return 0
}

// 开始派遣
type ExpeditionStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slotId,proto3" json:"slotId,omitempty"`               // 槽位id
	BattlefieldId int32                  `protobuf:"varint,2,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"` // 战场id
	PointId       int32                  `protobuf:"varint,3,opt,name=pointId,proto3" json:"pointId,omitempty"`             // 点位id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionStartReq) Reset() {
	*x = ExpeditionStartReq{}
	mi := &file_expeditionMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionStartReq) ProtoMessage() {}

func (x *ExpeditionStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionStartReq.ProtoReflect.Descriptor instead.
func (*ExpeditionStartReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{5}
}

func (x *ExpeditionStartReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ExpeditionStartReq) GetBattlefieldId() int32 {
	if x != nil {
		return x.BattlefieldId
	}
	return 0
}

func (x *ExpeditionStartReq) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

type ExpeditionStartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *ExpeditionSlotInfo    `protobuf:"bytes,1,opt,name=active,proto3" json:"active,omitempty"` // 激活的槽位信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionStartResp) Reset() {
	*x = ExpeditionStartResp{}
	mi := &file_expeditionMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionStartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionStartResp) ProtoMessage() {}

func (x *ExpeditionStartResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionStartResp.ProtoReflect.Descriptor instead.
func (*ExpeditionStartResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{6}
}

func (x *ExpeditionStartResp) GetActive() *ExpeditionSlotInfo {
	if x != nil {
		return x.Active
	}
	return nil
}

// 立刻完成
type ExpeditionFinishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slotId,proto3" json:"slotId,omitempty"` // 槽位id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionFinishReq) Reset() {
	*x = ExpeditionFinishReq{}
	mi := &file_expeditionMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionFinishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionFinishReq) ProtoMessage() {}

func (x *ExpeditionFinishReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionFinishReq.ProtoReflect.Descriptor instead.
func (*ExpeditionFinishReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{7}
}

func (x *ExpeditionFinishReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type ExpeditionFinishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *ExpeditionSlotInfo    `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`                 // 槽位信息
	MonsterInfos  *ExpeditionPointInfo   `protobuf:"bytes,3,opt,name=monsterInfos,proto3" json:"monsterInfos,omitempty"` // 怪物信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionFinishResp) Reset() {
	*x = ExpeditionFinishResp{}
	mi := &file_expeditionMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionFinishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionFinishResp) ProtoMessage() {}

func (x *ExpeditionFinishResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionFinishResp.ProtoReflect.Descriptor instead.
func (*ExpeditionFinishResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ExpeditionFinishResp) GetSlot() *ExpeditionSlotInfo {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *ExpeditionFinishResp) GetMonsterInfos() *ExpeditionPointInfo {
	if x != nil {
		return x.MonsterInfos
	}
	return nil
}

// 领奖协议
type ExpeditionClaimRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleFiledId int32                  `protobuf:"varint,1,opt,name=battleFiledId,proto3" json:"battleFiledId,omitempty"` // 战场id
	PointId       int32                  `protobuf:"varint,2,opt,name=pointId,proto3" json:"pointId,omitempty"`             // 点id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionClaimRewardReq) Reset() {
	*x = ExpeditionClaimRewardReq{}
	mi := &file_expeditionMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionClaimRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionClaimRewardReq) ProtoMessage() {}

func (x *ExpeditionClaimRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionClaimRewardReq.ProtoReflect.Descriptor instead.
func (*ExpeditionClaimRewardReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{9}
}

func (x *ExpeditionClaimRewardReq) GetBattleFiledId() int32 {
	if x != nil {
		return x.BattleFiledId
	}
	return 0
}

func (x *ExpeditionClaimRewardReq) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

type ExpeditionClaimRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reward        []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=reward,proto3" json:"reward,omitempty"` // 奖励
	IsWin         int32                  `protobuf:"varint,2,opt,name=isWin,proto3" json:"isWin,omitempty"`  // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionClaimRewardResp) Reset() {
	*x = ExpeditionClaimRewardResp{}
	mi := &file_expeditionMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionClaimRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionClaimRewardResp) ProtoMessage() {}

func (x *ExpeditionClaimRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionClaimRewardResp.ProtoReflect.Descriptor instead.
func (*ExpeditionClaimRewardResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{10}
}

func (x *ExpeditionClaimRewardResp) GetReward() []*ItemBasicInfo {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *ExpeditionClaimRewardResp) GetIsWin() int32 {
	if x != nil {
		return x.IsWin
	}
	return 0
}

// 加速
type ExpeditionSpeedUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[int32]int32        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 加速使用的道具id
	SlotId        int32                  `protobuf:"varint,2,opt,name=slotId,proto3" json:"slotId,omitempty"`                                                                          // 槽位id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionSpeedUpReq) Reset() {
	*x = ExpeditionSpeedUpReq{}
	mi := &file_expeditionMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionSpeedUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionSpeedUpReq) ProtoMessage() {}

func (x *ExpeditionSpeedUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionSpeedUpReq.ProtoReflect.Descriptor instead.
func (*ExpeditionSpeedUpReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{11}
}

func (x *ExpeditionSpeedUpReq) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ExpeditionSpeedUpReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type ExpeditionSpeedUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *ExpeditionSlotInfo    `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"` // 槽位信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionSpeedUpResp) Reset() {
	*x = ExpeditionSpeedUpResp{}
	mi := &file_expeditionMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionSpeedUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionSpeedUpResp) ProtoMessage() {}

func (x *ExpeditionSpeedUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionSpeedUpResp.ProtoReflect.Descriptor instead.
func (*ExpeditionSpeedUpResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{12}
}

func (x *ExpeditionSpeedUpResp) GetSlot() *ExpeditionSlotInfo {
	if x != nil {
		return x.Slot
	}
	return nil
}

// 停止
type ExpeditionCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        int32                  `protobuf:"varint,1,opt,name=slotId,proto3" json:"slotId,omitempty"` // 槽位id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionCancelReq) Reset() {
	*x = ExpeditionCancelReq{}
	mi := &file_expeditionMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionCancelReq) ProtoMessage() {}

func (x *ExpeditionCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionCancelReq.ProtoReflect.Descriptor instead.
func (*ExpeditionCancelReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{13}
}

func (x *ExpeditionCancelReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type ExpeditionCancelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *ExpeditionSlotInfo    `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"` // 槽位信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionCancelResp) Reset() {
	*x = ExpeditionCancelResp{}
	mi := &file_expeditionMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionCancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionCancelResp) ProtoMessage() {}

func (x *ExpeditionCancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionCancelResp.ProtoReflect.Descriptor instead.
func (*ExpeditionCancelResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{14}
}

func (x *ExpeditionCancelResp) GetSlot() *ExpeditionSlotInfo {
	if x != nil {
		return x.Slot
	}
	return nil
}

// 改变战场等级
type ExpeditionChangeLevelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattlefieldId int32                  `protobuf:"varint,1,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"` // 战场id
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                 // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionChangeLevelReq) Reset() {
	*x = ExpeditionChangeLevelReq{}
	mi := &file_expeditionMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionChangeLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionChangeLevelReq) ProtoMessage() {}

func (x *ExpeditionChangeLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionChangeLevelReq.ProtoReflect.Descriptor instead.
func (*ExpeditionChangeLevelReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{15}
}

func (x *ExpeditionChangeLevelReq) GetBattlefieldId() int32 {
	if x != nil {
		return x.BattlefieldId
	}
	return 0
}

func (x *ExpeditionChangeLevelReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type ExpeditionChangeLevelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionChangeLevelResp) Reset() {
	*x = ExpeditionChangeLevelResp{}
	mi := &file_expeditionMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionChangeLevelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionChangeLevelResp) ProtoMessage() {}

func (x *ExpeditionChangeLevelResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionChangeLevelResp.ProtoReflect.Descriptor instead.
func (*ExpeditionChangeLevelResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{16}
}

// 领取免费耐力
type ExpeditionClaimFreeStaminaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionClaimFreeStaminaReq) Reset() {
	*x = ExpeditionClaimFreeStaminaReq{}
	mi := &file_expeditionMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionClaimFreeStaminaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionClaimFreeStaminaReq) ProtoMessage() {}

func (x *ExpeditionClaimFreeStaminaReq) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionClaimFreeStaminaReq.ProtoReflect.Descriptor instead.
func (*ExpeditionClaimFreeStaminaReq) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{17}
}

type ExpeditionClaimFreeStaminaResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FreeCDTimeStamp int64                  `protobuf:"varint,4,opt,name=freeCDTimeStamp,proto3" json:"freeCDTimeStamp,omitempty"` // 免费领取cd结束时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpeditionClaimFreeStaminaResp) Reset() {
	*x = ExpeditionClaimFreeStaminaResp{}
	mi := &file_expeditionMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionClaimFreeStaminaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionClaimFreeStaminaResp) ProtoMessage() {}

func (x *ExpeditionClaimFreeStaminaResp) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionClaimFreeStaminaResp.ProtoReflect.Descriptor instead.
func (*ExpeditionClaimFreeStaminaResp) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{18}
}

func (x *ExpeditionClaimFreeStaminaResp) GetFreeCDTimeStamp() int64 {
	if x != nil {
		return x.FreeCDTimeStamp
	}
	return 0
}

// 推送变化
type ExpeditionChangePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*ExpeditionSlotInfo  `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`   // 槽位信息
	Points        []*ExpeditionPointInfo `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"` // 点位信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpeditionChangePush) Reset() {
	*x = ExpeditionChangePush{}
	mi := &file_expeditionMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpeditionChangePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpeditionChangePush) ProtoMessage() {}

func (x *ExpeditionChangePush) ProtoReflect() protoreflect.Message {
	mi := &file_expeditionMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpeditionChangePush.ProtoReflect.Descriptor instead.
func (*ExpeditionChangePush) Descriptor() ([]byte, []int) {
	return file_expeditionMessage_proto_rawDescGZIP(), []int{19}
}

func (x *ExpeditionChangePush) GetSlots() []*ExpeditionSlotInfo {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ExpeditionChangePush) GetPoints() []*ExpeditionPointInfo {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_expeditionMessage_proto protoreflect.FileDescriptor

const file_expeditionMessage_proto_rawDesc = "" +
	"\n" +
	"\x17expeditionMessage.proto\x12\x02pb\x1a\x13commonMessage.proto\"\xaa\x01\n" +
	"\x19ExpeditionBattlefieldInfo\x12$\n" +
	"\rbattlefieldId\x18\x01 \x01(\x05R\rbattlefieldId\x12*\n" +
	"\x10battlefieldLevel\x18\x02 \x01(\x05R\x10battlefieldLevel\x12;\n" +
	"\fmonsterInfos\x18\x03 \x03(\v2\x17.pb.ExpeditionPointInfoR\fmonsterInfos\"\x93\x01\n" +
	"\x13ExpeditionPointInfo\x12\x18\n" +
	"\apointId\x18\x01 \x01(\x05R\apointId\x12\x1c\n" +
	"\tmonsterId\x18\x02 \x01(\x05R\tmonsterId\x12(\n" +
	"\x0fnextRefreshTime\x18\x03 \x01(\x03R\x0fnextRefreshTime\x12\x1a\n" +
	"\bisReward\x18\x04 \x01(\x05R\bisReward\"\xa0\x01\n" +
	"\x12ExpeditionSlotInfo\x12\x16\n" +
	"\x06slotId\x18\x01 \x01(\x05R\x06slotId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12$\n" +
	"\rbattlefieldId\x18\x03 \x01(\x05R\rbattlefieldId\x12\x18\n" +
	"\apointId\x18\x04 \x01(\x05R\apointId\x12\x1a\n" +
	"\boverTime\x18\x05 \x01(\x03R\boverTime\"\x13\n" +
	"\x11ExpeditionInfoReq\"\x97\x02\n" +
	"\x12ExpeditionInfoResp\x12A\n" +
	"\fbattlefields\x18\x01 \x03(\v2\x1d.pb.ExpeditionBattlefieldInfoR\fbattlefields\x12,\n" +
	"\x05slots\x18\x02 \x03(\v2\x16.pb.ExpeditionSlotInfoR\x05slots\x12&\n" +
	"\x0efreeClaimCount\x18\x03 \x01(\x05R\x0efreeClaimCount\x12(\n" +
	"\x0ffreeCDTimeStamp\x18\x04 \x01(\x03R\x0ffreeCDTimeStamp\x12>\n" +
	"\x1aLastPowerRecoveryTimeStamp\x18\x05 \x01(\x03R\x1aLastPowerRecoveryTimeStamp\"l\n" +
	"\x12ExpeditionStartReq\x12\x16\n" +
	"\x06slotId\x18\x01 \x01(\x05R\x06slotId\x12$\n" +
	"\rbattlefieldId\x18\x02 \x01(\x05R\rbattlefieldId\x12\x18\n" +
	"\apointId\x18\x03 \x01(\x05R\apointId\"E\n" +
	"\x13ExpeditionStartResp\x12.\n" +
	"\x06active\x18\x01 \x01(\v2\x16.pb.ExpeditionSlotInfoR\x06active\"-\n" +
	"\x13ExpeditionFinishReq\x12\x16\n" +
	"\x06slotId\x18\x01 \x01(\x05R\x06slotId\"\x7f\n" +
	"\x14ExpeditionFinishResp\x12*\n" +
	"\x04slot\x18\x01 \x01(\v2\x16.pb.ExpeditionSlotInfoR\x04slot\x12;\n" +
	"\fmonsterInfos\x18\x03 \x01(\v2\x17.pb.ExpeditionPointInfoR\fmonsterInfos\"Z\n" +
	"\x18ExpeditionClaimRewardReq\x12$\n" +
	"\rbattleFiledId\x18\x01 \x01(\x05R\rbattleFiledId\x12\x18\n" +
	"\apointId\x18\x02 \x01(\x05R\apointId\"\\\n" +
	"\x19ExpeditionClaimRewardResp\x12)\n" +
	"\x06reward\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\x06reward\x12\x14\n" +
	"\x05isWin\x18\x02 \x01(\x05R\x05isWin\"\xa3\x01\n" +
	"\x14ExpeditionSpeedUpReq\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.pb.ExpeditionSpeedUpReq.ItemsEntryR\x05items\x12\x16\n" +
	"\x06slotId\x18\x02 \x01(\x05R\x06slotId\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"C\n" +
	"\x15ExpeditionSpeedUpResp\x12*\n" +
	"\x04slot\x18\x01 \x01(\v2\x16.pb.ExpeditionSlotInfoR\x04slot\"-\n" +
	"\x13ExpeditionCancelReq\x12\x16\n" +
	"\x06slotId\x18\x01 \x01(\x05R\x06slotId\"B\n" +
	"\x14ExpeditionCancelResp\x12*\n" +
	"\x04slot\x18\x01 \x01(\v2\x16.pb.ExpeditionSlotInfoR\x04slot\"V\n" +
	"\x18ExpeditionChangeLevelReq\x12$\n" +
	"\rbattlefieldId\x18\x01 \x01(\x05R\rbattlefieldId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x1b\n" +
	"\x19ExpeditionChangeLevelResp\"\x1f\n" +
	"\x1dExpeditionClaimFreeStaminaReq\"J\n" +
	"\x1eExpeditionClaimFreeStaminaResp\x12(\n" +
	"\x0ffreeCDTimeStamp\x18\x04 \x01(\x03R\x0ffreeCDTimeStamp\"u\n" +
	"\x14ExpeditionChangePush\x12,\n" +
	"\x05slots\x18\x01 \x03(\v2\x16.pb.ExpeditionSlotInfoR\x05slots\x12/\n" +
	"\x06points\x18\x02 \x03(\v2\x17.pb.ExpeditionPointInfoR\x06pointsB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_expeditionMessage_proto_rawDescOnce sync.Once
	file_expeditionMessage_proto_rawDescData []byte
)

func file_expeditionMessage_proto_rawDescGZIP() []byte {
	file_expeditionMessage_proto_rawDescOnce.Do(func() {
		file_expeditionMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expeditionMessage_proto_rawDesc), len(file_expeditionMessage_proto_rawDesc)))
	})
	return file_expeditionMessage_proto_rawDescData
}

var file_expeditionMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_expeditionMessage_proto_goTypes = []any{
	(*ExpeditionBattlefieldInfo)(nil),      // 0: pb.ExpeditionBattlefieldInfo
	(*ExpeditionPointInfo)(nil),            // 1: pb.ExpeditionPointInfo
	(*ExpeditionSlotInfo)(nil),             // 2: pb.ExpeditionSlotInfo
	(*ExpeditionInfoReq)(nil),              // 3: pb.ExpeditionInfoReq
	(*ExpeditionInfoResp)(nil),             // 4: pb.ExpeditionInfoResp
	(*ExpeditionStartReq)(nil),             // 5: pb.ExpeditionStartReq
	(*ExpeditionStartResp)(nil),            // 6: pb.ExpeditionStartResp
	(*ExpeditionFinishReq)(nil),            // 7: pb.ExpeditionFinishReq
	(*ExpeditionFinishResp)(nil),           // 8: pb.ExpeditionFinishResp
	(*ExpeditionClaimRewardReq)(nil),       // 9: pb.ExpeditionClaimRewardReq
	(*ExpeditionClaimRewardResp)(nil),      // 10: pb.ExpeditionClaimRewardResp
	(*ExpeditionSpeedUpReq)(nil),           // 11: pb.ExpeditionSpeedUpReq
	(*ExpeditionSpeedUpResp)(nil),          // 12: pb.ExpeditionSpeedUpResp
	(*ExpeditionCancelReq)(nil),            // 13: pb.ExpeditionCancelReq
	(*ExpeditionCancelResp)(nil),           // 14: pb.ExpeditionCancelResp
	(*ExpeditionChangeLevelReq)(nil),       // 15: pb.ExpeditionChangeLevelReq
	(*ExpeditionChangeLevelResp)(nil),      // 16: pb.ExpeditionChangeLevelResp
	(*ExpeditionClaimFreeStaminaReq)(nil),  // 17: pb.ExpeditionClaimFreeStaminaReq
	(*ExpeditionClaimFreeStaminaResp)(nil), // 18: pb.ExpeditionClaimFreeStaminaResp
	(*ExpeditionChangePush)(nil),           // 19: pb.ExpeditionChangePush
	nil,                                    // 20: pb.ExpeditionSpeedUpReq.ItemsEntry
	(*ItemBasicInfo)(nil),                  // 21: pb.ItemBasicInfo
}
var file_expeditionMessage_proto_depIdxs = []int32{
	1,  // 0: pb.ExpeditionBattlefieldInfo.monsterInfos:type_name -> pb.ExpeditionPointInfo
	0,  // 1: pb.ExpeditionInfoResp.battlefields:type_name -> pb.ExpeditionBattlefieldInfo
	2,  // 2: pb.ExpeditionInfoResp.slots:type_name -> pb.ExpeditionSlotInfo
	2,  // 3: pb.ExpeditionStartResp.active:type_name -> pb.ExpeditionSlotInfo
	2,  // 4: pb.ExpeditionFinishResp.slot:type_name -> pb.ExpeditionSlotInfo
	1,  // 5: pb.ExpeditionFinishResp.monsterInfos:type_name -> pb.ExpeditionPointInfo
	21, // 6: pb.ExpeditionClaimRewardResp.reward:type_name -> pb.ItemBasicInfo
	20, // 7: pb.ExpeditionSpeedUpReq.items:type_name -> pb.ExpeditionSpeedUpReq.ItemsEntry
	2,  // 8: pb.ExpeditionSpeedUpResp.slot:type_name -> pb.ExpeditionSlotInfo
	2,  // 9: pb.ExpeditionCancelResp.slot:type_name -> pb.ExpeditionSlotInfo
	2,  // 10: pb.ExpeditionChangePush.slots:type_name -> pb.ExpeditionSlotInfo
	1,  // 11: pb.ExpeditionChangePush.points:type_name -> pb.ExpeditionPointInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_expeditionMessage_proto_init() }
func file_expeditionMessage_proto_init() {
	if File_expeditionMessage_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expeditionMessage_proto_rawDesc), len(file_expeditionMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expeditionMessage_proto_goTypes,
		DependencyIndexes: file_expeditionMessage_proto_depIdxs,
		MessageInfos:      file_expeditionMessage_proto_msgTypes,
	}.Build()
	File_expeditionMessage_proto = out.File
	file_expeditionMessage_proto_goTypes = nil
	file_expeditionMessage_proto_depIdxs = nil
}
