// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: gmMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GM命令类型枚举
type GMCommandType int32

const (
	GMCommandType_GM_CMD_UNKNOWN GMCommandType = 0
	// 道具相关
	GMCommandType_GM_CMD_ADD_ITEM    GMCommandType = 1 // 添加道具
	GMCommandType_GM_CMD_REMOVE_ITEM GMCommandType = 2 // 移除道具
	// 经验相关
	GMCommandType_GM_CMD_ADD_EXP   GMCommandType = 3 // 增加经验
	GMCommandType_GM_CMD_SET_LEVEL GMCommandType = 4 // 设置等级
	// 英雄相关
	GMCommandType_GM_CMD_HERO_LEVEL_UP GMCommandType = 5 // 英雄升级
	GMCommandType_GM_CMD_HERO_STAR_UP  GMCommandType = 6 // 英雄升星
	// 货币相关
	GMCommandType_GM_CMD_ADD_CURRENCY    GMCommandType = 7 // 增加货币
	GMCommandType_GM_CMD_REMOVE_CURRENCY GMCommandType = 8 // 移除货币
	// 装备相关
	GMCommandType_GM_CMD_ADD_EQUIPMENT    GMCommandType = 9  // 添加装备
	GMCommandType_GM_CMD_REMOVE_EQUIPMENT GMCommandType = 10 // 移除装备
	GMCommandType_GM_CMD_ADD_HERO         GMCommandType = 11 // 添加英雄
	// 邮件相关
	GMCommandType_GM_CMD_SEND_MAIL        GMCommandType = 12 // 发送个人邮件
	GMCommandType_GM_CMD_SEND_SERVER_MAIL GMCommandType = 13 // 发送全服邮件
	// 副本相关
	GMCommandType_GM_CMD_CHANGE_MAIN_STAGE GMCommandType = 14 // 切换主线副本
	// 任务相关
	GMCommandType_GM_CMD_JUMP_THIS_MAIN_TASK GMCommandType = 15 // 跳过当前主线任务完成过程
	// 宠物相关
	GMCommandType_GM_CMD_ADD_PET GMCommandType = 16 // 添加宠物
)

// Enum value maps for GMCommandType.
var (
	GMCommandType_name = map[int32]string{
		0:  "GM_CMD_UNKNOWN",
		1:  "GM_CMD_ADD_ITEM",
		2:  "GM_CMD_REMOVE_ITEM",
		3:  "GM_CMD_ADD_EXP",
		4:  "GM_CMD_SET_LEVEL",
		5:  "GM_CMD_HERO_LEVEL_UP",
		6:  "GM_CMD_HERO_STAR_UP",
		7:  "GM_CMD_ADD_CURRENCY",
		8:  "GM_CMD_REMOVE_CURRENCY",
		9:  "GM_CMD_ADD_EQUIPMENT",
		10: "GM_CMD_REMOVE_EQUIPMENT",
		11: "GM_CMD_ADD_HERO",
		12: "GM_CMD_SEND_MAIL",
		13: "GM_CMD_SEND_SERVER_MAIL",
		14: "GM_CMD_CHANGE_MAIN_STAGE",
		15: "GM_CMD_JUMP_THIS_MAIN_TASK",
		16: "GM_CMD_ADD_PET",
	}
	GMCommandType_value = map[string]int32{
		"GM_CMD_UNKNOWN":             0,
		"GM_CMD_ADD_ITEM":            1,
		"GM_CMD_REMOVE_ITEM":         2,
		"GM_CMD_ADD_EXP":             3,
		"GM_CMD_SET_LEVEL":           4,
		"GM_CMD_HERO_LEVEL_UP":       5,
		"GM_CMD_HERO_STAR_UP":        6,
		"GM_CMD_ADD_CURRENCY":        7,
		"GM_CMD_REMOVE_CURRENCY":     8,
		"GM_CMD_ADD_EQUIPMENT":       9,
		"GM_CMD_REMOVE_EQUIPMENT":    10,
		"GM_CMD_ADD_HERO":            11,
		"GM_CMD_SEND_MAIL":           12,
		"GM_CMD_SEND_SERVER_MAIL":    13,
		"GM_CMD_CHANGE_MAIN_STAGE":   14,
		"GM_CMD_JUMP_THIS_MAIN_TASK": 15,
		"GM_CMD_ADD_PET":             16,
	}
)

func (x GMCommandType) Enum() *GMCommandType {
	p := new(GMCommandType)
	*p = x
	return p
}

func (x GMCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GMCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_gmMessage_proto_enumTypes[0].Descriptor()
}

func (GMCommandType) Type() protoreflect.EnumType {
	return &file_gmMessage_proto_enumTypes[0]
}

func (x GMCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GMCommandType.Descriptor instead.
func (GMCommandType) EnumDescriptor() ([]byte, []int) {
	return file_gmMessage_proto_rawDescGZIP(), []int{0}
}

// GM调用方类型
type GMInvokerType int32

const (
	GMInvokerType_GM_INVOKER_UNKNOWN  GMInvokerType = 0
	GMInvokerType_GM_INVOKER_CLIENT   GMInvokerType = 1 // 客户端调用
	GMInvokerType_GM_INVOKER_INTERNAL GMInvokerType = 2 // 程序内部调用
	GMInvokerType_GM_INVOKER_RPC      GMInvokerType = 3 // RPC调用（运营后台）
)

// Enum value maps for GMInvokerType.
var (
	GMInvokerType_name = map[int32]string{
		0: "GM_INVOKER_UNKNOWN",
		1: "GM_INVOKER_CLIENT",
		2: "GM_INVOKER_INTERNAL",
		3: "GM_INVOKER_RPC",
	}
	GMInvokerType_value = map[string]int32{
		"GM_INVOKER_UNKNOWN":  0,
		"GM_INVOKER_CLIENT":   1,
		"GM_INVOKER_INTERNAL": 2,
		"GM_INVOKER_RPC":      3,
	}
)

func (x GMInvokerType) Enum() *GMInvokerType {
	p := new(GMInvokerType)
	*p = x
	return p
}

func (x GMInvokerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GMInvokerType) Descriptor() protoreflect.EnumDescriptor {
	return file_gmMessage_proto_enumTypes[1].Descriptor()
}

func (GMInvokerType) Type() protoreflect.EnumType {
	return &file_gmMessage_proto_enumTypes[1]
}

func (x GMInvokerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GMInvokerType.Descriptor instead.
func (GMInvokerType) EnumDescriptor() ([]byte, []int) {
	return file_gmMessage_proto_rawDescGZIP(), []int{1}
}

// GM结果枚举
type GMResult int32

const (
	GMResult_GM_RESULT_SUCCESS           GMResult = 0 // 成功
	GMResult_GM_RESULT_FAILED            GMResult = 1 // 失败
	GMResult_GM_RESULT_INVALID_CMD       GMResult = 2 // 无效命令
	GMResult_GM_RESULT_INVALID_USER      GMResult = 3 // 无效用户
	GMResult_GM_RESULT_INVALID_PARAM     GMResult = 4 // 无效参数
	GMResult_GM_RESULT_INVOKER_DISABLED  GMResult = 5 // 调用方已禁用
	GMResult_GM_RESULT_PERMISSION_DENIED GMResult = 6 // 权限不足
)

// Enum value maps for GMResult.
var (
	GMResult_name = map[int32]string{
		0: "GM_RESULT_SUCCESS",
		1: "GM_RESULT_FAILED",
		2: "GM_RESULT_INVALID_CMD",
		3: "GM_RESULT_INVALID_USER",
		4: "GM_RESULT_INVALID_PARAM",
		5: "GM_RESULT_INVOKER_DISABLED",
		6: "GM_RESULT_PERMISSION_DENIED",
	}
	GMResult_value = map[string]int32{
		"GM_RESULT_SUCCESS":           0,
		"GM_RESULT_FAILED":            1,
		"GM_RESULT_INVALID_CMD":       2,
		"GM_RESULT_INVALID_USER":      3,
		"GM_RESULT_INVALID_PARAM":     4,
		"GM_RESULT_INVOKER_DISABLED":  5,
		"GM_RESULT_PERMISSION_DENIED": 6,
	}
)

func (x GMResult) Enum() *GMResult {
	p := new(GMResult)
	*p = x
	return p
}

func (x GMResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GMResult) Descriptor() protoreflect.EnumDescriptor {
	return file_gmMessage_proto_enumTypes[2].Descriptor()
}

func (GMResult) Type() protoreflect.EnumType {
	return &file_gmMessage_proto_enumTypes[2]
}

func (x GMResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GMResult.Descriptor instead.
func (GMResult) EnumDescriptor() ([]byte, []int) {
	return file_gmMessage_proto_rawDescGZIP(), []int{2}
}

// GM命令请求
type MessageGmReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	CmdType GMCommandType          `protobuf:"varint,1,opt,name=cmdType,proto3,enum=pb.GMCommandType" json:"cmdType,omitempty"` // 命令类型
	UserId  int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`                         // 用户ID（客户端调用时可省略，使用登录用户ID）
	// 额外参数（JSON格式，用于扩展）
	ExtraParams string `protobuf:"bytes,3,opt,name=extraParams,proto3" json:"extraParams,omitempty"`
	// 调用方类型（由系统自动填充）
	InvokerType GMInvokerType `protobuf:"varint,4,opt,name=invokerType,proto3,enum=pb.GMInvokerType" json:"invokerType,omitempty"`
	InvokerId   string        `protobuf:"bytes,5,opt,name=invokerId,proto3" json:"invokerId,omitempty"` // 调用方标识（如IP、服务名等）
	// 道具相关参数
	ItemId        int64 `protobuf:"varint,6,opt,name=itemId,proto3" json:"itemId,omitempty"`               // 道具ID
	ItemQuantity  int32 `protobuf:"varint,7,opt,name=itemQuantity,proto3" json:"itemQuantity,omitempty"`   // 道具数量
	InventoryType int32 `protobuf:"varint,8,opt,name=inventoryType,proto3" json:"inventoryType,omitempty"` // 背包类型
	// 经验相关参数
	Exp int64 `protobuf:"varint,9,opt,name=exp,proto3" json:"exp,omitempty"` // 经验值
	// 等级相关参数
	Level int32 `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"` // 等级
	// 英雄相关参数
	HeroId    int64 `protobuf:"varint,11,opt,name=heroId,proto3" json:"heroId,omitempty"`       // 英雄配置ID
	HeroOwnId int64 `protobuf:"varint,12,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"` // 英雄唯一ID
	HeroLevel int32 `protobuf:"varint,13,opt,name=heroLevel,proto3" json:"heroLevel,omitempty"` // 英雄等级
	HeroStar  int32 `protobuf:"varint,14,opt,name=heroStar,proto3" json:"heroStar,omitempty"`   // 英雄星级
	// 货币相关参数
	CurrencyType   int32 `protobuf:"varint,15,opt,name=currencyType,proto3" json:"currencyType,omitempty"`     // 货币类型
	CurrencyAmount int64 `protobuf:"varint,16,opt,name=currencyAmount,proto3" json:"currencyAmount,omitempty"` // 货币数量
	MainStageId    int32 `protobuf:"varint,17,opt,name=mainStageId,proto3" json:"mainStageId,omitempty"`       // 主线副本ID
	MainSubStageId int32 `protobuf:"varint,18,opt,name=mainSubStageId,proto3" json:"mainSubStageId,omitempty"` // 主线副本房间ID
	// 邮件相关参数
	Title         string                `protobuf:"bytes,19,opt,name=title,proto3" json:"title,omitempty"`                // 邮件标题
	Content       string                `protobuf:"bytes,20,opt,name=content,proto3" json:"content,omitempty"`            // 邮件内容
	MailType      int32                 `protobuf:"varint,21,opt,name=mailType,proto3" json:"mailType,omitempty"`         // 邮件类型（1=个人邮件，2=全服邮件）
	SenderAvatar  string                `protobuf:"bytes,22,opt,name=senderAvatar,proto3" json:"senderAvatar,omitempty"`  // 发送者头像（可选）
	Items         []*MailAttachmentItem `protobuf:"bytes,23,rep,name=items,proto3" json:"items,omitempty"`                // 附件物品条目（业务约定：只有一个附件，直接传 items
	IsConvenient  bool                  `protobuf:"varint,24,opt,name=IsConvenient,proto3" json:"IsConvenient,omitempty"` // 是否可一键领取（true=可一键领取；false=只能单独领取）
	ExpireDays    int32                 `protobuf:"varint,25,opt,name=expireDays,proto3" json:"expireDays,omitempty"`     // 邮件过期天数（0表示永不过期）
	CfgId         int32                 `protobuf:"varint,26,opt,name=cfgId,proto3" json:"cfgId,omitempty"`               // 邮件模板ID（0表示未使用模板）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageGmReq) Reset() {
	*x = MessageGmReq{}
	mi := &file_gmMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageGmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGmReq) ProtoMessage() {}

func (x *MessageGmReq) ProtoReflect() protoreflect.Message {
	mi := &file_gmMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGmReq.ProtoReflect.Descriptor instead.
func (*MessageGmReq) Descriptor() ([]byte, []int) {
	return file_gmMessage_proto_rawDescGZIP(), []int{0}
}

func (x *MessageGmReq) GetCmdType() GMCommandType {
	if x != nil {
		return x.CmdType
	}
	return GMCommandType_GM_CMD_UNKNOWN
}

func (x *MessageGmReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MessageGmReq) GetExtraParams() string {
	if x != nil {
		return x.ExtraParams
	}
	return ""
}

func (x *MessageGmReq) GetInvokerType() GMInvokerType {
	if x != nil {
		return x.InvokerType
	}
	return GMInvokerType_GM_INVOKER_UNKNOWN
}

func (x *MessageGmReq) GetInvokerId() string {
	if x != nil {
		return x.InvokerId
	}
	return ""
}

func (x *MessageGmReq) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MessageGmReq) GetItemQuantity() int32 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *MessageGmReq) GetInventoryType() int32 {
	if x != nil {
		return x.InventoryType
	}
	return 0
}

func (x *MessageGmReq) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *MessageGmReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MessageGmReq) GetHeroId() int64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *MessageGmReq) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *MessageGmReq) GetHeroLevel() int32 {
	if x != nil {
		return x.HeroLevel
	}
	return 0
}

func (x *MessageGmReq) GetHeroStar() int32 {
	if x != nil {
		return x.HeroStar
	}
	return 0
}

func (x *MessageGmReq) GetCurrencyType() int32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

func (x *MessageGmReq) GetCurrencyAmount() int64 {
	if x != nil {
		return x.CurrencyAmount
	}
	return 0
}

func (x *MessageGmReq) GetMainStageId() int32 {
	if x != nil {
		return x.MainStageId
	}
	return 0
}

func (x *MessageGmReq) GetMainSubStageId() int32 {
	if x != nil {
		return x.MainSubStageId
	}
	return 0
}

func (x *MessageGmReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageGmReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageGmReq) GetMailType() int32 {
	if x != nil {
		return x.MailType
	}
	return 0
}

func (x *MessageGmReq) GetSenderAvatar() string {
	if x != nil {
		return x.SenderAvatar
	}
	return ""
}

func (x *MessageGmReq) GetItems() []*MailAttachmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MessageGmReq) GetIsConvenient() bool {
	if x != nil {
		return x.IsConvenient
	}
	return false
}

func (x *MessageGmReq) GetExpireDays() int32 {
	if x != nil {
		return x.ExpireDays
	}
	return 0
}

func (x *MessageGmReq) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// GM命令响应
type MessageGmResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        GMResult               `protobuf:"varint,1,opt,name=result,proto3,enum=pb.GMResult" json:"result,omitempty"`                                                               // 结果码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                               // 消息
	ExtraData     map[string]string      `protobuf:"bytes,3,rep,name=extraData,proto3" json:"extraData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外返回数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageGmResp) Reset() {
	*x = MessageGmResp{}
	mi := &file_gmMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageGmResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGmResp) ProtoMessage() {}

func (x *MessageGmResp) ProtoReflect() protoreflect.Message {
	mi := &file_gmMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGmResp.ProtoReflect.Descriptor instead.
func (*MessageGmResp) Descriptor() ([]byte, []int) {
	return file_gmMessage_proto_rawDescGZIP(), []int{1}
}

func (x *MessageGmResp) GetResult() GMResult {
	if x != nil {
		return x.Result
	}
	return GMResult_GM_RESULT_SUCCESS
}

func (x *MessageGmResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageGmResp) GetExtraData() map[string]string {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

var File_gmMessage_proto protoreflect.FileDescriptor

const file_gmMessage_proto_rawDesc = "" +
	"\n" +
	"\x0fgmMessage.proto\x12\x02pb\x1a\x11mailMessage.proto\"\xd0\x06\n" +
	"\fMessageGmReq\x12+\n" +
	"\acmdType\x18\x01 \x01(\x0e2\x11.pb.GMCommandTypeR\acmdType\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12 \n" +
	"\vextraParams\x18\x03 \x01(\tR\vextraParams\x123\n" +
	"\vinvokerType\x18\x04 \x01(\x0e2\x11.pb.GMInvokerTypeR\vinvokerType\x12\x1c\n" +
	"\tinvokerId\x18\x05 \x01(\tR\tinvokerId\x12\x16\n" +
	"\x06itemId\x18\x06 \x01(\x03R\x06itemId\x12\"\n" +
	"\fitemQuantity\x18\a \x01(\x05R\fitemQuantity\x12$\n" +
	"\rinventoryType\x18\b \x01(\x05R\rinventoryType\x12\x10\n" +
	"\x03exp\x18\t \x01(\x03R\x03exp\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x16\n" +
	"\x06heroId\x18\v \x01(\x03R\x06heroId\x12\x1c\n" +
	"\theroOwnId\x18\f \x01(\x03R\theroOwnId\x12\x1c\n" +
	"\theroLevel\x18\r \x01(\x05R\theroLevel\x12\x1a\n" +
	"\bheroStar\x18\x0e \x01(\x05R\bheroStar\x12\"\n" +
	"\fcurrencyType\x18\x0f \x01(\x05R\fcurrencyType\x12&\n" +
	"\x0ecurrencyAmount\x18\x10 \x01(\x03R\x0ecurrencyAmount\x12 \n" +
	"\vmainStageId\x18\x11 \x01(\x05R\vmainStageId\x12&\n" +
	"\x0emainSubStageId\x18\x12 \x01(\x05R\x0emainSubStageId\x12\x14\n" +
	"\x05title\x18\x13 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x14 \x01(\tR\acontent\x12\x1a\n" +
	"\bmailType\x18\x15 \x01(\x05R\bmailType\x12\"\n" +
	"\fsenderAvatar\x18\x16 \x01(\tR\fsenderAvatar\x12,\n" +
	"\x05items\x18\x17 \x03(\v2\x16.pb.MailAttachmentItemR\x05items\x12\"\n" +
	"\fIsConvenient\x18\x18 \x01(\bR\fIsConvenient\x12\x1e\n" +
	"\n" +
	"expireDays\x18\x19 \x01(\x05R\n" +
	"expireDays\x12\x14\n" +
	"\x05cfgId\x18\x1a \x01(\x05R\x05cfgId\"\xcd\x01\n" +
	"\rMessageGmResp\x12$\n" +
	"\x06result\x18\x01 \x01(\x0e2\f.pb.GMResultR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\textraData\x18\x03 \x03(\v2 .pb.MessageGmResp.ExtraDataEntryR\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb3\x03\n" +
	"\rGMCommandType\x12\x12\n" +
	"\x0eGM_CMD_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fGM_CMD_ADD_ITEM\x10\x01\x12\x16\n" +
	"\x12GM_CMD_REMOVE_ITEM\x10\x02\x12\x12\n" +
	"\x0eGM_CMD_ADD_EXP\x10\x03\x12\x14\n" +
	"\x10GM_CMD_SET_LEVEL\x10\x04\x12\x18\n" +
	"\x14GM_CMD_HERO_LEVEL_UP\x10\x05\x12\x17\n" +
	"\x13GM_CMD_HERO_STAR_UP\x10\x06\x12\x17\n" +
	"\x13GM_CMD_ADD_CURRENCY\x10\a\x12\x1a\n" +
	"\x16GM_CMD_REMOVE_CURRENCY\x10\b\x12\x18\n" +
	"\x14GM_CMD_ADD_EQUIPMENT\x10\t\x12\x1b\n" +
	"\x17GM_CMD_REMOVE_EQUIPMENT\x10\n" +
	"\x12\x13\n" +
	"\x0fGM_CMD_ADD_HERO\x10\v\x12\x14\n" +
	"\x10GM_CMD_SEND_MAIL\x10\f\x12\x1b\n" +
	"\x17GM_CMD_SEND_SERVER_MAIL\x10\r\x12\x1c\n" +
	"\x18GM_CMD_CHANGE_MAIN_STAGE\x10\x0e\x12\x1e\n" +
	"\x1aGM_CMD_JUMP_THIS_MAIN_TASK\x10\x0f\x12\x12\n" +
	"\x0eGM_CMD_ADD_PET\x10\x10*k\n" +
	"\rGMInvokerType\x12\x16\n" +
	"\x12GM_INVOKER_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11GM_INVOKER_CLIENT\x10\x01\x12\x17\n" +
	"\x13GM_INVOKER_INTERNAL\x10\x02\x12\x12\n" +
	"\x0eGM_INVOKER_RPC\x10\x03*\xcc\x01\n" +
	"\bGMResult\x12\x15\n" +
	"\x11GM_RESULT_SUCCESS\x10\x00\x12\x14\n" +
	"\x10GM_RESULT_FAILED\x10\x01\x12\x19\n" +
	"\x15GM_RESULT_INVALID_CMD\x10\x02\x12\x1a\n" +
	"\x16GM_RESULT_INVALID_USER\x10\x03\x12\x1b\n" +
	"\x17GM_RESULT_INVALID_PARAM\x10\x04\x12\x1e\n" +
	"\x1aGM_RESULT_INVOKER_DISABLED\x10\x05\x12\x1f\n" +
	"\x1bGM_RESULT_PERMISSION_DENIED\x10\x06B\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_gmMessage_proto_rawDescOnce sync.Once
	file_gmMessage_proto_rawDescData []byte
)

func file_gmMessage_proto_rawDescGZIP() []byte {
	file_gmMessage_proto_rawDescOnce.Do(func() {
		file_gmMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gmMessage_proto_rawDesc), len(file_gmMessage_proto_rawDesc)))
	})
	return file_gmMessage_proto_rawDescData
}

var file_gmMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gmMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gmMessage_proto_goTypes = []any{
	(GMCommandType)(0),         // 0: pb.GMCommandType
	(GMInvokerType)(0),         // 1: pb.GMInvokerType
	(GMResult)(0),              // 2: pb.GMResult
	(*MessageGmReq)(nil),       // 3: pb.MessageGmReq
	(*MessageGmResp)(nil),      // 4: pb.MessageGmResp
	nil,                        // 5: pb.MessageGmResp.ExtraDataEntry
	(*MailAttachmentItem)(nil), // 6: pb.MailAttachmentItem
}
var file_gmMessage_proto_depIdxs = []int32{
	0, // 0: pb.MessageGmReq.cmdType:type_name -> pb.GMCommandType
	1, // 1: pb.MessageGmReq.invokerType:type_name -> pb.GMInvokerType
	6, // 2: pb.MessageGmReq.items:type_name -> pb.MailAttachmentItem
	2, // 3: pb.MessageGmResp.result:type_name -> pb.GMResult
	5, // 4: pb.MessageGmResp.extraData:type_name -> pb.MessageGmResp.ExtraDataEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gmMessage_proto_init() }
func file_gmMessage_proto_init() {
	if File_gmMessage_proto != nil {
		return
	}
	file_mailMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gmMessage_proto_rawDesc), len(file_gmMessage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gmMessage_proto_goTypes,
		DependencyIndexes: file_gmMessage_proto_depIdxs,
		EnumInfos:         file_gmMessage_proto_enumTypes,
		MessageInfos:      file_gmMessage_proto_msgTypes,
	}.Build()
	File_gmMessage_proto = out.File
	file_gmMessage_proto_goTypes = nil
	file_gmMessage_proto_depIdxs = nil
}
