// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: lotteryMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LotteryResult int32

const (
	LotteryResult_LOTTERY_RESULT_SUCCESS             LotteryResult = 0 // 成功
	LotteryResult_LOTTERY_RESULT_NOT_ENOUGH_CURRENCY LotteryResult = 1 // 抽卡货币不足
	LotteryResult_LOTTERY_RESULT_HERO_BAG_FULL       LotteryResult = 2 // 英雄背包已满
)

// Enum value maps for LotteryResult.
var (
	LotteryResult_name = map[int32]string{
		0: "LOTTERY_RESULT_SUCCESS",
		1: "LOTTERY_RESULT_NOT_ENOUGH_CURRENCY",
		2: "LOTTERY_RESULT_HERO_BAG_FULL",
	}
	LotteryResult_value = map[string]int32{
		"LOTTERY_RESULT_SUCCESS":             0,
		"LOTTERY_RESULT_NOT_ENOUGH_CURRENCY": 1,
		"LOTTERY_RESULT_HERO_BAG_FULL":       2,
	}
)

func (x LotteryResult) Enum() *LotteryResult {
	p := new(LotteryResult)
	*p = x
	return p
}

func (x LotteryResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LotteryResult) Descriptor() protoreflect.EnumDescriptor {
	return file_lotteryMessage_proto_enumTypes[0].Descriptor()
}

func (LotteryResult) Type() protoreflect.EnumType {
	return &file_lotteryMessage_proto_enumTypes[0]
}

func (x LotteryResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LotteryResult.Descriptor instead.
func (LotteryResult) EnumDescriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{0}
}

type GetLotteryHistoryDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotteryId     int32                  `protobuf:"varint,1,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"` // 抽卡池ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotteryHistoryDetailReq) Reset() {
	*x = GetLotteryHistoryDetailReq{}
	mi := &file_lotteryMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryHistoryDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryHistoryDetailReq) ProtoMessage() {}

func (x *GetLotteryHistoryDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryHistoryDetailReq.ProtoReflect.Descriptor instead.
func (*GetLotteryHistoryDetailReq) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{0}
}

func (x *GetLotteryHistoryDetailReq) GetLotteryId() int32 {
	if x != nil {
		return x.LotteryId
	}
	return 0
}

type LotteryHistoryDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`         // 抽卡记录ID
	ItemId        int32                  `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"` // 道具id
	Count         int32                  `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`   // 道具数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotteryHistoryDetail) Reset() {
	*x = LotteryHistoryDetail{}
	mi := &file_lotteryMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryHistoryDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryHistoryDetail) ProtoMessage() {}

func (x *LotteryHistoryDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryHistoryDetail.ProtoReflect.Descriptor instead.
func (*LotteryHistoryDetail) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{1}
}

func (x *LotteryHistoryDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LotteryHistoryDetail) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *LotteryHistoryDetail) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LotteryLuckyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LuckyNum      int32                  `protobuf:"varint,1,opt,name=LuckyNum,proto3" json:"LuckyNum,omitempty"` // 就是折数
	CreateTime    int64                  `protobuf:"varint,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotteryLuckyEvent) Reset() {
	*x = LotteryLuckyEvent{}
	mi := &file_lotteryMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryLuckyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryLuckyEvent) ProtoMessage() {}

func (x *LotteryLuckyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryLuckyEvent.ProtoReflect.Descriptor instead.
func (*LotteryLuckyEvent) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{2}
}

func (x *LotteryLuckyEvent) GetLuckyNum() int32 {
	if x != nil {
		return x.LuckyNum
	}
	return 0
}

func (x *LotteryLuckyEvent) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type GetLotteryHistoryDetailResp struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	HistoryDetails []*LotteryHistoryDetail `protobuf:"bytes,1,rep,name=historyDetails,proto3" json:"historyDetails,omitempty"` // 抽卡记录详情列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLotteryHistoryDetailResp) Reset() {
	*x = GetLotteryHistoryDetailResp{}
	mi := &file_lotteryMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryHistoryDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryHistoryDetailResp) ProtoMessage() {}

func (x *GetLotteryHistoryDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryHistoryDetailResp.ProtoReflect.Descriptor instead.
func (*GetLotteryHistoryDetailResp) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{3}
}

func (x *GetLotteryHistoryDetailResp) GetHistoryDetails() []*LotteryHistoryDetail {
	if x != nil {
		return x.HistoryDetails
	}
	return nil
}

type GetLotteryInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotteryId     int32                  `protobuf:"varint,1,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"` // 抽卡池ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLotteryInfoReq) Reset() {
	*x = GetLotteryInfoReq{}
	mi := &file_lotteryMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryInfoReq) ProtoMessage() {}

func (x *GetLotteryInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryInfoReq.ProtoReflect.Descriptor instead.
func (*GetLotteryInfoReq) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{4}
}

func (x *GetLotteryInfoReq) GetLotteryId() int32 {
	if x != nil {
		return x.LotteryId
	}
	return 0
}

type LotteryInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LotteryCount         int32                  `protobuf:"varint,1,opt,name=lotteryCount,proto3" json:"lotteryCount,omitempty"`                 // 抽卡总次数
	LastBasicGuaranteNum int32                  `protobuf:"varint,2,opt,name=lastBasicGuaranteNum,proto3" json:"lastBasicGuaranteNum,omitempty"` // 上次基础保底计数
	IsDirty              bool                   `protobuf:"varint,3,opt,name=isDirty,proto3" json:"isDirty,omitempty"`                           // 上次是否歪了
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LotteryInfo) Reset() {
	*x = LotteryInfo{}
	mi := &file_lotteryMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryInfo) ProtoMessage() {}

func (x *LotteryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryInfo.ProtoReflect.Descriptor instead.
func (*LotteryInfo) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{5}
}

func (x *LotteryInfo) GetLotteryCount() int32 {
	if x != nil {
		return x.LotteryCount
	}
	return 0
}

func (x *LotteryInfo) GetLastBasicGuaranteNum() int32 {
	if x != nil {
		return x.LastBasicGuaranteNum
	}
	return 0
}

func (x *LotteryInfo) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

type GetLotteryInfoResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LotteryInfo       *LotteryInfo           `protobuf:"bytes,1,opt,name=lotteryInfo,proto3" json:"lotteryInfo,omitempty"`      // 抽卡信息
	FirstDropFree     int32                  `protobuf:"varint,2,opt,name=firstDropFree,proto3" json:"firstDropFree,omitempty"` // 免费次数
	LotteryLuckyEvent *LotteryLuckyEvent     `protobuf:"bytes,3,opt,name=LotteryLuckyEvent,proto3" json:"LotteryLuckyEvent,omitempty"`
	NewLuckyCount     int32                  `protobuf:"varint,4,opt,name=NewLuckyCount,proto3" json:"NewLuckyCount,omitempty"` // 新手抽取次数
	NewIsReward       bool                   `protobuf:"varint,5,opt,name=NewIsReward,proto3" json:"NewIsReward,omitempty"`     // 新手是否奖励
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetLotteryInfoResp) Reset() {
	*x = GetLotteryInfoResp{}
	mi := &file_lotteryMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLotteryInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLotteryInfoResp) ProtoMessage() {}

func (x *GetLotteryInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLotteryInfoResp.ProtoReflect.Descriptor instead.
func (*GetLotteryInfoResp) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{6}
}

func (x *GetLotteryInfoResp) GetLotteryInfo() *LotteryInfo {
	if x != nil {
		return x.LotteryInfo
	}
	return nil
}

func (x *GetLotteryInfoResp) GetFirstDropFree() int32 {
	if x != nil {
		return x.FirstDropFree
	}
	return 0
}

func (x *GetLotteryInfoResp) GetLotteryLuckyEvent() *LotteryLuckyEvent {
	if x != nil {
		return x.LotteryLuckyEvent
	}
	return nil
}

func (x *GetLotteryInfoResp) GetNewLuckyCount() int32 {
	if x != nil {
		return x.NewLuckyCount
	}
	return 0
}

func (x *GetLotteryInfoResp) GetNewIsReward() bool {
	if x != nil {
		return x.NewIsReward
	}
	return false
}

type LotteryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LotteryType   int32                  `protobuf:"varint,1,opt,name=lotteryType,proto3" json:"lotteryType,omitempty"` // 抽卡类型 1：单抽 2：十连抽
	LotteryId     int32                  `protobuf:"varint,2,opt,name=lotteryId,proto3" json:"lotteryId,omitempty"`     // 抽卡池ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LotteryReq) Reset() {
	*x = LotteryReq{}
	mi := &file_lotteryMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryReq) ProtoMessage() {}

func (x *LotteryReq) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryReq.ProtoReflect.Descriptor instead.
func (*LotteryReq) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{7}
}

func (x *LotteryReq) GetLotteryType() int32 {
	if x != nil {
		return x.LotteryType
	}
	return 0
}

func (x *LotteryReq) GetLotteryId() int32 {
	if x != nil {
		return x.LotteryId
	}
	return 0
}

type LotteryResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Result            LotteryResult          `protobuf:"varint,1,opt,name=result,proto3,enum=pb.LotteryResult" json:"result,omitempty"` // 抽卡结果
	InfoList          []*ItemBasicInfo       `protobuf:"bytes,2,rep,name=infoList,proto3" json:"infoList,omitempty"`                    // 抽奖结果 message ItemBasicInfo{int32 itemId = 1;int32 count = 2;}
	LotteryInfo       *LotteryInfo           `protobuf:"bytes,3,opt,name=lotteryInfo,proto3" json:"lotteryInfo,omitempty"`              // 抽卡信息
	FirstDropFree     int32                  `protobuf:"varint,4,opt,name=firstDropFree,proto3" json:"firstDropFree,omitempty"`         // 免费次数
	LotteryLuckyEvent *LotteryLuckyEvent     `protobuf:"bytes,5,opt,name=LotteryLuckyEvent,proto3" json:"LotteryLuckyEvent,omitempty"`
	NewLuckyCount     int32                  `protobuf:"varint,6,opt,name=NewLuckyCount,proto3" json:"NewLuckyCount,omitempty"` // 新手抽取次数
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LotteryResp) Reset() {
	*x = LotteryResp{}
	mi := &file_lotteryMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LotteryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LotteryResp) ProtoMessage() {}

func (x *LotteryResp) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LotteryResp.ProtoReflect.Descriptor instead.
func (*LotteryResp) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{8}
}

func (x *LotteryResp) GetResult() LotteryResult {
	if x != nil {
		return x.Result
	}
	return LotteryResult_LOTTERY_RESULT_SUCCESS
}

func (x *LotteryResp) GetInfoList() []*ItemBasicInfo {
	if x != nil {
		return x.InfoList
	}
	return nil
}

func (x *LotteryResp) GetLotteryInfo() *LotteryInfo {
	if x != nil {
		return x.LotteryInfo
	}
	return nil
}

func (x *LotteryResp) GetFirstDropFree() int32 {
	if x != nil {
		return x.FirstDropFree
	}
	return 0
}

func (x *LotteryResp) GetLotteryLuckyEvent() *LotteryLuckyEvent {
	if x != nil {
		return x.LotteryLuckyEvent
	}
	return nil
}

func (x *LotteryResp) GetNewLuckyCount() int32 {
	if x != nil {
		return x.NewLuckyCount
	}
	return 0
}

type NewLuckyRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLuckyRewardReq) Reset() {
	*x = NewLuckyRewardReq{}
	mi := &file_lotteryMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLuckyRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLuckyRewardReq) ProtoMessage() {}

func (x *NewLuckyRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLuckyRewardReq.ProtoReflect.Descriptor instead.
func (*NewLuckyRewardReq) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{9}
}

func (x *NewLuckyRewardReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type NewLuckyRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLuckyRewardResp) Reset() {
	*x = NewLuckyRewardResp{}
	mi := &file_lotteryMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLuckyRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLuckyRewardResp) ProtoMessage() {}

func (x *NewLuckyRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_lotteryMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLuckyRewardResp.ProtoReflect.Descriptor instead.
func (*NewLuckyRewardResp) Descriptor() ([]byte, []int) {
	return file_lotteryMessage_proto_rawDescGZIP(), []int{10}
}

var File_lotteryMessage_proto protoreflect.FileDescriptor

const file_lotteryMessage_proto_rawDesc = "" +
	"\n" +
	"\x14lotteryMessage.proto\x12\x02pb\x1a\x13commonMessage.proto\":\n" +
	"\x1aGetLotteryHistoryDetailReq\x12\x1c\n" +
	"\tlotteryId\x18\x01 \x01(\x05R\tlotteryId\"T\n" +
	"\x14LotteryHistoryDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05Count\x18\x03 \x01(\x05R\x05Count\"O\n" +
	"\x11LotteryLuckyEvent\x12\x1a\n" +
	"\bLuckyNum\x18\x01 \x01(\x05R\bLuckyNum\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\x02 \x01(\x03R\n" +
	"CreateTime\"_\n" +
	"\x1bGetLotteryHistoryDetailResp\x12@\n" +
	"\x0ehistoryDetails\x18\x01 \x03(\v2\x18.pb.LotteryHistoryDetailR\x0ehistoryDetails\"1\n" +
	"\x11GetLotteryInfoReq\x12\x1c\n" +
	"\tlotteryId\x18\x01 \x01(\x05R\tlotteryId\"\x7f\n" +
	"\vLotteryInfo\x12\"\n" +
	"\flotteryCount\x18\x01 \x01(\x05R\flotteryCount\x122\n" +
	"\x14lastBasicGuaranteNum\x18\x02 \x01(\x05R\x14lastBasicGuaranteNum\x12\x18\n" +
	"\aisDirty\x18\x03 \x01(\bR\aisDirty\"\xfa\x01\n" +
	"\x12GetLotteryInfoResp\x121\n" +
	"\vlotteryInfo\x18\x01 \x01(\v2\x0f.pb.LotteryInfoR\vlotteryInfo\x12$\n" +
	"\rfirstDropFree\x18\x02 \x01(\x05R\rfirstDropFree\x12C\n" +
	"\x11LotteryLuckyEvent\x18\x03 \x01(\v2\x15.pb.LotteryLuckyEventR\x11LotteryLuckyEvent\x12$\n" +
	"\rNewLuckyCount\x18\x04 \x01(\x05R\rNewLuckyCount\x12 \n" +
	"\vNewIsReward\x18\x05 \x01(\bR\vNewIsReward\"L\n" +
	"\n" +
	"LotteryReq\x12 \n" +
	"\vlotteryType\x18\x01 \x01(\x05R\vlotteryType\x12\x1c\n" +
	"\tlotteryId\x18\x02 \x01(\x05R\tlotteryId\"\xab\x02\n" +
	"\vLotteryResp\x12)\n" +
	"\x06result\x18\x01 \x01(\x0e2\x11.pb.LotteryResultR\x06result\x12-\n" +
	"\binfoList\x18\x02 \x03(\v2\x11.pb.ItemBasicInfoR\binfoList\x121\n" +
	"\vlotteryInfo\x18\x03 \x01(\v2\x0f.pb.LotteryInfoR\vlotteryInfo\x12$\n" +
	"\rfirstDropFree\x18\x04 \x01(\x05R\rfirstDropFree\x12C\n" +
	"\x11LotteryLuckyEvent\x18\x05 \x01(\v2\x15.pb.LotteryLuckyEventR\x11LotteryLuckyEvent\x12$\n" +
	"\rNewLuckyCount\x18\x06 \x01(\x05R\rNewLuckyCount\"+\n" +
	"\x11NewLuckyRewardReq\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\"\x14\n" +
	"\x12NewLuckyRewardResp*u\n" +
	"\rLotteryResult\x12\x1a\n" +
	"\x16LOTTERY_RESULT_SUCCESS\x10\x00\x12&\n" +
	"\"LOTTERY_RESULT_NOT_ENOUGH_CURRENCY\x10\x01\x12 \n" +
	"\x1cLOTTERY_RESULT_HERO_BAG_FULL\x10\x02B\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_lotteryMessage_proto_rawDescOnce sync.Once
	file_lotteryMessage_proto_rawDescData []byte
)

func file_lotteryMessage_proto_rawDescGZIP() []byte {
	file_lotteryMessage_proto_rawDescOnce.Do(func() {
		file_lotteryMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lotteryMessage_proto_rawDesc), len(file_lotteryMessage_proto_rawDesc)))
	})
	return file_lotteryMessage_proto_rawDescData
}

var file_lotteryMessage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lotteryMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lotteryMessage_proto_goTypes = []any{
	(LotteryResult)(0),                  // 0: pb.LotteryResult
	(*GetLotteryHistoryDetailReq)(nil),  // 1: pb.GetLotteryHistoryDetailReq
	(*LotteryHistoryDetail)(nil),        // 2: pb.LotteryHistoryDetail
	(*LotteryLuckyEvent)(nil),           // 3: pb.LotteryLuckyEvent
	(*GetLotteryHistoryDetailResp)(nil), // 4: pb.GetLotteryHistoryDetailResp
	(*GetLotteryInfoReq)(nil),           // 5: pb.GetLotteryInfoReq
	(*LotteryInfo)(nil),                 // 6: pb.LotteryInfo
	(*GetLotteryInfoResp)(nil),          // 7: pb.GetLotteryInfoResp
	(*LotteryReq)(nil),                  // 8: pb.LotteryReq
	(*LotteryResp)(nil),                 // 9: pb.LotteryResp
	(*NewLuckyRewardReq)(nil),           // 10: pb.NewLuckyRewardReq
	(*NewLuckyRewardResp)(nil),          // 11: pb.NewLuckyRewardResp
	(*ItemBasicInfo)(nil),               // 12: pb.ItemBasicInfo
}
var file_lotteryMessage_proto_depIdxs = []int32{
	2,  // 0: pb.GetLotteryHistoryDetailResp.historyDetails:type_name -> pb.LotteryHistoryDetail
	6,  // 1: pb.GetLotteryInfoResp.lotteryInfo:type_name -> pb.LotteryInfo
	3,  // 2: pb.GetLotteryInfoResp.LotteryLuckyEvent:type_name -> pb.LotteryLuckyEvent
	0,  // 3: pb.LotteryResp.result:type_name -> pb.LotteryResult
	12, // 4: pb.LotteryResp.infoList:type_name -> pb.ItemBasicInfo
	6,  // 5: pb.LotteryResp.lotteryInfo:type_name -> pb.LotteryInfo
	3,  // 6: pb.LotteryResp.LotteryLuckyEvent:type_name -> pb.LotteryLuckyEvent
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_lotteryMessage_proto_init() }
func file_lotteryMessage_proto_init() {
	if File_lotteryMessage_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lotteryMessage_proto_rawDesc), len(file_lotteryMessage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lotteryMessage_proto_goTypes,
		DependencyIndexes: file_lotteryMessage_proto_depIdxs,
		EnumInfos:         file_lotteryMessage_proto_enumTypes,
		MessageInfos:      file_lotteryMessage_proto_msgTypes,
	}.Build()
	File_lotteryMessage_proto = out.File
	file_lotteryMessage_proto_goTypes = nil
	file_lotteryMessage_proto_depIdxs = nil
}
