// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: pass.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通行证奖励信息
type PassRewardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`               // 等级
	PointsPer     int32                  `protobuf:"varint,2,opt,name=pointsPer,proto3" json:"pointsPer,omitempty"`       // 每级所需积分
	ReceivedFree  bool                   `protobuf:"varint,3,opt,name=receivedFree,proto3" json:"receivedFree,omitempty"` // 是否已领取免费档位
	ReceivedVip1  bool                   `protobuf:"varint,4,opt,name=receivedVip1,proto3" json:"receivedVip1,omitempty"` // 是否已领取付费档位1
	ReceivedVip2  bool                   `protobuf:"varint,5,opt,name=receivedVip2,proto3" json:"receivedVip2,omitempty"` // 是否已领取付费档位2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassRewardInfo) Reset() {
	*x = PassRewardInfo{}
	mi := &file_pass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRewardInfo) ProtoMessage() {}

func (x *PassRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRewardInfo.ProtoReflect.Descriptor instead.
func (*PassRewardInfo) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{0}
}

func (x *PassRewardInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PassRewardInfo) GetPointsPer() int32 {
	if x != nil {
		return x.PointsPer
	}
	return 0
}

func (x *PassRewardInfo) GetReceivedFree() bool {
	if x != nil {
		return x.ReceivedFree
	}
	return false
}

func (x *PassRewardInfo) GetReceivedVip1() bool {
	if x != nil {
		return x.ReceivedVip1
	}
	return false
}

func (x *PassRewardInfo) GetReceivedVip2() bool {
	if x != nil {
		return x.ReceivedVip2
	}
	return false
}

// 通行证信息
type PassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"`             // 通行证ID
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`         // 当前进度
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`               // 当前等级
	VipLevel      int32                  `protobuf:"varint,4,opt,name=vipLevel,proto3" json:"vipLevel,omitempty"`         // VIP等级（位运算）：0=免费, 1=档位1, 2=档位2, 3=档位1+2, 4=档位3, ...
	Rewards       []*PassRewardInfo      `protobuf:"bytes,5,rep,name=rewards,proto3" json:"rewards,omitempty"`            // 奖励列表
	LoopProgress  int32                  `protobuf:"varint,6,opt,name=loopProgress,proto3" json:"loopProgress,omitempty"` // 循环积分（满级后多出的积分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassInfo) Reset() {
	*x = PassInfo{}
	mi := &file_pass_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassInfo) ProtoMessage() {}

func (x *PassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassInfo.ProtoReflect.Descriptor instead.
func (*PassInfo) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{1}
}

func (x *PassInfo) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

func (x *PassInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PassInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PassInfo) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PassInfo) GetRewards() []*PassRewardInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *PassInfo) GetLoopProgress() int32 {
	if x != nil {
		return x.LoopProgress
	}
	return 0
}

// 通行证奖励选项（当drop有多个道具时）
type PassRewardOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"` // 道具ID
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassRewardOption) Reset() {
	*x = PassRewardOption{}
	mi := &file_pass_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassRewardOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRewardOption) ProtoMessage() {}

func (x *PassRewardOption) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRewardOption.ProtoReflect.Descriptor instead.
func (*PassRewardOption) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{2}
}

func (x *PassRewardOption) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PassRewardOption) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取通行证信息请求
type GetPassInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"` // 通行证ID（0表示获取所有）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassInfoReq) Reset() {
	*x = GetPassInfoReq{}
	mi := &file_pass_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassInfoReq) ProtoMessage() {}

func (x *GetPassInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassInfoReq.ProtoReflect.Descriptor instead.
func (*GetPassInfoReq) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{3}
}

func (x *GetPassInfoReq) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

// 获取通行证信息响应
type GetPassInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassList      []*PassInfo            `protobuf:"bytes,1,rep,name=passList,proto3" json:"passList,omitempty"` // 通行证列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassInfoResp) Reset() {
	*x = GetPassInfoResp{}
	mi := &file_pass_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassInfoResp) ProtoMessage() {}

func (x *GetPassInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassInfoResp.ProtoReflect.Descriptor instead.
func (*GetPassInfoResp) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{4}
}

func (x *GetPassInfoResp) GetPassList() []*PassInfo {
	if x != nil {
		return x.PassList
	}
	return nil
}

// 获取通行证奖励选项请求（当drop有多个道具时）TODO del
type GetPassRewardOptionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"`           // 通行证ID
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`             // 等级
	RewardLevel   int32                  `protobuf:"varint,3,opt,name=rewardLevel,proto3" json:"rewardLevel,omitempty"` // 奖励档位：0=免费, 1=档位1, 2=档位2, 3=档位3, ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassRewardOptionsReq) Reset() {
	*x = GetPassRewardOptionsReq{}
	mi := &file_pass_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassRewardOptionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassRewardOptionsReq) ProtoMessage() {}

func (x *GetPassRewardOptionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassRewardOptionsReq.ProtoReflect.Descriptor instead.
func (*GetPassRewardOptionsReq) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{5}
}

func (x *GetPassRewardOptionsReq) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

func (x *GetPassRewardOptionsReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetPassRewardOptionsReq) GetRewardLevel() int32 {
	if x != nil {
		return x.RewardLevel
	}
	return 0
}

// 获取通行证奖励选项响应
type GetPassRewardOptionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*PassRewardOption    `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"` // 奖励选项列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassRewardOptionsResp) Reset() {
	*x = GetPassRewardOptionsResp{}
	mi := &file_pass_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassRewardOptionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassRewardOptionsResp) ProtoMessage() {}

func (x *GetPassRewardOptionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassRewardOptionsResp.ProtoReflect.Descriptor instead.
func (*GetPassRewardOptionsResp) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{6}
}

func (x *GetPassRewardOptionsResp) GetOptions() []*PassRewardOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// 购买通行证积分请求
type BuyPassProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"` // 通行证ID
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"` // 要购买的积分数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyPassProgressReq) Reset() {
	*x = BuyPassProgressReq{}
	mi := &file_pass_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyPassProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyPassProgressReq) ProtoMessage() {}

func (x *BuyPassProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyPassProgressReq.ProtoReflect.Descriptor instead.
func (*BuyPassProgressReq) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{7}
}

func (x *BuyPassProgressReq) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

func (x *BuyPassProgressReq) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// 购买通行证积分响应
type BuyPassProgressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"` // 当前总进度
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`       // 当前等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyPassProgressResp) Reset() {
	*x = BuyPassProgressResp{}
	mi := &file_pass_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyPassProgressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyPassProgressResp) ProtoMessage() {}

func (x *BuyPassProgressResp) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyPassProgressResp.ProtoReflect.Descriptor instead.
func (*BuyPassProgressResp) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{8}
}

func (x *BuyPassProgressResp) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *BuyPassProgressResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 领取循环奖励请求
type ClaimLoopRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"` // 通行证ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimLoopRewardReq) Reset() {
	*x = ClaimLoopRewardReq{}
	mi := &file_pass_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimLoopRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLoopRewardReq) ProtoMessage() {}

func (x *ClaimLoopRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLoopRewardReq.ProtoReflect.Descriptor instead.
func (*ClaimLoopRewardReq) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimLoopRewardReq) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

// 领取循环奖励响应
type ClaimLoopRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`            // 奖励道具列表
	LoopProgress  int32                  `protobuf:"varint,2,opt,name=loopProgress,proto3" json:"loopProgress,omitempty"` // 剩余循环积分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimLoopRewardResp) Reset() {
	*x = ClaimLoopRewardResp{}
	mi := &file_pass_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimLoopRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLoopRewardResp) ProtoMessage() {}

func (x *ClaimLoopRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLoopRewardResp.ProtoReflect.Descriptor instead.
func (*ClaimLoopRewardResp) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimLoopRewardResp) GetRewards() []*ItemBasicInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *ClaimLoopRewardResp) GetLoopProgress() int32 {
	if x != nil {
		return x.LoopProgress
	}
	return 0
}

// 奖励选择信息（用于一次性领取所有奖励）
type PassRewardChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`               // 等级
	RewardLevel   int32                  `protobuf:"varint,2,opt,name=rewardLevel,proto3" json:"rewardLevel,omitempty"`   // 奖励档位：0=免费, 1=档位1, 2=档位2, 3=档位3, ...
	ChosenDropId  int32                  `protobuf:"varint,3,opt,name=chosenDropId,proto3" json:"chosenDropId,omitempty"` // 选择的掉落ID（当dropId2或dropId3是数组时必填）
	ChosenItemId  int32                  `protobuf:"varint,4,opt,name=chosenItemId,proto3" json:"chosenItemId,omitempty"` // 选择的道具ID（当drop有多个道具时必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassRewardChoice) Reset() {
	*x = PassRewardChoice{}
	mi := &file_pass_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassRewardChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassRewardChoice) ProtoMessage() {}

func (x *PassRewardChoice) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassRewardChoice.ProtoReflect.Descriptor instead.
func (*PassRewardChoice) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{11}
}

func (x *PassRewardChoice) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PassRewardChoice) GetRewardLevel() int32 {
	if x != nil {
		return x.RewardLevel
	}
	return 0
}

func (x *PassRewardChoice) GetChosenDropId() int32 {
	if x != nil {
		return x.ChosenDropId
	}
	return 0
}

func (x *PassRewardChoice) GetChosenItemId() int32 {
	if x != nil {
		return x.ChosenItemId
	}
	return 0
}

// 一次性领取所有可领取奖励请求
type ClaimAllPassRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassId        int32                  `protobuf:"varint,1,opt,name=passId,proto3" json:"passId,omitempty"`  // 通行证ID
	Choices       []*PassRewardChoice    `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"` // 奖励选择信息（仅当奖励需要选择时提供）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimAllPassRewardReq) Reset() {
	*x = ClaimAllPassRewardReq{}
	mi := &file_pass_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAllPassRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAllPassRewardReq) ProtoMessage() {}

func (x *ClaimAllPassRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAllPassRewardReq.ProtoReflect.Descriptor instead.
func (*ClaimAllPassRewardReq) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{12}
}

func (x *ClaimAllPassRewardReq) GetPassId() int32 {
	if x != nil {
		return x.PassId
	}
	return 0
}

func (x *ClaimAllPassRewardReq) GetChoices() []*PassRewardChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// 一次性领取所有可领取奖励响应
type ClaimAllPassRewardResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rewards         []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`                  // 奖励道具列表
	MaxClaimedLevel int32                  `protobuf:"varint,2,opt,name=maxClaimedLevel,proto3" json:"maxClaimedLevel,omitempty"` // 最大领取等级
	Pass            *PassInfo              `protobuf:"bytes,3,opt,name=pass,proto3" json:"pass,omitempty"`                        // 通行证 Info
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClaimAllPassRewardResp) Reset() {
	*x = ClaimAllPassRewardResp{}
	mi := &file_pass_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimAllPassRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimAllPassRewardResp) ProtoMessage() {}

func (x *ClaimAllPassRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_pass_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimAllPassRewardResp.ProtoReflect.Descriptor instead.
func (*ClaimAllPassRewardResp) Descriptor() ([]byte, []int) {
	return file_pass_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimAllPassRewardResp) GetRewards() []*ItemBasicInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *ClaimAllPassRewardResp) GetMaxClaimedLevel() int32 {
	if x != nil {
		return x.MaxClaimedLevel
	}
	return 0
}

func (x *ClaimAllPassRewardResp) GetPass() *PassInfo {
	if x != nil {
		return x.Pass
	}
	return nil
}

var File_pass_proto protoreflect.FileDescriptor

const file_pass_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pass.proto\x12\x02pb\x1a\x13commonMessage.proto\"\xb0\x01\n" +
	"\x0ePassRewardInfo\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1c\n" +
	"\tpointsPer\x18\x02 \x01(\x05R\tpointsPer\x12\"\n" +
	"\freceivedFree\x18\x03 \x01(\bR\freceivedFree\x12\"\n" +
	"\freceivedVip1\x18\x04 \x01(\bR\freceivedVip1\x12\"\n" +
	"\freceivedVip2\x18\x05 \x01(\bR\freceivedVip2\"\xc2\x01\n" +
	"\bPassInfo\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1a\n" +
	"\bvipLevel\x18\x04 \x01(\x05R\bvipLevel\x12,\n" +
	"\arewards\x18\x05 \x03(\v2\x12.pb.PassRewardInfoR\arewards\x12\"\n" +
	"\floopProgress\x18\x06 \x01(\x05R\floopProgress\"@\n" +
	"\x10PassRewardOption\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"(\n" +
	"\x0eGetPassInfoReq\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\";\n" +
	"\x0fGetPassInfoResp\x12(\n" +
	"\bpassList\x18\x01 \x03(\v2\f.pb.PassInfoR\bpassList\"i\n" +
	"\x17GetPassRewardOptionsReq\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12 \n" +
	"\vrewardLevel\x18\x03 \x01(\x05R\vrewardLevel\"J\n" +
	"\x18GetPassRewardOptionsResp\x12.\n" +
	"\aoptions\x18\x01 \x03(\v2\x14.pb.PassRewardOptionR\aoptions\"D\n" +
	"\x12BuyPassProgressReq\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\"G\n" +
	"\x13BuyPassProgressResp\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\",\n" +
	"\x12ClaimLoopRewardReq\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\"f\n" +
	"\x13ClaimLoopRewardResp\x12+\n" +
	"\arewards\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\arewards\x12\"\n" +
	"\floopProgress\x18\x02 \x01(\x05R\floopProgress\"\x92\x01\n" +
	"\x10PassRewardChoice\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12 \n" +
	"\vrewardLevel\x18\x02 \x01(\x05R\vrewardLevel\x12\"\n" +
	"\fchosenDropId\x18\x03 \x01(\x05R\fchosenDropId\x12\"\n" +
	"\fchosenItemId\x18\x04 \x01(\x05R\fchosenItemId\"_\n" +
	"\x15ClaimAllPassRewardReq\x12\x16\n" +
	"\x06passId\x18\x01 \x01(\x05R\x06passId\x12.\n" +
	"\achoices\x18\x02 \x03(\v2\x14.pb.PassRewardChoiceR\achoices\"\x91\x01\n" +
	"\x16ClaimAllPassRewardResp\x12+\n" +
	"\arewards\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\arewards\x12(\n" +
	"\x0fmaxClaimedLevel\x18\x02 \x01(\x05R\x0fmaxClaimedLevel\x12 \n" +
	"\x04pass\x18\x03 \x01(\v2\f.pb.PassInfoR\x04passB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_pass_proto_rawDescOnce sync.Once
	file_pass_proto_rawDescData []byte
)

func file_pass_proto_rawDescGZIP() []byte {
	file_pass_proto_rawDescOnce.Do(func() {
		file_pass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pass_proto_rawDesc), len(file_pass_proto_rawDesc)))
	})
	return file_pass_proto_rawDescData
}

var file_pass_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pass_proto_goTypes = []any{
	(*PassRewardInfo)(nil),           // 0: pb.PassRewardInfo
	(*PassInfo)(nil),                 // 1: pb.PassInfo
	(*PassRewardOption)(nil),         // 2: pb.PassRewardOption
	(*GetPassInfoReq)(nil),           // 3: pb.GetPassInfoReq
	(*GetPassInfoResp)(nil),          // 4: pb.GetPassInfoResp
	(*GetPassRewardOptionsReq)(nil),  // 5: pb.GetPassRewardOptionsReq
	(*GetPassRewardOptionsResp)(nil), // 6: pb.GetPassRewardOptionsResp
	(*BuyPassProgressReq)(nil),       // 7: pb.BuyPassProgressReq
	(*BuyPassProgressResp)(nil),      // 8: pb.BuyPassProgressResp
	(*ClaimLoopRewardReq)(nil),       // 9: pb.ClaimLoopRewardReq
	(*ClaimLoopRewardResp)(nil),      // 10: pb.ClaimLoopRewardResp
	(*PassRewardChoice)(nil),         // 11: pb.PassRewardChoice
	(*ClaimAllPassRewardReq)(nil),    // 12: pb.ClaimAllPassRewardReq
	(*ClaimAllPassRewardResp)(nil),   // 13: pb.ClaimAllPassRewardResp
	(*ItemBasicInfo)(nil),            // 14: pb.ItemBasicInfo
}
var file_pass_proto_depIdxs = []int32{
	0,  // 0: pb.PassInfo.rewards:type_name -> pb.PassRewardInfo
	1,  // 1: pb.GetPassInfoResp.passList:type_name -> pb.PassInfo
	2,  // 2: pb.GetPassRewardOptionsResp.options:type_name -> pb.PassRewardOption
	14, // 3: pb.ClaimLoopRewardResp.rewards:type_name -> pb.ItemBasicInfo
	11, // 4: pb.ClaimAllPassRewardReq.choices:type_name -> pb.PassRewardChoice
	14, // 5: pb.ClaimAllPassRewardResp.rewards:type_name -> pb.ItemBasicInfo
	1,  // 6: pb.ClaimAllPassRewardResp.pass:type_name -> pb.PassInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pass_proto_init() }
func file_pass_proto_init() {
	if File_pass_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pass_proto_rawDesc), len(file_pass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pass_proto_goTypes,
		DependencyIndexes: file_pass_proto_depIdxs,
		MessageInfos:      file_pass_proto_msgTypes,
	}.Build()
	File_pass_proto = out.File
	file_pass_proto_goTypes = nil
	file_pass_proto_depIdxs = nil
}
