// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: petMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 宠物详情信息
type PetDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`                                                                                // 宠物唯一ID
	PetId         int32                  `protobuf:"varint,2,opt,name=petId,proto3" json:"petId,omitempty"`                                                                                      // 配表ID
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                                      // 等级
	Star          int32                  `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`                                                                                        // 星级（从0开始）
	HeroOwnId     int64                  `protobuf:"varint,5,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`                                                                              // 绑定英雄，0=在背包
	Attributes    map[int32]int64        `protobuf:"bytes,6,rep,name=Attributes,proto3" json:"Attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 宠物属性列表
	PassiveSkills []int32                `protobuf:"varint,7,rep,packed,name=passiveSkills,proto3" json:"passiveSkills,omitempty"`                                                               // 被动技能列表（没有则空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailInfo) Reset() {
	*x = PetDetailInfo{}
	mi := &file_petMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailInfo) ProtoMessage() {}

func (x *PetDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailInfo.ProtoReflect.Descriptor instead.
func (*PetDetailInfo) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{0}
}

func (x *PetDetailInfo) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetDetailInfo) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetDetailInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetDetailInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *PetDetailInfo) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *PetDetailInfo) GetAttributes() map[int32]int64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PetDetailInfo) GetPassiveSkills() []int32 {
	if x != nil {
		return x.PassiveSkills
	}
	return nil
}

// ====== 获取宠物详情 ======
type PetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailReq) Reset() {
	*x = PetDetailReq{}
	mi := &file_petMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailReq) ProtoMessage() {}

func (x *PetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailReq.ProtoReflect.Descriptor instead.
func (*PetDetailReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PetDetailReq) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

type PetDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetDetailInfo         `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailResp) Reset() {
	*x = PetDetailResp{}
	mi := &file_petMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailResp) ProtoMessage() {}

func (x *PetDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailResp.ProtoReflect.Descriptor instead.
func (*PetDetailResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{2}
}

func (x *PetDetailResp) GetPet() *PetDetailInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetEquipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	HeroOwnId     int64                  `protobuf:"varint,2,opt,name=heroOwnId,proto3" json:"heroOwnId,omitempty"`         // 目标英雄；卸下时可传0
	OperationType int32                  `protobuf:"varint,3,opt,name=operationType,proto3" json:"operationType,omitempty"` // 0=穿戴；1=卸下
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetEquipReq) Reset() {
	*x = PetEquipReq{}
	mi := &file_petMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetEquipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetEquipReq) ProtoMessage() {}

func (x *PetEquipReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetEquipReq.ProtoReflect.Descriptor instead.
func (*PetEquipReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{3}
}

func (x *PetEquipReq) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetEquipReq) GetHeroOwnId() int64 {
	if x != nil {
		return x.HeroOwnId
	}
	return 0
}

func (x *PetEquipReq) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

type PetEquipResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetDetailInfo         `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetEquipResp) Reset() {
	*x = PetEquipResp{}
	mi := &file_petMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetEquipResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetEquipResp) ProtoMessage() {}

func (x *PetEquipResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetEquipResp.ProtoReflect.Descriptor instead.
func (*PetEquipResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{4}
}

func (x *PetEquipResp) GetPet() *PetDetailInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetLevelUpReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	// 1=+1级 2=+5级 3=+10级
	LevelUpType   int32 `protobuf:"varint,2,opt,name=levelUpType,proto3" json:"levelUpType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetLevelUpReq) Reset() {
	*x = PetLevelUpReq{}
	mi := &file_petMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetLevelUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetLevelUpReq) ProtoMessage() {}

func (x *PetLevelUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetLevelUpReq.ProtoReflect.Descriptor instead.
func (*PetLevelUpReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{5}
}

func (x *PetLevelUpReq) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetLevelUpReq) GetLevelUpType() int32 {
	if x != nil {
		return x.LevelUpType
	}
	return 0
}

type PetLevelUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetDetailInfo         `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetLevelUpResp) Reset() {
	*x = PetLevelUpResp{}
	mi := &file_petMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetLevelUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetLevelUpResp) ProtoMessage() {}

func (x *PetLevelUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetLevelUpResp.ProtoReflect.Descriptor instead.
func (*PetLevelUpResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{6}
}

func (x *PetLevelUpResp) GetPet() *PetDetailInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetStarUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	PetOwnIds     []int64                `protobuf:"varint,2,rep,packed,name=petOwnIds,proto3" json:"petOwnIds,omitempty"` // 材料宠物ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStarUpReq) Reset() {
	*x = PetStarUpReq{}
	mi := &file_petMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStarUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStarUpReq) ProtoMessage() {}

func (x *PetStarUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStarUpReq.ProtoReflect.Descriptor instead.
func (*PetStarUpReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{7}
}

func (x *PetStarUpReq) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

func (x *PetStarUpReq) GetPetOwnIds() []int64 {
	if x != nil {
		return x.PetOwnIds
	}
	return nil
}

type PetStarUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetDetailInfo         `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStarUpResp) Reset() {
	*x = PetStarUpResp{}
	mi := &file_petMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStarUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStarUpResp) ProtoMessage() {}

func (x *PetStarUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStarUpResp.ProtoReflect.Descriptor instead.
func (*PetStarUpResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{8}
}

func (x *PetStarUpResp) GetPet() *PetDetailInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetRebirthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnId      int64                  `protobuf:"varint,1,opt,name=petOwnId,proto3" json:"petOwnId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRebirthReq) Reset() {
	*x = PetRebirthReq{}
	mi := &file_petMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRebirthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRebirthReq) ProtoMessage() {}

func (x *PetRebirthReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRebirthReq.ProtoReflect.Descriptor instead.
func (*PetRebirthReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{9}
}

func (x *PetRebirthReq) GetPetOwnId() int64 {
	if x != nil {
		return x.PetOwnId
	}
	return 0
}

type PetRebirthResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *PetDetailInfo         `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRebirthResp) Reset() {
	*x = PetRebirthResp{}
	mi := &file_petMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRebirthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRebirthResp) ProtoMessage() {}

func (x *PetRebirthResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRebirthResp.ProtoReflect.Descriptor instead.
func (*PetRebirthResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{10}
}

func (x *PetRebirthResp) GetPet() *PetDetailInfo {
	if x != nil {
		return x.Pet
	}
	return nil
}

type PetDecomposeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetOwnIds     []int64                `protobuf:"varint,1,rep,packed,name=petOwnIds,proto3" json:"petOwnIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDecomposeReq) Reset() {
	*x = PetDecomposeReq{}
	mi := &file_petMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDecomposeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDecomposeReq) ProtoMessage() {}

func (x *PetDecomposeReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDecomposeReq.ProtoReflect.Descriptor instead.
func (*PetDecomposeReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{11}
}

func (x *PetDecomposeReq) GetPetOwnIds() []int64 {
	if x != nil {
		return x.PetOwnIds
	}
	return nil
}

type PetDecomposeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"` // 1=成功 0=失败
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDecomposeResp) Reset() {
	*x = PetDecomposeResp{}
	mi := &file_petMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDecomposeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDecomposeResp) ProtoMessage() {}

func (x *PetDecomposeResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDecomposeResp.ProtoReflect.Descriptor instead.
func (*PetDecomposeResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{12}
}

func (x *PetDecomposeResp) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type PetMaxLevelMaxStarDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         int32                  `protobuf:"varint,1,opt,name=petId,proto3" json:"petId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetMaxLevelMaxStarDetailReq) Reset() {
	*x = PetMaxLevelMaxStarDetailReq{}
	mi := &file_petMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetMaxLevelMaxStarDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetMaxLevelMaxStarDetailReq) ProtoMessage() {}

func (x *PetMaxLevelMaxStarDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetMaxLevelMaxStarDetailReq.ProtoReflect.Descriptor instead.
func (*PetMaxLevelMaxStarDetailReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{13}
}

func (x *PetMaxLevelMaxStarDetailReq) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type PetMaxLevelMaxStarDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetInfo       *PetDetailInfo         `protobuf:"bytes,1,opt,name=petInfo,proto3" json:"petInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetMaxLevelMaxStarDetailResp) Reset() {
	*x = PetMaxLevelMaxStarDetailResp{}
	mi := &file_petMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetMaxLevelMaxStarDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetMaxLevelMaxStarDetailResp) ProtoMessage() {}

func (x *PetMaxLevelMaxStarDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetMaxLevelMaxStarDetailResp.ProtoReflect.Descriptor instead.
func (*PetMaxLevelMaxStarDetailResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{14}
}

func (x *PetMaxLevelMaxStarDetailResp) GetPetInfo() *PetDetailInfo {
	if x != nil {
		return x.PetInfo
	}
	return nil
}

type PetAffinityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffinityId    int32                  `protobuf:"varint,1,opt,name=affinityId,proto3" json:"affinityId,omitempty"`                                                                            // PetAffinityCfg.Id
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`                                                                                      // 0=未激活；>=1 表示已激活档位
	Attributes    map[int32]int64        `protobuf:"bytes,3,rep,name=Attributes,proto3" json:"Attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 宠物缘分属性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAffinityInfo) Reset() {
	*x = PetAffinityInfo{}
	mi := &file_petMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAffinityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAffinityInfo) ProtoMessage() {}

func (x *PetAffinityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAffinityInfo.ProtoReflect.Descriptor instead.
func (*PetAffinityInfo) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{15}
}

func (x *PetAffinityInfo) GetAffinityId() int32 {
	if x != nil {
		return x.AffinityId
	}
	return 0
}

func (x *PetAffinityInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PetAffinityInfo) GetAttributes() map[int32]int64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type PetStarBookEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetId         int32                  `protobuf:"varint,1,opt,name=petId,proto3" json:"petId,omitempty"`
	MaxStar       int32                  `protobuf:"varint,2,opt,name=maxStar,proto3" json:"maxStar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetStarBookEntry) Reset() {
	*x = PetStarBookEntry{}
	mi := &file_petMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetStarBookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetStarBookEntry) ProtoMessage() {}

func (x *PetStarBookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetStarBookEntry.ProtoReflect.Descriptor instead.
func (*PetStarBookEntry) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{16}
}

func (x *PetStarBookEntry) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetStarBookEntry) GetMaxStar() int32 {
	if x != nil {
		return x.MaxStar
	}
	return 0
}

type PushPetStarBookChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       []*PetStarBookEntry    `protobuf:"bytes,1,rep,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPetStarBookChange) Reset() {
	*x = PushPetStarBookChange{}
	mi := &file_petMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPetStarBookChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPetStarBookChange) ProtoMessage() {}

func (x *PushPetStarBookChange) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPetStarBookChange.ProtoReflect.Descriptor instead.
func (*PushPetStarBookChange) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{17}
}

func (x *PushPetStarBookChange) GetChanged() []*PetStarBookEntry {
	if x != nil {
		return x.Changed
	}
	return nil
}

type PetAffinityLevelUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffinityId    int32                  `protobuf:"varint,1,opt,name=affinityId,proto3" json:"affinityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAffinityLevelUpReq) Reset() {
	*x = PetAffinityLevelUpReq{}
	mi := &file_petMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAffinityLevelUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAffinityLevelUpReq) ProtoMessage() {}

func (x *PetAffinityLevelUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAffinityLevelUpReq.ProtoReflect.Descriptor instead.
func (*PetAffinityLevelUpReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{18}
}

func (x *PetAffinityLevelUpReq) GetAffinityId() int32 {
	if x != nil {
		return x.AffinityId
	}
	return 0
}

type PetAffinityLevelUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PetAffinityInfo       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAffinityLevelUpResp) Reset() {
	*x = PetAffinityLevelUpResp{}
	mi := &file_petMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAffinityLevelUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAffinityLevelUpResp) ProtoMessage() {}

func (x *PetAffinityLevelUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAffinityLevelUpResp.ProtoReflect.Descriptor instead.
func (*PetAffinityLevelUpResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{19}
}

func (x *PetAffinityLevelUpResp) GetInfo() *PetAffinityInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PetAffinityListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAffinityListReq) Reset() {
	*x = PetAffinityListReq{}
	mi := &file_petMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAffinityListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAffinityListReq) ProtoMessage() {}

func (x *PetAffinityListReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAffinityListReq.ProtoReflect.Descriptor instead.
func (*PetAffinityListReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{20}
}

type PetAffinityListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*PetAffinityInfo     `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetAffinityListResp) Reset() {
	*x = PetAffinityListResp{}
	mi := &file_petMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetAffinityListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetAffinityListResp) ProtoMessage() {}

func (x *PetAffinityListResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetAffinityListResp.ProtoReflect.Descriptor instead.
func (*PetAffinityListResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{21}
}

func (x *PetAffinityListResp) GetInfo() []*PetAffinityInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PushPetDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddPetList    []*PetDetailInfo       `protobuf:"bytes,1,rep,name=addPetList,proto3" json:"addPetList,omitempty"`
	RemovePetList []*PetDetailInfo       `protobuf:"bytes,2,rep,name=removePetList,proto3" json:"removePetList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPetDetail) Reset() {
	*x = PushPetDetail{}
	mi := &file_petMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPetDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPetDetail) ProtoMessage() {}

func (x *PushPetDetail) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPetDetail.ProtoReflect.Descriptor instead.
func (*PushPetDetail) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{22}
}

func (x *PushPetDetail) GetAddPetList() []*PetDetailInfo {
	if x != nil {
		return x.AddPetList
	}
	return nil
}

func (x *PushPetDetail) GetRemovePetList() []*PetDetailInfo {
	if x != nil {
		return x.RemovePetList
	}
	return nil
}

type PetRecruitSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 1~3
	PetId         int32                  `protobuf:"varint,3,opt,name=petId,proto3" json:"petId,omitempty"` // 宠物配置ID
	State         int32                  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"` // 0=可招募, 1=已招募
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitSlot) Reset() {
	*x = PetRecruitSlot{}
	mi := &file_petMessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitSlot) ProtoMessage() {}

func (x *PetRecruitSlot) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitSlot.ProtoReflect.Descriptor instead.
func (*PetRecruitSlot) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{23}
}

func (x *PetRecruitSlot) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PetRecruitSlot) GetPetId() int32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *PetRecruitSlot) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type PetRecruitInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Slots              []*PetRecruitSlot      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`                            // 固定3个
	AutoRefreshUsed    int32                  `protobuf:"varint,2,opt,name=autoRefreshUsed,proto3" json:"autoRefreshUsed,omitempty"`       // 今日系统刷新已用次数
	NextRefreshTime    int64                  `protobuf:"varint,3,opt,name=nextRefreshTime,proto3" json:"nextRefreshTime,omitempty"`       // 下一次“系统刷新触发时间”(ms)
	ManualRefreshFree  int32                  `protobuf:"varint,4,opt,name=manualRefreshFree,proto3" json:"manualRefreshFree,omitempty"`   // 手动刷新是否免费,1为免费
	DiamondRecruitUsed int32                  `protobuf:"varint,5,opt,name=diamondRecruitUsed,proto3" json:"diamondRecruitUsed,omitempty"` // 今日已使用钻石招募次数（用于折扣）
	RecruitCost        int32                  `protobuf:"varint,6,opt,name=recruitCost,proto3" json:"recruitCost,omitempty"`               // 招募价格
	TripleRecruit      int32                  `protobuf:"varint,7,opt,name=tripleRecruit,proto3" json:"tripleRecruit,omitempty"`           // 1=三倍招募 0=普通招募
	RecruitType        int32                  `protobuf:"varint,8,opt,name=recruitType,proto3" json:"recruitType,omitempty"`               // 1=招募券 2=钻石
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PetRecruitInfo) Reset() {
	*x = PetRecruitInfo{}
	mi := &file_petMessage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitInfo) ProtoMessage() {}

func (x *PetRecruitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitInfo.ProtoReflect.Descriptor instead.
func (*PetRecruitInfo) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{24}
}

func (x *PetRecruitInfo) GetSlots() []*PetRecruitSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *PetRecruitInfo) GetAutoRefreshUsed() int32 {
	if x != nil {
		return x.AutoRefreshUsed
	}
	return 0
}

func (x *PetRecruitInfo) GetNextRefreshTime() int64 {
	if x != nil {
		return x.NextRefreshTime
	}
	return 0
}

func (x *PetRecruitInfo) GetManualRefreshFree() int32 {
	if x != nil {
		return x.ManualRefreshFree
	}
	return 0
}

func (x *PetRecruitInfo) GetDiamondRecruitUsed() int32 {
	if x != nil {
		return x.DiamondRecruitUsed
	}
	return 0
}

func (x *PetRecruitInfo) GetRecruitCost() int32 {
	if x != nil {
		return x.RecruitCost
	}
	return 0
}

func (x *PetRecruitInfo) GetTripleRecruit() int32 {
	if x != nil {
		return x.TripleRecruit
	}
	return 0
}

func (x *PetRecruitInfo) GetRecruitType() int32 {
	if x != nil {
		return x.RecruitType
	}
	return 0
}

type PetRecruitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecruitType   int32                  `protobuf:"varint,1,opt,name=recruitType,proto3" json:"recruitType,omitempty"`     // 1=招募券 2=钻石
	TripleRecruit int32                  `protobuf:"varint,2,opt,name=tripleRecruit,proto3" json:"tripleRecruit,omitempty"` // 1=三倍招募 0=普通招募
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitReq) Reset() {
	*x = PetRecruitReq{}
	mi := &file_petMessage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitReq) ProtoMessage() {}

func (x *PetRecruitReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitReq.ProtoReflect.Descriptor instead.
func (*PetRecruitReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{25}
}

func (x *PetRecruitReq) GetRecruitType() int32 {
	if x != nil {
		return x.RecruitType
	}
	return 0
}

func (x *PetRecruitReq) GetTripleRecruit() int32 {
	if x != nil {
		return x.TripleRecruit
	}
	return 0
}

type PetRecruitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicInfo     *PetRecruitInfo        `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`      // 返回最新面板（可能触动了自动刷新）
	GainedPetId   int32                  `protobuf:"varint,2,opt,name=gainedPetId,proto3" json:"gainedPetId,omitempty"` // 实际获得petId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitResp) Reset() {
	*x = PetRecruitResp{}
	mi := &file_petMessage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitResp) ProtoMessage() {}

func (x *PetRecruitResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitResp.ProtoReflect.Descriptor instead.
func (*PetRecruitResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{26}
}

func (x *PetRecruitResp) GetBasicInfo() *PetRecruitInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *PetRecruitResp) GetGainedPetId() int32 {
	if x != nil {
		return x.GainedPetId
	}
	return 0
}

type PetRecruitDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitDetailReq) Reset() {
	*x = PetRecruitDetailReq{}
	mi := &file_petMessage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitDetailReq) ProtoMessage() {}

func (x *PetRecruitDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitDetailReq.ProtoReflect.Descriptor instead.
func (*PetRecruitDetailReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{27}
}

type PetRecruitDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicInfo     *PetRecruitInfo        `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitDetailResp) Reset() {
	*x = PetRecruitDetailResp{}
	mi := &file_petMessage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitDetailResp) ProtoMessage() {}

func (x *PetRecruitDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitDetailResp.ProtoReflect.Descriptor instead.
func (*PetRecruitDetailResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{28}
}

func (x *PetRecruitDetailResp) GetBasicInfo() *PetRecruitInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

type PetRecruitRefreshReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitRefreshReq) Reset() {
	*x = PetRecruitRefreshReq{}
	mi := &file_petMessage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitRefreshReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitRefreshReq) ProtoMessage() {}

func (x *PetRecruitRefreshReq) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitRefreshReq.ProtoReflect.Descriptor instead.
func (*PetRecruitRefreshReq) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{29}
}

type PetRecruitRefreshResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicInfo     *PetRecruitInfo        `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetRecruitRefreshResp) Reset() {
	*x = PetRecruitRefreshResp{}
	mi := &file_petMessage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetRecruitRefreshResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetRecruitRefreshResp) ProtoMessage() {}

func (x *PetRecruitRefreshResp) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetRecruitRefreshResp.ProtoReflect.Descriptor instead.
func (*PetRecruitRefreshResp) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{30}
}

func (x *PetRecruitRefreshResp) GetBasicInfo() *PetRecruitInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

type PushPetRecruitChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasicInfo     *PetRecruitInfo        `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPetRecruitChange) Reset() {
	*x = PushPetRecruitChange{}
	mi := &file_petMessage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPetRecruitChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPetRecruitChange) ProtoMessage() {}

func (x *PushPetRecruitChange) ProtoReflect() protoreflect.Message {
	mi := &file_petMessage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPetRecruitChange.ProtoReflect.Descriptor instead.
func (*PushPetRecruitChange) Descriptor() ([]byte, []int) {
	return file_petMessage_proto_rawDescGZIP(), []int{31}
}

func (x *PushPetRecruitChange) GetBasicInfo() *PetRecruitInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

var File_petMessage_proto protoreflect.FileDescriptor

const file_petMessage_proto_rawDesc = "" +
	"\n" +
	"\x10petMessage.proto\x12\x02pb\"\xb1\x02\n" +
	"\rPetDetailInfo\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12\x14\n" +
	"\x05petId\x18\x02 \x01(\x05R\x05petId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04star\x18\x04 \x01(\x05R\x04star\x12\x1c\n" +
	"\theroOwnId\x18\x05 \x01(\x03R\theroOwnId\x12A\n" +
	"\n" +
	"Attributes\x18\x06 \x03(\v2!.pb.PetDetailInfo.AttributesEntryR\n" +
	"Attributes\x12$\n" +
	"\rpassiveSkills\x18\a \x03(\x05R\rpassiveSkills\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"*\n" +
	"\fPetDetailReq\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\"4\n" +
	"\rPetDetailResp\x12#\n" +
	"\x03pet\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\x03pet\"m\n" +
	"\vPetEquipReq\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12\x1c\n" +
	"\theroOwnId\x18\x02 \x01(\x03R\theroOwnId\x12$\n" +
	"\roperationType\x18\x03 \x01(\x05R\roperationType\"3\n" +
	"\fPetEquipResp\x12#\n" +
	"\x03pet\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\x03pet\"M\n" +
	"\rPetLevelUpReq\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12 \n" +
	"\vlevelUpType\x18\x02 \x01(\x05R\vlevelUpType\"5\n" +
	"\x0ePetLevelUpResp\x12#\n" +
	"\x03pet\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\x03pet\"H\n" +
	"\fPetStarUpReq\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\x12\x1c\n" +
	"\tpetOwnIds\x18\x02 \x03(\x03R\tpetOwnIds\"4\n" +
	"\rPetStarUpResp\x12#\n" +
	"\x03pet\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\x03pet\"+\n" +
	"\rPetRebirthReq\x12\x1a\n" +
	"\bpetOwnId\x18\x01 \x01(\x03R\bpetOwnId\"5\n" +
	"\x0ePetRebirthResp\x12#\n" +
	"\x03pet\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\x03pet\"/\n" +
	"\x0fPetDecomposeReq\x12\x1c\n" +
	"\tpetOwnIds\x18\x01 \x03(\x03R\tpetOwnIds\"0\n" +
	"\x10PetDecomposeResp\x12\x1c\n" +
	"\tisSuccess\x18\x01 \x01(\bR\tisSuccess\"3\n" +
	"\x1bPetMaxLevelMaxStarDetailReq\x12\x14\n" +
	"\x05petId\x18\x01 \x01(\x05R\x05petId\"K\n" +
	"\x1cPetMaxLevelMaxStarDetailResp\x12+\n" +
	"\apetInfo\x18\x01 \x01(\v2\x11.pb.PetDetailInfoR\apetInfo\"\xcb\x01\n" +
	"\x0fPetAffinityInfo\x12\x1e\n" +
	"\n" +
	"affinityId\x18\x01 \x01(\x05R\n" +
	"affinityId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12C\n" +
	"\n" +
	"Attributes\x18\x03 \x03(\v2#.pb.PetAffinityInfo.AttributesEntryR\n" +
	"Attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"B\n" +
	"\x10PetStarBookEntry\x12\x14\n" +
	"\x05petId\x18\x01 \x01(\x05R\x05petId\x12\x18\n" +
	"\amaxStar\x18\x02 \x01(\x05R\amaxStar\"G\n" +
	"\x15PushPetStarBookChange\x12.\n" +
	"\achanged\x18\x01 \x03(\v2\x14.pb.PetStarBookEntryR\achanged\"7\n" +
	"\x15PetAffinityLevelUpReq\x12\x1e\n" +
	"\n" +
	"affinityId\x18\x01 \x01(\x05R\n" +
	"affinityId\"A\n" +
	"\x16PetAffinityLevelUpResp\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.pb.PetAffinityInfoR\x04info\"\x14\n" +
	"\x12PetAffinityListReq\">\n" +
	"\x13PetAffinityListResp\x12'\n" +
	"\x04info\x18\x01 \x03(\v2\x13.pb.PetAffinityInfoR\x04info\"{\n" +
	"\rPushPetDetail\x121\n" +
	"\n" +
	"addPetList\x18\x01 \x03(\v2\x11.pb.PetDetailInfoR\n" +
	"addPetList\x127\n" +
	"\rremovePetList\x18\x02 \x03(\v2\x11.pb.PetDetailInfoR\rremovePetList\"R\n" +
	"\x0ePetRecruitSlot\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05petId\x18\x03 \x01(\x05R\x05petId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\x05R\x05state\"\xd6\x02\n" +
	"\x0ePetRecruitInfo\x12(\n" +
	"\x05slots\x18\x01 \x03(\v2\x12.pb.PetRecruitSlotR\x05slots\x12(\n" +
	"\x0fautoRefreshUsed\x18\x02 \x01(\x05R\x0fautoRefreshUsed\x12(\n" +
	"\x0fnextRefreshTime\x18\x03 \x01(\x03R\x0fnextRefreshTime\x12,\n" +
	"\x11manualRefreshFree\x18\x04 \x01(\x05R\x11manualRefreshFree\x12.\n" +
	"\x12diamondRecruitUsed\x18\x05 \x01(\x05R\x12diamondRecruitUsed\x12 \n" +
	"\vrecruitCost\x18\x06 \x01(\x05R\vrecruitCost\x12$\n" +
	"\rtripleRecruit\x18\a \x01(\x05R\rtripleRecruit\x12 \n" +
	"\vrecruitType\x18\b \x01(\x05R\vrecruitType\"W\n" +
	"\rPetRecruitReq\x12 \n" +
	"\vrecruitType\x18\x01 \x01(\x05R\vrecruitType\x12$\n" +
	"\rtripleRecruit\x18\x02 \x01(\x05R\rtripleRecruit\"d\n" +
	"\x0ePetRecruitResp\x120\n" +
	"\tbasicInfo\x18\x01 \x01(\v2\x12.pb.PetRecruitInfoR\tbasicInfo\x12 \n" +
	"\vgainedPetId\x18\x02 \x01(\x05R\vgainedPetId\"\x15\n" +
	"\x13PetRecruitDetailReq\"H\n" +
	"\x14PetRecruitDetailResp\x120\n" +
	"\tbasicInfo\x18\x01 \x01(\v2\x12.pb.PetRecruitInfoR\tbasicInfo\"\x16\n" +
	"\x14PetRecruitRefreshReq\"I\n" +
	"\x15PetRecruitRefreshResp\x120\n" +
	"\tbasicInfo\x18\x01 \x01(\v2\x12.pb.PetRecruitInfoR\tbasicInfo\"H\n" +
	"\x14PushPetRecruitChange\x120\n" +
	"\tbasicInfo\x18\x01 \x01(\v2\x12.pb.PetRecruitInfoR\tbasicInfoB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_petMessage_proto_rawDescOnce sync.Once
	file_petMessage_proto_rawDescData []byte
)

func file_petMessage_proto_rawDescGZIP() []byte {
	file_petMessage_proto_rawDescOnce.Do(func() {
		file_petMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_petMessage_proto_rawDesc), len(file_petMessage_proto_rawDesc)))
	})
	return file_petMessage_proto_rawDescData
}

var file_petMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_petMessage_proto_goTypes = []any{
	(*PetDetailInfo)(nil),                // 0: pb.PetDetailInfo
	(*PetDetailReq)(nil),                 // 1: pb.PetDetailReq
	(*PetDetailResp)(nil),                // 2: pb.PetDetailResp
	(*PetEquipReq)(nil),                  // 3: pb.PetEquipReq
	(*PetEquipResp)(nil),                 // 4: pb.PetEquipResp
	(*PetLevelUpReq)(nil),                // 5: pb.PetLevelUpReq
	(*PetLevelUpResp)(nil),               // 6: pb.PetLevelUpResp
	(*PetStarUpReq)(nil),                 // 7: pb.PetStarUpReq
	(*PetStarUpResp)(nil),                // 8: pb.PetStarUpResp
	(*PetRebirthReq)(nil),                // 9: pb.PetRebirthReq
	(*PetRebirthResp)(nil),               // 10: pb.PetRebirthResp
	(*PetDecomposeReq)(nil),              // 11: pb.PetDecomposeReq
	(*PetDecomposeResp)(nil),             // 12: pb.PetDecomposeResp
	(*PetMaxLevelMaxStarDetailReq)(nil),  // 13: pb.PetMaxLevelMaxStarDetailReq
	(*PetMaxLevelMaxStarDetailResp)(nil), // 14: pb.PetMaxLevelMaxStarDetailResp
	(*PetAffinityInfo)(nil),              // 15: pb.PetAffinityInfo
	(*PetStarBookEntry)(nil),             // 16: pb.PetStarBookEntry
	(*PushPetStarBookChange)(nil),        // 17: pb.PushPetStarBookChange
	(*PetAffinityLevelUpReq)(nil),        // 18: pb.PetAffinityLevelUpReq
	(*PetAffinityLevelUpResp)(nil),       // 19: pb.PetAffinityLevelUpResp
	(*PetAffinityListReq)(nil),           // 20: pb.PetAffinityListReq
	(*PetAffinityListResp)(nil),          // 21: pb.PetAffinityListResp
	(*PushPetDetail)(nil),                // 22: pb.PushPetDetail
	(*PetRecruitSlot)(nil),               // 23: pb.PetRecruitSlot
	(*PetRecruitInfo)(nil),               // 24: pb.PetRecruitInfo
	(*PetRecruitReq)(nil),                // 25: pb.PetRecruitReq
	(*PetRecruitResp)(nil),               // 26: pb.PetRecruitResp
	(*PetRecruitDetailReq)(nil),          // 27: pb.PetRecruitDetailReq
	(*PetRecruitDetailResp)(nil),         // 28: pb.PetRecruitDetailResp
	(*PetRecruitRefreshReq)(nil),         // 29: pb.PetRecruitRefreshReq
	(*PetRecruitRefreshResp)(nil),        // 30: pb.PetRecruitRefreshResp
	(*PushPetRecruitChange)(nil),         // 31: pb.PushPetRecruitChange
	nil,                                  // 32: pb.PetDetailInfo.AttributesEntry
	nil,                                  // 33: pb.PetAffinityInfo.AttributesEntry
}
var file_petMessage_proto_depIdxs = []int32{
	32, // 0: pb.PetDetailInfo.Attributes:type_name -> pb.PetDetailInfo.AttributesEntry
	0,  // 1: pb.PetDetailResp.pet:type_name -> pb.PetDetailInfo
	0,  // 2: pb.PetEquipResp.pet:type_name -> pb.PetDetailInfo
	0,  // 3: pb.PetLevelUpResp.pet:type_name -> pb.PetDetailInfo
	0,  // 4: pb.PetStarUpResp.pet:type_name -> pb.PetDetailInfo
	0,  // 5: pb.PetRebirthResp.pet:type_name -> pb.PetDetailInfo
	0,  // 6: pb.PetMaxLevelMaxStarDetailResp.petInfo:type_name -> pb.PetDetailInfo
	33, // 7: pb.PetAffinityInfo.Attributes:type_name -> pb.PetAffinityInfo.AttributesEntry
	16, // 8: pb.PushPetStarBookChange.changed:type_name -> pb.PetStarBookEntry
	15, // 9: pb.PetAffinityLevelUpResp.info:type_name -> pb.PetAffinityInfo
	15, // 10: pb.PetAffinityListResp.info:type_name -> pb.PetAffinityInfo
	0,  // 11: pb.PushPetDetail.addPetList:type_name -> pb.PetDetailInfo
	0,  // 12: pb.PushPetDetail.removePetList:type_name -> pb.PetDetailInfo
	23, // 13: pb.PetRecruitInfo.slots:type_name -> pb.PetRecruitSlot
	24, // 14: pb.PetRecruitResp.basicInfo:type_name -> pb.PetRecruitInfo
	24, // 15: pb.PetRecruitDetailResp.basicInfo:type_name -> pb.PetRecruitInfo
	24, // 16: pb.PetRecruitRefreshResp.basicInfo:type_name -> pb.PetRecruitInfo
	24, // 17: pb.PushPetRecruitChange.basicInfo:type_name -> pb.PetRecruitInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_petMessage_proto_init() }
func file_petMessage_proto_init() {
	if File_petMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_petMessage_proto_rawDesc), len(file_petMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_petMessage_proto_goTypes,
		DependencyIndexes: file_petMessage_proto_depIdxs,
		MessageInfos:      file_petMessage_proto_msgTypes,
	}.Build()
	File_petMessage_proto = out.File
	file_petMessage_proto_goTypes = nil
	file_petMessage_proto_depIdxs = nil
}
