// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: shopMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取商城物品
type GetShopInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopType      int32                  `protobuf:"varint,1,opt,name=shopType,proto3" json:"shopType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopInfoReq) Reset() {
	*x = GetShopInfoReq{}
	mi := &file_shopMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopInfoReq) ProtoMessage() {}

func (x *GetShopInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopInfoReq.ProtoReflect.Descriptor instead.
func (*GetShopInfoReq) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{0}
}

func (x *GetShopInfoReq) GetShopType() int32 {
	if x != nil {
		return x.ShopType
	}
	return 0
}

// 获取商城物品
type GetShopInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopInfos     map[int32]*ShopInfo    `protobuf:"bytes,1,rep,name=shopInfos,proto3" json:"shopInfos,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 商城物品信息
	PassInfo      []*PassItemInfo        `protobuf:"bytes,2,rep,name=passInfo,proto3" json:"passInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopInfoResp) Reset() {
	*x = GetShopInfoResp{}
	mi := &file_shopMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopInfoResp) ProtoMessage() {}

func (x *GetShopInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopInfoResp.ProtoReflect.Descriptor instead.
func (*GetShopInfoResp) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{1}
}

func (x *GetShopInfoResp) GetShopInfos() map[int32]*ShopInfo {
	if x != nil {
		return x.ShopInfos
	}
	return nil
}

func (x *GetShopInfoResp) GetPassInfo() []*PassItemInfo {
	if x != nil {
		return x.PassInfo
	}
	return nil
}

// 商城物品信息
type ShopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShopType      int32                  `protobuf:"varint,1,opt,name=shopType,proto3" json:"shopType,omitempty"`  // 商城类型
	ItemInfos     []*ShopItemInfo        `protobuf:"bytes,2,rep,name=itemInfos,proto3" json:"itemInfos,omitempty"` // 商城物品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopInfo) Reset() {
	*x = ShopInfo{}
	mi := &file_shopMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopInfo) ProtoMessage() {}

func (x *ShopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopInfo.ProtoReflect.Descriptor instead.
func (*ShopInfo) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ShopInfo) GetShopType() int32 {
	if x != nil {
		return x.ShopType
	}
	return 0
}

func (x *ShopInfo) GetItemInfos() []*ShopItemInfo {
	if x != nil {
		return x.ItemInfos
	}
	return nil
}

// 商城物品信息
type ShopItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`         // 商城物品id
	BuyCount      int32                  `protobuf:"varint,2,opt,name=buyCount,proto3" json:"buyCount,omitempty"`     // 购买数量
	LeftTime      int64                  `protobuf:"varint,3,opt,name=leftTime,proto3" json:"leftTime,omitempty"`     // 剩余时间
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`         // 0:可见 1:可购买
	UnlockTime    int64                  `protobuf:"varint,5,opt,name=unlockTime,proto3" json:"unlockTime,omitempty"` // 解锁时间
	IsFirstBuy    bool                   `protobuf:"varint,6,opt,name=isFirstBuy,proto3" json:"isFirstBuy,omitempty"` // 是否是第一次购买
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItemInfo) Reset() {
	*x = ShopItemInfo{}
	mi := &file_shopMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItemInfo) ProtoMessage() {}

func (x *ShopItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItemInfo.ProtoReflect.Descriptor instead.
func (*ShopItemInfo) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{3}
}

func (x *ShopItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ShopItemInfo) GetBuyCount() int32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *ShopItemInfo) GetLeftTime() int64 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *ShopItemInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ShopItemInfo) GetUnlockTime() int64 {
	if x != nil {
		return x.UnlockTime
	}
	return 0
}

func (x *ShopItemInfo) GetIsFirstBuy() bool {
	if x != nil {
		return x.IsFirstBuy
	}
	return false
}

// 周卡信息
type PassItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`       // 周卡物品id
	CanAccept     bool                   `protobuf:"varint,2,opt,name=canAccept,proto3" json:"canAccept,omitempty"` // 是否能领取
	LeftTimes     int32                  `protobuf:"varint,3,opt,name=leftTimes,proto3" json:"leftTimes,omitempty"` // 剩余次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassItemInfo) Reset() {
	*x = PassItemInfo{}
	mi := &file_shopMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassItemInfo) ProtoMessage() {}

func (x *PassItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassItemInfo.ProtoReflect.Descriptor instead.
func (*PassItemInfo) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{4}
}

func (x *PassItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *PassItemInfo) GetCanAccept() bool {
	if x != nil {
		return x.CanAccept
	}
	return false
}

func (x *PassItemInfo) GetLeftTimes() int32 {
	if x != nil {
		return x.LeftTimes
	}
	return 0
}

// 购买商城物品
type BuyShopItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                      // 商城物品id
	ItemIds       map[int32]int32        `protobuf:"bytes,2,rep,name=itemIds,proto3" json:"itemIds,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 自选商品id
	UseToken      int32                  `protobuf:"varint,3,opt,name=useToken,proto3" json:"useToken,omitempty"`                                                                          // 使用代币
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyShopItemReq) Reset() {
	*x = BuyShopItemReq{}
	mi := &file_shopMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyShopItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyShopItemReq) ProtoMessage() {}

func (x *BuyShopItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyShopItemReq.ProtoReflect.Descriptor instead.
func (*BuyShopItemReq) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{5}
}

func (x *BuyShopItemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuyShopItemReq) GetItemIds() map[int32]int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *BuyShopItemReq) GetUseToken() int32 {
	if x != nil {
		return x.UseToken
	}
	return 0
}

// 购买商城物品
type BuyShopItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyShopItemResp) Reset() {
	*x = BuyShopItemResp{}
	mi := &file_shopMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyShopItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyShopItemResp) ProtoMessage() {}

func (x *BuyShopItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyShopItemResp.ProtoReflect.Descriptor instead.
func (*BuyShopItemResp) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{6}
}

func (x *BuyShopItemResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 获取周卡奖励
type GetPassAwardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 周卡id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassAwardReq) Reset() {
	*x = GetPassAwardReq{}
	mi := &file_shopMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassAwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassAwardReq) ProtoMessage() {}

func (x *GetPassAwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassAwardReq.ProtoReflect.Descriptor instead.
func (*GetPassAwardReq) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{7}
}

func (x *GetPassAwardReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取周卡奖励
type GetPassAwardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPassAwardResp) Reset() {
	*x = GetPassAwardResp{}
	mi := &file_shopMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPassAwardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPassAwardResp) ProtoMessage() {}

func (x *GetPassAwardResp) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPassAwardResp.ProtoReflect.Descriptor instead.
func (*GetPassAwardResp) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{8}
}

// 商城物品推送
type PushShopItemPop struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ItemInfos       []*ShopItemInfo        `protobuf:"bytes,1,rep,name=itemInfos,proto3" json:"itemInfos,omitempty"`             // 商城物品信息
	FirstChargeInfo []*PassItemInfo        `protobuf:"bytes,2,rep,name=firstChargeInfo,proto3" json:"firstChargeInfo,omitempty"` // 首充
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushShopItemPop) Reset() {
	*x = PushShopItemPop{}
	mi := &file_shopMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushShopItemPop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushShopItemPop) ProtoMessage() {}

func (x *PushShopItemPop) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushShopItemPop.ProtoReflect.Descriptor instead.
func (*PushShopItemPop) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{9}
}

func (x *PushShopItemPop) GetItemInfos() []*ShopItemInfo {
	if x != nil {
		return x.ItemInfos
	}
	return nil
}

func (x *PushShopItemPop) GetFirstChargeInfo() []*PassItemInfo {
	if x != nil {
		return x.FirstChargeInfo
	}
	return nil
}

// 购买信息推送
type PushOrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 商城物品id
	OrderId       int64                  `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`        //订单号，代币购买为空
	IsCoupon      bool                   `protobuf:"varint,3,opt,name=isCoupon,proto3" json:"isCoupon,omitempty"`      //是否是代金券订单
	PayPlatform   string                 `protobuf:"bytes,4,opt,name=payPlatform,proto3" json:"payPlatform,omitempty"` // 支付平台
	GpOrderId     string                 `protobuf:"bytes,5,opt,name=gpOrderId,proto3" json:"gpOrderId,omitempty"`     //谷歌的订单id，ios的transaction_id
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`             //埋点用，谷歌传，ios不传
	IsSandbox     bool                   `protobuf:"varint,7,opt,name=isSandbox,proto3" json:"isSandbox,omitempty"`    //是否是沙盒支付
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOrderInfo) Reset() {
	*x = PushOrderInfo{}
	mi := &file_shopMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOrderInfo) ProtoMessage() {}

func (x *PushOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shopMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOrderInfo.ProtoReflect.Descriptor instead.
func (*PushOrderInfo) Descriptor() ([]byte, []int) {
	return file_shopMessage_proto_rawDescGZIP(), []int{10}
}

func (x *PushOrderInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PushOrderInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PushOrderInfo) GetIsCoupon() bool {
	if x != nil {
		return x.IsCoupon
	}
	return false
}

func (x *PushOrderInfo) GetPayPlatform() string {
	if x != nil {
		return x.PayPlatform
	}
	return ""
}

func (x *PushOrderInfo) GetGpOrderId() string {
	if x != nil {
		return x.GpOrderId
	}
	return ""
}

func (x *PushOrderInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushOrderInfo) GetIsSandbox() bool {
	if x != nil {
		return x.IsSandbox
	}
	return false
}

var File_shopMessage_proto protoreflect.FileDescriptor

const file_shopMessage_proto_rawDesc = "" +
	"\n" +
	"\x11shopMessage.proto\x12\x02pb\",\n" +
	"\x0eGetShopInfoReq\x12\x1a\n" +
	"\bshopType\x18\x01 \x01(\x05R\bshopType\"\xcd\x01\n" +
	"\x0fGetShopInfoResp\x12@\n" +
	"\tshopInfos\x18\x01 \x03(\v2\".pb.GetShopInfoResp.ShopInfosEntryR\tshopInfos\x12,\n" +
	"\bpassInfo\x18\x02 \x03(\v2\x10.pb.PassItemInfoR\bpassInfo\x1aJ\n" +
	"\x0eShopInfosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.pb.ShopInfoR\x05value:\x028\x01\"V\n" +
	"\bShopInfo\x12\x1a\n" +
	"\bshopType\x18\x01 \x01(\x05R\bshopType\x12.\n" +
	"\titemInfos\x18\x02 \x03(\v2\x10.pb.ShopItemInfoR\titemInfos\"\xb6\x01\n" +
	"\fShopItemInfo\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x1a\n" +
	"\bbuyCount\x18\x02 \x01(\x05R\bbuyCount\x12\x1a\n" +
	"\bleftTime\x18\x03 \x01(\x03R\bleftTime\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"unlockTime\x18\x05 \x01(\x03R\n" +
	"unlockTime\x12\x1e\n" +
	"\n" +
	"isFirstBuy\x18\x06 \x01(\bR\n" +
	"isFirstBuy\"b\n" +
	"\fPassItemInfo\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x1c\n" +
	"\tcanAccept\x18\x02 \x01(\bR\tcanAccept\x12\x1c\n" +
	"\tleftTimes\x18\x03 \x01(\x05R\tleftTimes\"\xb3\x01\n" +
	"\x0eBuyShopItemReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\aitemIds\x18\x02 \x03(\v2\x1f.pb.BuyShopItemReq.ItemIdsEntryR\aitemIds\x12\x1a\n" +
	"\buseToken\x18\x03 \x01(\x05R\buseToken\x1a:\n" +
	"\fItemIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"+\n" +
	"\x0fBuyShopItemResp\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\"!\n" +
	"\x0fGetPassAwardReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x12\n" +
	"\x10GetPassAwardResp\"}\n" +
	"\x0fPushShopItemPop\x12.\n" +
	"\titemInfos\x18\x01 \x03(\v2\x10.pb.ShopItemInfoR\titemInfos\x12:\n" +
	"\x0ffirstChargeInfo\x18\x02 \x03(\v2\x10.pb.PassItemInfoR\x0ffirstChargeInfo\"\xc9\x01\n" +
	"\rPushOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aorderId\x18\x02 \x01(\x03R\aorderId\x12\x1a\n" +
	"\bisCoupon\x18\x03 \x01(\bR\bisCoupon\x12 \n" +
	"\vpayPlatform\x18\x04 \x01(\tR\vpayPlatform\x12\x1c\n" +
	"\tgpOrderId\x18\x05 \x01(\tR\tgpOrderId\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12\x1c\n" +
	"\tisSandbox\x18\a \x01(\bR\tisSandboxB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_shopMessage_proto_rawDescOnce sync.Once
	file_shopMessage_proto_rawDescData []byte
)

func file_shopMessage_proto_rawDescGZIP() []byte {
	file_shopMessage_proto_rawDescOnce.Do(func() {
		file_shopMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopMessage_proto_rawDesc), len(file_shopMessage_proto_rawDesc)))
	})
	return file_shopMessage_proto_rawDescData
}

var file_shopMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_shopMessage_proto_goTypes = []any{
	(*GetShopInfoReq)(nil),   // 0: pb.GetShopInfoReq
	(*GetShopInfoResp)(nil),  // 1: pb.GetShopInfoResp
	(*ShopInfo)(nil),         // 2: pb.ShopInfo
	(*ShopItemInfo)(nil),     // 3: pb.ShopItemInfo
	(*PassItemInfo)(nil),     // 4: pb.PassItemInfo
	(*BuyShopItemReq)(nil),   // 5: pb.BuyShopItemReq
	(*BuyShopItemResp)(nil),  // 6: pb.BuyShopItemResp
	(*GetPassAwardReq)(nil),  // 7: pb.GetPassAwardReq
	(*GetPassAwardResp)(nil), // 8: pb.GetPassAwardResp
	(*PushShopItemPop)(nil),  // 9: pb.PushShopItemPop
	(*PushOrderInfo)(nil),    // 10: pb.PushOrderInfo
	nil,                      // 11: pb.GetShopInfoResp.ShopInfosEntry
	nil,                      // 12: pb.BuyShopItemReq.ItemIdsEntry
}
var file_shopMessage_proto_depIdxs = []int32{
	11, // 0: pb.GetShopInfoResp.shopInfos:type_name -> pb.GetShopInfoResp.ShopInfosEntry
	4,  // 1: pb.GetShopInfoResp.passInfo:type_name -> pb.PassItemInfo
	3,  // 2: pb.ShopInfo.itemInfos:type_name -> pb.ShopItemInfo
	12, // 3: pb.BuyShopItemReq.itemIds:type_name -> pb.BuyShopItemReq.ItemIdsEntry
	3,  // 4: pb.PushShopItemPop.itemInfos:type_name -> pb.ShopItemInfo
	4,  // 5: pb.PushShopItemPop.firstChargeInfo:type_name -> pb.PassItemInfo
	2,  // 6: pb.GetShopInfoResp.ShopInfosEntry.value:type_name -> pb.ShopInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shopMessage_proto_init() }
func file_shopMessage_proto_init() {
	if File_shopMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopMessage_proto_rawDesc), len(file_shopMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shopMessage_proto_goTypes,
		DependencyIndexes: file_shopMessage_proto_depIdxs,
		MessageInfos:      file_shopMessage_proto_msgTypes,
	}.Build()
	File_shopMessage_proto = out.File
	file_shopMessage_proto_goTypes = nil
	file_shopMessage_proto_depIdxs = nil
}
