// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: taskMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDetailsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribution   int32                  `protobuf:"varint,1,opt,name=attribution,proto3" json:"attribution,omitempty"` // 任务归属 1:主线任务 2:支线任务 3:每日任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailsReq) Reset() {
	*x = TaskDetailsReq{}
	mi := &file_taskMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailsReq) ProtoMessage() {}

func (x *TaskDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailsReq.ProtoReflect.Descriptor instead.
func (*TaskDetailsReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDetailsReq) GetAttribution() int32 {
	if x != nil {
		return x.Attribution
	}
	return 0
}

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`       // 任务ID
	TaskState     int32                  `protobuf:"varint,2,opt,name=taskState,proto3" json:"taskState,omitempty"` // 任务状态 0:未完成 1:已完成未领取 2:已领取
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`   // 任务进度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_taskMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInfo) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskInfo) GetTaskState() int32 {
	if x != nil {
		return x.TaskState
	}
	return 0
}

func (x *TaskInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type TaskInfoStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribution   int32                  `protobuf:"varint,1,opt,name=attribution,proto3" json:"attribution,omitempty"` //任务归属
	TaskInfoList  []*TaskInfo            `protobuf:"bytes,2,rep,name=taskInfoList,proto3" json:"taskInfoList,omitempty"`
	DailyPoint    int32                  `protobuf:"varint,3,opt,name=dailyPoint,proto3" json:"dailyPoint,omitempty"`
	DailyBox      int32                  `protobuf:"varint,4,opt,name=dailyBox,proto3" json:"dailyBox,omitempty"`
	WeekPoint     int32                  `protobuf:"varint,5,opt,name=weekPoint,proto3" json:"weekPoint,omitempty"`
	WeekBox       int32                  `protobuf:"varint,6,opt,name=weekBox,proto3" json:"weekBox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoStruct) Reset() {
	*x = TaskInfoStruct{}
	mi := &file_taskMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoStruct) ProtoMessage() {}

func (x *TaskInfoStruct) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoStruct.ProtoReflect.Descriptor instead.
func (*TaskInfoStruct) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInfoStruct) GetAttribution() int32 {
	if x != nil {
		return x.Attribution
	}
	return 0
}

func (x *TaskInfoStruct) GetTaskInfoList() []*TaskInfo {
	if x != nil {
		return x.TaskInfoList
	}
	return nil
}

func (x *TaskInfoStruct) GetDailyPoint() int32 {
	if x != nil {
		return x.DailyPoint
	}
	return 0
}

func (x *TaskInfoStruct) GetDailyBox() int32 {
	if x != nil {
		return x.DailyBox
	}
	return 0
}

func (x *TaskInfoStruct) GetWeekPoint() int32 {
	if x != nil {
		return x.WeekPoint
	}
	return 0
}

func (x *TaskInfoStruct) GetWeekBox() int32 {
	if x != nil {
		return x.WeekBox
	}
	return 0
}

type TaskDetailsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskInfoList  []*TaskInfo            `protobuf:"bytes,1,rep,name=taskInfoList,proto3" json:"taskInfoList,omitempty"` // 任务信息列表
	DailyPoint    int32                  `protobuf:"varint,2,opt,name=dailyPoint,proto3" json:"dailyPoint,omitempty"`
	DailyBox      int32                  `protobuf:"varint,3,opt,name=dailyBox,proto3" json:"dailyBox,omitempty"`
	WeekPoint     int32                  `protobuf:"varint,4,opt,name=weekPoint,proto3" json:"weekPoint,omitempty"`
	WeekBox       int32                  `protobuf:"varint,5,opt,name=weekBox,proto3" json:"weekBox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetailsResp) Reset() {
	*x = TaskDetailsResp{}
	mi := &file_taskMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetailsResp) ProtoMessage() {}

func (x *TaskDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetailsResp.ProtoReflect.Descriptor instead.
func (*TaskDetailsResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{3}
}

func (x *TaskDetailsResp) GetTaskInfoList() []*TaskInfo {
	if x != nil {
		return x.TaskInfoList
	}
	return nil
}

func (x *TaskDetailsResp) GetDailyPoint() int32 {
	if x != nil {
		return x.DailyPoint
	}
	return 0
}

func (x *TaskDetailsResp) GetDailyBox() int32 {
	if x != nil {
		return x.DailyBox
	}
	return 0
}

func (x *TaskDetailsResp) GetWeekPoint() int32 {
	if x != nil {
		return x.WeekPoint
	}
	return 0
}

func (x *TaskDetailsResp) GetWeekBox() int32 {
	if x != nil {
		return x.WeekBox
	}
	return 0
}

type TaskRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribution   int32                  `protobuf:"varint,1,opt,name=attribution,proto3" json:"attribution,omitempty"` // 任务归属 1:主线任务 2:支线任务
	TaskId        int32                  `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`           // 任务ID
	RewardType    int32                  `protobuf:"varint,3,opt,name=rewardType,proto3" json:"rewardType,omitempty"`   // 奖励类型 1:一键领取 2:单个任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRewardReq) Reset() {
	*x = TaskRewardReq{}
	mi := &file_taskMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRewardReq) ProtoMessage() {}

func (x *TaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRewardReq.ProtoReflect.Descriptor instead.
func (*TaskRewardReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{4}
}

func (x *TaskRewardReq) GetAttribution() int32 {
	if x != nil {
		return x.Attribution
	}
	return 0
}

func (x *TaskRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRewardReq) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

type TaskRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=itemList,proto3" json:"itemList,omitempty"` // 领取道具id list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRewardResp) Reset() {
	*x = TaskRewardResp{}
	mi := &file_taskMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRewardResp) ProtoMessage() {}

func (x *TaskRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRewardResp.ProtoReflect.Descriptor instead.
func (*TaskRewardResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{5}
}

func (x *TaskRewardResp) GetItemList() []*ItemBasicInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type PushTaskUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribution   int32                  `protobuf:"varint,1,opt,name=attribution,proto3" json:"attribution,omitempty"` // 任务归属 1:主线任务 2:支线任务 3:每日任务
	TaskId        int32                  `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`           // 任务ID
	TaskState     int32                  `protobuf:"varint,3,opt,name=taskState,proto3" json:"taskState,omitempty"`     // 任务状态 0:未完成 1:已完成未领取 2:已领取
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`       // 任务进度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTaskUpdate) Reset() {
	*x = PushTaskUpdate{}
	mi := &file_taskMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTaskUpdate) ProtoMessage() {}

func (x *PushTaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTaskUpdate.ProtoReflect.Descriptor instead.
func (*PushTaskUpdate) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{6}
}

func (x *PushTaskUpdate) GetAttribution() int32 {
	if x != nil {
		return x.Attribution
	}
	return 0
}

func (x *PushTaskUpdate) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PushTaskUpdate) GetTaskState() int32 {
	if x != nil {
		return x.TaskState
	}
	return 0
}

func (x *PushTaskUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type TaskDailyRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RewardType    int32                  `protobuf:"varint,1,opt,name=rewardType,proto3" json:"rewardType,omitempty"` // 奖励类型 1:一键领取（进度条宝箱和所有已完成任务）  2：进度条宝箱 3：所有已完成任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDailyRewardReq) Reset() {
	*x = TaskDailyRewardReq{}
	mi := &file_taskMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDailyRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDailyRewardReq) ProtoMessage() {}

func (x *TaskDailyRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDailyRewardReq.ProtoReflect.Descriptor instead.
func (*TaskDailyRewardReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{7}
}

func (x *TaskDailyRewardReq) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

type TaskDailyRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=itemList,proto3" json:"itemList,omitempty"` // 领取道具id list
	DailyPoint    int32                  `protobuf:"varint,2,opt,name=dailyPoint,proto3" json:"dailyPoint,omitempty"`
	DailyBox      int32                  `protobuf:"varint,3,opt,name=dailyBox,proto3" json:"dailyBox,omitempty"`
	WeekPoint     int32                  `protobuf:"varint,4,opt,name=weekPoint,proto3" json:"weekPoint,omitempty"`
	WeekBox       int32                  `protobuf:"varint,5,opt,name=weekBox,proto3" json:"weekBox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDailyRewardResp) Reset() {
	*x = TaskDailyRewardResp{}
	mi := &file_taskMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDailyRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDailyRewardResp) ProtoMessage() {}

func (x *TaskDailyRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDailyRewardResp.ProtoReflect.Descriptor instead.
func (*TaskDailyRewardResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{8}
}

func (x *TaskDailyRewardResp) GetItemList() []*ItemBasicInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

func (x *TaskDailyRewardResp) GetDailyPoint() int32 {
	if x != nil {
		return x.DailyPoint
	}
	return 0
}

func (x *TaskDailyRewardResp) GetDailyBox() int32 {
	if x != nil {
		return x.DailyBox
	}
	return 0
}

func (x *TaskDailyRewardResp) GetWeekPoint() int32 {
	if x != nil {
		return x.WeekPoint
	}
	return 0
}

func (x *TaskDailyRewardResp) GetWeekBox() int32 {
	if x != nil {
		return x.WeekBox
	}
	return 0
}

type BountyRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int32                  `protobuf:"varint,1,opt,name=bountyId,proto3" json:"bountyId,omitempty"` // 悬赏令id
	TaskId        int32                  `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`     // 任务id 0 一键领取 其他 领取某个小任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BountyRewardReq) Reset() {
	*x = BountyRewardReq{}
	mi := &file_taskMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyRewardReq) ProtoMessage() {}

func (x *BountyRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyRewardReq.ProtoReflect.Descriptor instead.
func (*BountyRewardReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{9}
}

func (x *BountyRewardReq) GetBountyId() int32 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *BountyRewardReq) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type BountyRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemList      []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=itemList,proto3" json:"itemList,omitempty"` // 领取道具id list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BountyRewardResp) Reset() {
	*x = BountyRewardResp{}
	mi := &file_taskMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyRewardResp) ProtoMessage() {}

func (x *BountyRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyRewardResp.ProtoReflect.Descriptor instead.
func (*BountyRewardResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{10}
}

func (x *BountyRewardResp) GetItemList() []*ItemBasicInfo {
	if x != nil {
		return x.ItemList
	}
	return nil
}

type BountyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int32                  `protobuf:"varint,1,opt,name=bountyId,proto3" json:"bountyId,omitempty"` // 悬赏令id
	TaskList      []*TaskInfo            `protobuf:"bytes,2,rep,name=taskList,proto3" json:"taskList,omitempty"`  // 任务列表
	EndTime       int64                  `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`   // 结束时间 毫秒时间戳
	Status        int32                  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`     // 状态 0进行中 1已完成未领取 2已领取 4 超时未完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BountyInfo) Reset() {
	*x = BountyInfo{}
	mi := &file_taskMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BountyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BountyInfo) ProtoMessage() {}

func (x *BountyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BountyInfo.ProtoReflect.Descriptor instead.
func (*BountyInfo) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{11}
}

func (x *BountyInfo) GetBountyId() int32 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

func (x *BountyInfo) GetTaskList() []*TaskInfo {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *BountyInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BountyInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PushBountyStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BountyInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // 悬赏令信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBountyStart) Reset() {
	*x = PushBountyStart{}
	mi := &file_taskMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBountyStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBountyStart) ProtoMessage() {}

func (x *PushBountyStart) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBountyStart.ProtoReflect.Descriptor instead.
func (*PushBountyStart) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{12}
}

func (x *PushBountyStart) GetInfo() *BountyInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PushBountyEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int32                  `protobuf:"varint,1,opt,name=bountyId,proto3" json:"bountyId,omitempty"` // 悬赏令id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBountyEnd) Reset() {
	*x = PushBountyEnd{}
	mi := &file_taskMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBountyEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBountyEnd) ProtoMessage() {}

func (x *PushBountyEnd) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBountyEnd.ProtoReflect.Descriptor instead.
func (*PushBountyEnd) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{13}
}

func (x *PushBountyEnd) GetBountyId() int32 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type GetBountyDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BountyId      int32                  `protobuf:"varint,1,opt,name=bountyId,proto3" json:"bountyId,omitempty"` // 悬赏令id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyDetailReq) Reset() {
	*x = GetBountyDetailReq{}
	mi := &file_taskMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyDetailReq) ProtoMessage() {}

func (x *GetBountyDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyDetailReq.ProtoReflect.Descriptor instead.
func (*GetBountyDetailReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{14}
}

func (x *GetBountyDetailReq) GetBountyId() int32 {
	if x != nil {
		return x.BountyId
	}
	return 0
}

type GetBountyDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BountyInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // 悬赏令信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBountyDetailResp) Reset() {
	*x = GetBountyDetailResp{}
	mi := &file_taskMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBountyDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBountyDetailResp) ProtoMessage() {}

func (x *GetBountyDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBountyDetailResp.ProtoReflect.Descriptor instead.
func (*GetBountyDetailResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{15}
}

func (x *GetBountyDetailResp) GetInfo() *BountyInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PassCardtTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	FinishNum     int32                  `protobuf:"varint,3,opt,name=finishNum,proto3" json:"finishNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassCardtTaskInfo) Reset() {
	*x = PassCardtTaskInfo{}
	mi := &file_taskMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassCardtTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassCardtTaskInfo) ProtoMessage() {}

func (x *PassCardtTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassCardtTaskInfo.ProtoReflect.Descriptor instead.
func (*PassCardtTaskInfo) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{16}
}

func (x *PassCardtTaskInfo) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PassCardtTaskInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PassCardtTaskInfo) GetFinishNum() int32 {
	if x != nil {
		return x.FinishNum
	}
	return 0
}

type PassCardTask struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PassCardId           int32                  `protobuf:"varint,1,opt,name=passCardId,proto3" json:"passCardId,omitempty"`
	PassCardTaskInfoList []*PassCardtTaskInfo   `protobuf:"bytes,2,rep,name=passCardTaskInfoList,proto3" json:"passCardTaskInfoList,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PassCardTask) Reset() {
	*x = PassCardTask{}
	mi := &file_taskMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassCardTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassCardTask) ProtoMessage() {}

func (x *PassCardTask) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassCardTask.ProtoReflect.Descriptor instead.
func (*PassCardTask) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{17}
}

func (x *PassCardTask) GetPassCardId() int32 {
	if x != nil {
		return x.PassCardId
	}
	return 0
}

func (x *PassCardTask) GetPassCardTaskInfoList() []*PassCardtTaskInfo {
	if x != nil {
		return x.PassCardTaskInfoList
	}
	return nil
}

type AllianceDailyDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyBox      int32                  `protobuf:"varint,1,opt,name=dailyBox,proto3" json:"dailyBox,omitempty"` //联盟每日活跃宝箱领取阶段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllianceDailyDetail) Reset() {
	*x = AllianceDailyDetail{}
	mi := &file_taskMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllianceDailyDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceDailyDetail) ProtoMessage() {}

func (x *AllianceDailyDetail) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceDailyDetail.ProtoReflect.Descriptor instead.
func (*AllianceDailyDetail) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{18}
}

func (x *AllianceDailyDetail) GetDailyBox() int32 {
	if x != nil {
		return x.DailyBox
	}
	return 0
}

type AllianceDailyTaskRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RewardType    int32                  `protobuf:"varint,1,opt,name=rewardType,proto3" json:"rewardType,omitempty"` // 奖励类型 1:一键领取（进度条宝箱和所有已完成任务）  2：进度条宝箱 3：所有已完成任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllianceDailyTaskRewardReq) Reset() {
	*x = AllianceDailyTaskRewardReq{}
	mi := &file_taskMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllianceDailyTaskRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceDailyTaskRewardReq) ProtoMessage() {}

func (x *AllianceDailyTaskRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceDailyTaskRewardReq.ProtoReflect.Descriptor instead.
func (*AllianceDailyTaskRewardReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{19}
}

func (x *AllianceDailyTaskRewardReq) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

type AllianceDailyTaskRewardResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AllianceDailyDetail *AllianceDailyDetail   `protobuf:"bytes,1,opt,name=allianceDailyDetail,proto3" json:"allianceDailyDetail,omitempty"` // 联盟每日活跃宝箱领取阶段
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AllianceDailyTaskRewardResp) Reset() {
	*x = AllianceDailyTaskRewardResp{}
	mi := &file_taskMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllianceDailyTaskRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceDailyTaskRewardResp) ProtoMessage() {}

func (x *AllianceDailyTaskRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceDailyTaskRewardResp.ProtoReflect.Descriptor instead.
func (*AllianceDailyTaskRewardResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{20}
}

func (x *AllianceDailyTaskRewardResp) GetAllianceDailyDetail() *AllianceDailyDetail {
	if x != nil {
		return x.AllianceDailyDetail
	}
	return nil
}

type GetAllianceDailyTaskDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllianceDailyTaskDetailReq) Reset() {
	*x = GetAllianceDailyTaskDetailReq{}
	mi := &file_taskMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllianceDailyTaskDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllianceDailyTaskDetailReq) ProtoMessage() {}

func (x *GetAllianceDailyTaskDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllianceDailyTaskDetailReq.ProtoReflect.Descriptor instead.
func (*GetAllianceDailyTaskDetailReq) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{21}
}

type GetAllianceDailyTaskDetailResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AllianceDailyDetail *AllianceDailyDetail   `protobuf:"bytes,1,opt,name=allianceDailyDetail,proto3" json:"allianceDailyDetail,omitempty"` // 联盟每日活跃宝箱领取阶段
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAllianceDailyTaskDetailResp) Reset() {
	*x = GetAllianceDailyTaskDetailResp{}
	mi := &file_taskMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllianceDailyTaskDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllianceDailyTaskDetailResp) ProtoMessage() {}

func (x *GetAllianceDailyTaskDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_taskMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllianceDailyTaskDetailResp.ProtoReflect.Descriptor instead.
func (*GetAllianceDailyTaskDetailResp) Descriptor() ([]byte, []int) {
	return file_taskMessage_proto_rawDescGZIP(), []int{22}
}

func (x *GetAllianceDailyTaskDetailResp) GetAllianceDailyDetail() *AllianceDailyDetail {
	if x != nil {
		return x.AllianceDailyDetail
	}
	return nil
}

var File_taskMessage_proto protoreflect.FileDescriptor

const file_taskMessage_proto_rawDesc = "" +
	"\n" +
	"\x11taskMessage.proto\x12\x02pb\x1a\x13commonMessage.proto\"2\n" +
	"\x0eTaskDetailsReq\x12 \n" +
	"\vattribution\x18\x01 \x01(\x05R\vattribution\"\\\n" +
	"\bTaskInfo\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x05R\x06taskId\x12\x1c\n" +
	"\ttaskState\x18\x02 \x01(\x05R\ttaskState\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\"\xd8\x01\n" +
	"\x0eTaskInfoStruct\x12 \n" +
	"\vattribution\x18\x01 \x01(\x05R\vattribution\x120\n" +
	"\ftaskInfoList\x18\x02 \x03(\v2\f.pb.TaskInfoR\ftaskInfoList\x12\x1e\n" +
	"\n" +
	"dailyPoint\x18\x03 \x01(\x05R\n" +
	"dailyPoint\x12\x1a\n" +
	"\bdailyBox\x18\x04 \x01(\x05R\bdailyBox\x12\x1c\n" +
	"\tweekPoint\x18\x05 \x01(\x05R\tweekPoint\x12\x18\n" +
	"\aweekBox\x18\x06 \x01(\x05R\aweekBox\"\xb7\x01\n" +
	"\x0fTaskDetailsResp\x120\n" +
	"\ftaskInfoList\x18\x01 \x03(\v2\f.pb.TaskInfoR\ftaskInfoList\x12\x1e\n" +
	"\n" +
	"dailyPoint\x18\x02 \x01(\x05R\n" +
	"dailyPoint\x12\x1a\n" +
	"\bdailyBox\x18\x03 \x01(\x05R\bdailyBox\x12\x1c\n" +
	"\tweekPoint\x18\x04 \x01(\x05R\tweekPoint\x12\x18\n" +
	"\aweekBox\x18\x05 \x01(\x05R\aweekBox\"i\n" +
	"\rTaskRewardReq\x12 \n" +
	"\vattribution\x18\x01 \x01(\x05R\vattribution\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x05R\x06taskId\x12\x1e\n" +
	"\n" +
	"rewardType\x18\x03 \x01(\x05R\n" +
	"rewardType\"?\n" +
	"\x0eTaskRewardResp\x12-\n" +
	"\bitemList\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\bitemList\"\x84\x01\n" +
	"\x0ePushTaskUpdate\x12 \n" +
	"\vattribution\x18\x01 \x01(\x05R\vattribution\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x05R\x06taskId\x12\x1c\n" +
	"\ttaskState\x18\x03 \x01(\x05R\ttaskState\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\"4\n" +
	"\x12TaskDailyRewardReq\x12\x1e\n" +
	"\n" +
	"rewardType\x18\x01 \x01(\x05R\n" +
	"rewardType\"\xb8\x01\n" +
	"\x13TaskDailyRewardResp\x12-\n" +
	"\bitemList\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\bitemList\x12\x1e\n" +
	"\n" +
	"dailyPoint\x18\x02 \x01(\x05R\n" +
	"dailyPoint\x12\x1a\n" +
	"\bdailyBox\x18\x03 \x01(\x05R\bdailyBox\x12\x1c\n" +
	"\tweekPoint\x18\x04 \x01(\x05R\tweekPoint\x12\x18\n" +
	"\aweekBox\x18\x05 \x01(\x05R\aweekBox\"E\n" +
	"\x0fBountyRewardReq\x12\x1a\n" +
	"\bbountyId\x18\x01 \x01(\x05R\bbountyId\x12\x16\n" +
	"\x06taskId\x18\x02 \x01(\x05R\x06taskId\"A\n" +
	"\x10BountyRewardResp\x12-\n" +
	"\bitemList\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\bitemList\"\x84\x01\n" +
	"\n" +
	"BountyInfo\x12\x1a\n" +
	"\bbountyId\x18\x01 \x01(\x05R\bbountyId\x12(\n" +
	"\btaskList\x18\x02 \x03(\v2\f.pb.TaskInfoR\btaskList\x12\x18\n" +
	"\aEndTime\x18\x03 \x01(\x03R\aEndTime\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\x05R\x06Status\"5\n" +
	"\x0fPushBountyStart\x12\"\n" +
	"\x04info\x18\x01 \x01(\v2\x0e.pb.BountyInfoR\x04info\"+\n" +
	"\rPushBountyEnd\x12\x1a\n" +
	"\bbountyId\x18\x01 \x01(\x05R\bbountyId\"0\n" +
	"\x12GetBountyDetailReq\x12\x1a\n" +
	"\bbountyId\x18\x01 \x01(\x05R\bbountyId\"9\n" +
	"\x13GetBountyDetailResp\x12\"\n" +
	"\x04info\x18\x01 \x01(\v2\x0e.pb.BountyInfoR\x04info\"e\n" +
	"\x11PassCardtTaskInfo\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\x05R\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x1c\n" +
	"\tfinishNum\x18\x03 \x01(\x05R\tfinishNum\"y\n" +
	"\fPassCardTask\x12\x1e\n" +
	"\n" +
	"passCardId\x18\x01 \x01(\x05R\n" +
	"passCardId\x12I\n" +
	"\x14passCardTaskInfoList\x18\x02 \x03(\v2\x15.pb.PassCardtTaskInfoR\x14passCardTaskInfoList\"1\n" +
	"\x13AllianceDailyDetail\x12\x1a\n" +
	"\bdailyBox\x18\x01 \x01(\x05R\bdailyBox\"<\n" +
	"\x1aAllianceDailyTaskRewardReq\x12\x1e\n" +
	"\n" +
	"rewardType\x18\x01 \x01(\x05R\n" +
	"rewardType\"h\n" +
	"\x1bAllianceDailyTaskRewardResp\x12I\n" +
	"\x13allianceDailyDetail\x18\x01 \x01(\v2\x17.pb.AllianceDailyDetailR\x13allianceDailyDetail\"\x1f\n" +
	"\x1dGetAllianceDailyTaskDetailReq\"k\n" +
	"\x1eGetAllianceDailyTaskDetailResp\x12I\n" +
	"\x13allianceDailyDetail\x18\x01 \x01(\v2\x17.pb.AllianceDailyDetailR\x13allianceDailyDetailB\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_taskMessage_proto_rawDescOnce sync.Once
	file_taskMessage_proto_rawDescData []byte
)

func file_taskMessage_proto_rawDescGZIP() []byte {
	file_taskMessage_proto_rawDescOnce.Do(func() {
		file_taskMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskMessage_proto_rawDesc), len(file_taskMessage_proto_rawDesc)))
	})
	return file_taskMessage_proto_rawDescData
}

var file_taskMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_taskMessage_proto_goTypes = []any{
	(*TaskDetailsReq)(nil),                 // 0: pb.TaskDetailsReq
	(*TaskInfo)(nil),                       // 1: pb.TaskInfo
	(*TaskInfoStruct)(nil),                 // 2: pb.TaskInfoStruct
	(*TaskDetailsResp)(nil),                // 3: pb.TaskDetailsResp
	(*TaskRewardReq)(nil),                  // 4: pb.TaskRewardReq
	(*TaskRewardResp)(nil),                 // 5: pb.TaskRewardResp
	(*PushTaskUpdate)(nil),                 // 6: pb.PushTaskUpdate
	(*TaskDailyRewardReq)(nil),             // 7: pb.TaskDailyRewardReq
	(*TaskDailyRewardResp)(nil),            // 8: pb.TaskDailyRewardResp
	(*BountyRewardReq)(nil),                // 9: pb.BountyRewardReq
	(*BountyRewardResp)(nil),               // 10: pb.BountyRewardResp
	(*BountyInfo)(nil),                     // 11: pb.BountyInfo
	(*PushBountyStart)(nil),                // 12: pb.PushBountyStart
	(*PushBountyEnd)(nil),                  // 13: pb.PushBountyEnd
	(*GetBountyDetailReq)(nil),             // 14: pb.GetBountyDetailReq
	(*GetBountyDetailResp)(nil),            // 15: pb.GetBountyDetailResp
	(*PassCardtTaskInfo)(nil),              // 16: pb.PassCardtTaskInfo
	(*PassCardTask)(nil),                   // 17: pb.PassCardTask
	(*AllianceDailyDetail)(nil),            // 18: pb.AllianceDailyDetail
	(*AllianceDailyTaskRewardReq)(nil),     // 19: pb.AllianceDailyTaskRewardReq
	(*AllianceDailyTaskRewardResp)(nil),    // 20: pb.AllianceDailyTaskRewardResp
	(*GetAllianceDailyTaskDetailReq)(nil),  // 21: pb.GetAllianceDailyTaskDetailReq
	(*GetAllianceDailyTaskDetailResp)(nil), // 22: pb.GetAllianceDailyTaskDetailResp
	(*ItemBasicInfo)(nil),                  // 23: pb.ItemBasicInfo
}
var file_taskMessage_proto_depIdxs = []int32{
	1,  // 0: pb.TaskInfoStruct.taskInfoList:type_name -> pb.TaskInfo
	1,  // 1: pb.TaskDetailsResp.taskInfoList:type_name -> pb.TaskInfo
	23, // 2: pb.TaskRewardResp.itemList:type_name -> pb.ItemBasicInfo
	23, // 3: pb.TaskDailyRewardResp.itemList:type_name -> pb.ItemBasicInfo
	23, // 4: pb.BountyRewardResp.itemList:type_name -> pb.ItemBasicInfo
	1,  // 5: pb.BountyInfo.taskList:type_name -> pb.TaskInfo
	11, // 6: pb.PushBountyStart.info:type_name -> pb.BountyInfo
	11, // 7: pb.GetBountyDetailResp.info:type_name -> pb.BountyInfo
	16, // 8: pb.PassCardTask.passCardTaskInfoList:type_name -> pb.PassCardtTaskInfo
	18, // 9: pb.AllianceDailyTaskRewardResp.allianceDailyDetail:type_name -> pb.AllianceDailyDetail
	18, // 10: pb.GetAllianceDailyTaskDetailResp.allianceDailyDetail:type_name -> pb.AllianceDailyDetail
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_taskMessage_proto_init() }
func file_taskMessage_proto_init() {
	if File_taskMessage_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskMessage_proto_rawDesc), len(file_taskMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_taskMessage_proto_goTypes,
		DependencyIndexes: file_taskMessage_proto_depIdxs,
		MessageInfos:      file_taskMessage_proto_msgTypes,
	}.Build()
	File_taskMessage_proto = out.File
	file_taskMessage_proto_goTypes = nil
	file_taskMessage_proto_depIdxs = nil
}
