// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: vipCard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VipPrivilegeType int32

const (
	VipPrivilegeType_VIP_PRIVILEGE_NONE            VipPrivilegeType = 0  // NONE
	VipPrivilegeType_VIP_PRIVILEGE_NO_AD           VipPrivilegeType = 1  // 免广告【数据=时间 秒】
	VipPrivilegeType_VIP_PRIVILEGE_BATTLE_SPEED    VipPrivilegeType = 2  // 战斗加速【数据=万分比】
	VipPrivilegeType_VIP_PRIVILEGE_IDLE_TIME       VipPrivilegeType = 3  // 挂机时长【上限 秒】
	VipPrivilegeType_VIP_PRIVILEGE_IDLE_REWARD     VipPrivilegeType = 4  // 挂机奖励【快速领取钻石购买次数】
	VipPrivilegeType_VIP_PRIVILEGE_MAIN_REWARD     VipPrivilegeType = 5  // 主线奖励【触发特权掉落】
	VipPrivilegeType_VIP_PRIVILEGE_LOTTERY_GUAR    VipPrivilegeType = 6  // 抽卡保底【保底次数】
	VipPrivilegeType_VIP_PRIVILEGE_FATIGUE_LIMIT   VipPrivilegeType = 7  // 疲劳值上限【整数】
	VipPrivilegeType_VIP_PRIVILEGE_BUILD_QUEUE     VipPrivilegeType = 8  // 建筑队列【个数】
	VipPrivilegeType_VIP_PRIVILEGE_INSTANCE_TICKET VipPrivilegeType = 9  // 副本门票【每日免费次数】
	VipPrivilegeType_VIP_PRIVILEGE_RECRUITMENT     VipPrivilegeType = 10 // 招募权益【每日可领取招募奖励】
	VipPrivilegeType_VIP_PRIVILEGE_SPEED_ADD       VipPrivilegeType = 16 // 临时加速符特权
)

// Enum value maps for VipPrivilegeType.
var (
	VipPrivilegeType_name = map[int32]string{
		0:  "VIP_PRIVILEGE_NONE",
		1:  "VIP_PRIVILEGE_NO_AD",
		2:  "VIP_PRIVILEGE_BATTLE_SPEED",
		3:  "VIP_PRIVILEGE_IDLE_TIME",
		4:  "VIP_PRIVILEGE_IDLE_REWARD",
		5:  "VIP_PRIVILEGE_MAIN_REWARD",
		6:  "VIP_PRIVILEGE_LOTTERY_GUAR",
		7:  "VIP_PRIVILEGE_FATIGUE_LIMIT",
		8:  "VIP_PRIVILEGE_BUILD_QUEUE",
		9:  "VIP_PRIVILEGE_INSTANCE_TICKET",
		10: "VIP_PRIVILEGE_RECRUITMENT",
		16: "VIP_PRIVILEGE_SPEED_ADD",
	}
	VipPrivilegeType_value = map[string]int32{
		"VIP_PRIVILEGE_NONE":            0,
		"VIP_PRIVILEGE_NO_AD":           1,
		"VIP_PRIVILEGE_BATTLE_SPEED":    2,
		"VIP_PRIVILEGE_IDLE_TIME":       3,
		"VIP_PRIVILEGE_IDLE_REWARD":     4,
		"VIP_PRIVILEGE_MAIN_REWARD":     5,
		"VIP_PRIVILEGE_LOTTERY_GUAR":    6,
		"VIP_PRIVILEGE_FATIGUE_LIMIT":   7,
		"VIP_PRIVILEGE_BUILD_QUEUE":     8,
		"VIP_PRIVILEGE_INSTANCE_TICKET": 9,
		"VIP_PRIVILEGE_RECRUITMENT":     10,
		"VIP_PRIVILEGE_SPEED_ADD":       16,
	}
)

func (x VipPrivilegeType) Enum() *VipPrivilegeType {
	p := new(VipPrivilegeType)
	*p = x
	return p
}

func (x VipPrivilegeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VipPrivilegeType) Descriptor() protoreflect.EnumDescriptor {
	return file_vipCard_proto_enumTypes[0].Descriptor()
}

func (VipPrivilegeType) Type() protoreflect.EnumType {
	return &file_vipCard_proto_enumTypes[0]
}

func (x VipPrivilegeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VipPrivilegeType.Descriptor instead.
func (VipPrivilegeType) EnumDescriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{0}
}

// 单条特权能力数据
type VipPrivilegeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VipPrivilegeType       `protobuf:"varint,1,opt,name=type,proto3,enum=pb.VipPrivilegeType" json:"type,omitempty"` // 特权功能
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`                        // 数值（单位含义见枚举注释）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VipPrivilegeData) Reset() {
	*x = VipPrivilegeData{}
	mi := &file_vipCard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipPrivilegeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipPrivilegeData) ProtoMessage() {}

func (x *VipPrivilegeData) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipPrivilegeData.ProtoReflect.Descriptor instead.
func (*VipPrivilegeData) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{0}
}

func (x *VipPrivilegeData) GetType() VipPrivilegeType {
	if x != nil {
		return x.Type
	}
	return VipPrivilegeType_VIP_PRIVILEGE_NONE
}

func (x *VipPrivilegeData) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 一张特权卡的信息
type VipCardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`         // 特权卡的 itemId
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expireTime,proto3" json:"expireTime,omitempty"` // 过期时间（毫秒时间戳，-1 表示永久）
	Privs         []*VipPrivilegeData    `protobuf:"bytes,3,rep,name=privs,proto3" json:"privs,omitempty"`            // 该卡拥有的所有特权能力
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VipCardInfo) Reset() {
	*x = VipCardInfo{}
	mi := &file_vipCard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipCardInfo) ProtoMessage() {}

func (x *VipCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipCardInfo.ProtoReflect.Descriptor instead.
func (*VipCardInfo) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{1}
}

func (x *VipCardInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *VipCardInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *VipCardInfo) GetPrivs() []*VipPrivilegeData {
	if x != nil {
		return x.Privs
	}
	return nil
}

// 领取特权奖励请求
type ClaimPrivilegeRewardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RewardType    int32                  `protobuf:"varint,1,opt,name=rewardType,proto3" json:"rewardType,omitempty"` // 奖励类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPrivilegeRewardReq) Reset() {
	*x = ClaimPrivilegeRewardReq{}
	mi := &file_vipCard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPrivilegeRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPrivilegeRewardReq) ProtoMessage() {}

func (x *ClaimPrivilegeRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPrivilegeRewardReq.ProtoReflect.Descriptor instead.
func (*ClaimPrivilegeRewardReq) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimPrivilegeRewardReq) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

// 领取特权奖励响应
type ClaimPrivilegeRewardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*ItemBasicInfo       `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"` // 领取的道具列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPrivilegeRewardResp) Reset() {
	*x = ClaimPrivilegeRewardResp{}
	mi := &file_vipCard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPrivilegeRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPrivilegeRewardResp) ProtoMessage() {}

func (x *ClaimPrivilegeRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPrivilegeRewardResp.ProtoReflect.Descriptor instead.
func (*ClaimPrivilegeRewardResp) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimPrivilegeRewardResp) GetRewards() []*ItemBasicInfo {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type ClaimPrivilegeRewardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RewardType    int32                  `protobuf:"varint,1,opt,name=RewardType,proto3" json:"RewardType,omitempty"`       // 奖励类型
	LastClaimTime int64                  `protobuf:"varint,2,opt,name=LastClaimTime,proto3" json:"LastClaimTime,omitempty"` // 上次领取时间（毫秒时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPrivilegeRewardInfo) Reset() {
	*x = ClaimPrivilegeRewardInfo{}
	mi := &file_vipCard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPrivilegeRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPrivilegeRewardInfo) ProtoMessage() {}

func (x *ClaimPrivilegeRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPrivilegeRewardInfo.ProtoReflect.Descriptor instead.
func (*ClaimPrivilegeRewardInfo) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimPrivilegeRewardInfo) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *ClaimPrivilegeRewardInfo) GetLastClaimTime() int64 {
	if x != nil {
		return x.LastClaimTime
	}
	return 0
}

// 推送
type PushVipCardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *VipCardInfo           `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushVipCardInfo) Reset() {
	*x = PushVipCardInfo{}
	mi := &file_vipCard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushVipCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushVipCardInfo) ProtoMessage() {}

func (x *PushVipCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vipCard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushVipCardInfo.ProtoReflect.Descriptor instead.
func (*PushVipCardInfo) Descriptor() ([]byte, []int) {
	return file_vipCard_proto_rawDescGZIP(), []int{5}
}

func (x *PushVipCardInfo) GetInfo() *VipCardInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_vipCard_proto protoreflect.FileDescriptor

const file_vipCard_proto_rawDesc = "" +
	"\n" +
	"\rvipCard.proto\x12\x02pb\x1a\x13commonMessage.proto\"R\n" +
	"\x10VipPrivilegeData\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.pb.VipPrivilegeTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"q\n" +
	"\vVipCardInfo\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\x05R\x06itemId\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x02 \x01(\x03R\n" +
	"expireTime\x12*\n" +
	"\x05privs\x18\x03 \x03(\v2\x14.pb.VipPrivilegeDataR\x05privs\"9\n" +
	"\x17ClaimPrivilegeRewardReq\x12\x1e\n" +
	"\n" +
	"rewardType\x18\x01 \x01(\x05R\n" +
	"rewardType\"G\n" +
	"\x18ClaimPrivilegeRewardResp\x12+\n" +
	"\arewards\x18\x01 \x03(\v2\x11.pb.ItemBasicInfoR\arewards\"`\n" +
	"\x18ClaimPrivilegeRewardInfo\x12\x1e\n" +
	"\n" +
	"RewardType\x18\x01 \x01(\x05R\n" +
	"RewardType\x12$\n" +
	"\rLastClaimTime\x18\x02 \x01(\x03R\rLastClaimTime\"6\n" +
	"\x0fPushVipCardInfo\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.pb.VipCardInfoR\x04info*\xfd\x02\n" +
	"\x10VipPrivilegeType\x12\x16\n" +
	"\x12VIP_PRIVILEGE_NONE\x10\x00\x12\x17\n" +
	"\x13VIP_PRIVILEGE_NO_AD\x10\x01\x12\x1e\n" +
	"\x1aVIP_PRIVILEGE_BATTLE_SPEED\x10\x02\x12\x1b\n" +
	"\x17VIP_PRIVILEGE_IDLE_TIME\x10\x03\x12\x1d\n" +
	"\x19VIP_PRIVILEGE_IDLE_REWARD\x10\x04\x12\x1d\n" +
	"\x19VIP_PRIVILEGE_MAIN_REWARD\x10\x05\x12\x1e\n" +
	"\x1aVIP_PRIVILEGE_LOTTERY_GUAR\x10\x06\x12\x1f\n" +
	"\x1bVIP_PRIVILEGE_FATIGUE_LIMIT\x10\a\x12\x1d\n" +
	"\x19VIP_PRIVILEGE_BUILD_QUEUE\x10\b\x12!\n" +
	"\x1dVIP_PRIVILEGE_INSTANCE_TICKET\x10\t\x12\x1d\n" +
	"\x19VIP_PRIVILEGE_RECRUITMENT\x10\n" +
	"\x12\x1b\n" +
	"\x17VIP_PRIVILEGE_SPEED_ADD\x10\x10B\x10Z\x0e../logic/pb;pbb\x06proto3"

var (
	file_vipCard_proto_rawDescOnce sync.Once
	file_vipCard_proto_rawDescData []byte
)

func file_vipCard_proto_rawDescGZIP() []byte {
	file_vipCard_proto_rawDescOnce.Do(func() {
		file_vipCard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vipCard_proto_rawDesc), len(file_vipCard_proto_rawDesc)))
	})
	return file_vipCard_proto_rawDescData
}

var file_vipCard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vipCard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vipCard_proto_goTypes = []any{
	(VipPrivilegeType)(0),            // 0: pb.VipPrivilegeType
	(*VipPrivilegeData)(nil),         // 1: pb.VipPrivilegeData
	(*VipCardInfo)(nil),              // 2: pb.VipCardInfo
	(*ClaimPrivilegeRewardReq)(nil),  // 3: pb.ClaimPrivilegeRewardReq
	(*ClaimPrivilegeRewardResp)(nil), // 4: pb.ClaimPrivilegeRewardResp
	(*ClaimPrivilegeRewardInfo)(nil), // 5: pb.ClaimPrivilegeRewardInfo
	(*PushVipCardInfo)(nil),          // 6: pb.PushVipCardInfo
	(*ItemBasicInfo)(nil),            // 7: pb.ItemBasicInfo
}
var file_vipCard_proto_depIdxs = []int32{
	0, // 0: pb.VipPrivilegeData.type:type_name -> pb.VipPrivilegeType
	1, // 1: pb.VipCardInfo.privs:type_name -> pb.VipPrivilegeData
	7, // 2: pb.ClaimPrivilegeRewardResp.rewards:type_name -> pb.ItemBasicInfo
	2, // 3: pb.PushVipCardInfo.info:type_name -> pb.VipCardInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vipCard_proto_init() }
func file_vipCard_proto_init() {
	if File_vipCard_proto != nil {
		return
	}
	file_commonMessage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vipCard_proto_rawDesc), len(file_vipCard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vipCard_proto_goTypes,
		DependencyIndexes: file_vipCard_proto_depIdxs,
		EnumInfos:         file_vipCard_proto_enumTypes,
		MessageInfos:      file_vipCard_proto_msgTypes,
	}.Build()
	File_vipCard_proto = out.File
	file_vipCard_proto_goTypes = nil
	file_vipCard_proto_depIdxs = nil
}
